// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/port/outbound/bulk_services/outbound.go

// Package mock_outbound is a generated GoMock package.
package mock_outbound

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	action "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/domain/action"
)

// MockOutboundInfra is a mock of OutboundInfra interface.
type MockOutboundInfra struct {
	ctrl     *gomock.Controller
	recorder *MockOutboundInfraMockRecorder
}

// MockOutboundInfraMockRecorder is the mock recorder for MockOutboundInfra.
type MockOutboundInfraMockRecorder struct {
	mock *MockOutboundInfra
}

// NewMockOutboundInfra creates a new mock instance.
func NewMockOutboundInfra(ctrl *gomock.Controller) *MockOutboundInfra {
	mock := &MockOutboundInfra{ctrl: ctrl}
	mock.recorder = &MockOutboundInfraMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboundInfra) EXPECT() *MockOutboundInfraMockRecorder {
	return m.recorder
}

// CreateCpsAction mocks base method.
func (m *MockOutboundInfra) CreateCpsAction(ctx context.Context, Action action.CPSAction) (action.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCpsAction", ctx, Action)
	ret0, _ := ret[0].(action.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCpsAction indicates an expected call of CreateCpsAction.
func (mr *MockOutboundInfraMockRecorder) CreateCpsAction(ctx, Action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCpsAction", reflect.TypeOf((*MockOutboundInfra)(nil).CreateCpsAction), ctx, Action)
}

// FetchAccountsByAccountNumber mocks base method.
func (m *MockOutboundInfra) FetchAccountsByAccountNumber(ctx context.Context, accountNumber string) ([]action.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAccountsByAccountNumber", ctx, accountNumber)
	ret0, _ := ret[0].([]action.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAccountsByAccountNumber indicates an expected call of FetchAccountsByAccountNumber.
func (mr *MockOutboundInfraMockRecorder) FetchAccountsByAccountNumber(ctx, accountNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAccountsByAccountNumber", reflect.TypeOf((*MockOutboundInfra)(nil).FetchAccountsByAccountNumber), ctx, accountNumber)
}

// FetchCpsActionById mocks base method.
func (m *MockOutboundInfra) FetchCpsActionById(ctx context.Context, Action_Id string) (action.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCpsActionById", ctx, Action_Id)
	ret0, _ := ret[0].(action.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCpsActionById indicates an expected call of FetchCpsActionById.
func (mr *MockOutboundInfraMockRecorder) FetchCpsActionById(ctx, Action_Id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCpsActionById", reflect.TypeOf((*MockOutboundInfra)(nil).FetchCpsActionById), ctx, Action_Id)
}

// FetchLastCpsActionByMakerID mocks base method.
func (m *MockOutboundInfra) FetchLastCpsActionByMakerID(ctx context.Context, makerId string) (action.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchLastCpsActionByMakerID", ctx, makerId)
	ret0, _ := ret[0].(action.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchLastCpsActionByMakerID indicates an expected call of FetchLastCpsActionByMakerID.
func (mr *MockOutboundInfraMockRecorder) FetchLastCpsActionByMakerID(ctx, makerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchLastCpsActionByMakerID", reflect.TypeOf((*MockOutboundInfra)(nil).FetchLastCpsActionByMakerID), ctx, makerId)
}

// FetchLinkedAccountById mocks base method.
func (m *MockOutboundInfra) FetchLinkedAccountById(ctx context.Context, id []string) ([]action.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchLinkedAccountById", ctx, id)
	ret0, _ := ret[0].([]action.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchLinkedAccountById indicates an expected call of FetchLinkedAccountById.
func (mr *MockOutboundInfraMockRecorder) FetchLinkedAccountById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchLinkedAccountById", reflect.TypeOf((*MockOutboundInfra)(nil).FetchLinkedAccountById), ctx, id)
}

// GetAllHqServices mocks base method.
func (m *MockOutboundInfra) GetAllHqServices(ctx context.Context) ([]action.ServiceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHqServices", ctx)
	ret0, _ := ret[0].([]action.ServiceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllHqServices indicates an expected call of GetAllHqServices.
func (mr *MockOutboundInfraMockRecorder) GetAllHqServices(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHqServices", reflect.TypeOf((*MockOutboundInfra)(nil).GetAllHqServices), ctx)
}

// GetAllHqServicesPaginated mocks base method.
func (m *MockOutboundInfra) GetAllHqServicesPaginated(ctx context.Context, offset, limit int) ([]action.ServiceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHqServicesPaginated", ctx, offset, limit)
	ret0, _ := ret[0].([]action.ServiceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllHqServicesPaginated indicates an expected call of GetAllHqServicesPaginated.
func (mr *MockOutboundInfraMockRecorder) GetAllHqServicesPaginated(ctx, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHqServicesPaginated", reflect.TypeOf((*MockOutboundInfra)(nil).GetAllHqServicesPaginated), ctx, offset, limit)
}

// GetHqServiceById mocks base method.
func (m *MockOutboundInfra) GetHqServiceById(ctx context.Context, id string) (action.ServiceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHqServiceById", ctx, id)
	ret0, _ := ret[0].(action.ServiceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHqServiceById indicates an expected call of GetHqServiceById.
func (mr *MockOutboundInfraMockRecorder) GetHqServiceById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHqServiceById", reflect.TypeOf((*MockOutboundInfra)(nil).GetHqServiceById), ctx, id)
}

// UpdateAccount mocks base method.
func (m *MockOutboundInfra) UpdateAccount(ctx context.Context, linkedAccount action.LinkedAccount) (action.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, linkedAccount)
	ret0, _ := ret[0].(action.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockOutboundInfraMockRecorder) UpdateAccount(ctx, linkedAccount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockOutboundInfra)(nil).UpdateAccount), ctx, linkedAccount)
}

// UpdateAccounts mocks base method.
func (m *MockOutboundInfra) UpdateAccounts(ctx context.Context, linkedAccounts []action.LinkedAccount) ([]action.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccounts", ctx, linkedAccounts)
	ret0, _ := ret[0].([]action.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccounts indicates an expected call of UpdateAccounts.
func (mr *MockOutboundInfraMockRecorder) UpdateAccounts(ctx, linkedAccounts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccounts", reflect.TypeOf((*MockOutboundInfra)(nil).UpdateAccounts), ctx, linkedAccounts)
}

// UpdateCpsAction mocks base method.
func (m *MockOutboundInfra) UpdateCpsAction(ctx context.Context, Action action.CPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCpsAction", ctx, Action)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCpsAction indicates an expected call of UpdateCpsAction.
func (mr *MockOutboundInfraMockRecorder) UpdateCpsAction(ctx, Action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCpsAction", reflect.TypeOf((*MockOutboundInfra)(nil).UpdateCpsAction), ctx, Action)
}

// UpdateHqService mocks base method.
func (m *MockOutboundInfra) UpdateHqService(ctx context.Context, service action.ServiceDetails) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHqService", ctx, service)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHqService indicates an expected call of UpdateHqService.
func (mr *MockOutboundInfraMockRecorder) UpdateHqService(ctx, service interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHqService", reflect.TypeOf((*MockOutboundInfra)(nil).UpdateHqService), ctx, service)
}
