-- Amount based auth tiers (Oracle)
CREATE TABLE AMOUNT_BASED_AUTH_TIERS (
    ID RAW(16) DEFAULT SYS_GUID() NOT NULL,
    CURRENCY VARCHAR2(16) NOT NULL,
    MIN_AMOUNT NUMBER(20,0) NOT NULL,
    MAX_AMOUNT NUMBER(20,0) NOT NULL,
    METHOD VARCHAR2(32) NOT NULL,
    ENABLED NUMBER(1,0) DEFAULT 1 NOT NULL,
    IS_DELETED NUMBER(1,0) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_AMOUNT_BASED_AUTH_TIERS PRIMARY KEY (ID)
);

CREATE INDEX IX_AmountAuth_Currency ON AMOUNT_BASED_AUTH_TIERS (CURRENCY);
CREATE INDEX IX_AmountAuth_Method   ON AMOUNT_BASED_AUTH_TIERS (METHOD);

-- Unique active tier per (currency, method)
CREATE UNIQUE INDEX UX_AmountAuth_Active_Unique
ON AMOUNT_BASED_AUTH_TIERS (
    CASE
        WHEN IS_DELETED = 0 THEN UPPER(CURRENCY) || '|' || UPPER(METHOD)
        ELSE NULL
    END
);

