-- Budget categories (Oracle): replaces MongoDB collection budget_category
CREATE TABLE BUDGET_CATEGORIES (
    ID RAW(16) DEFAULT SYS_GUID() NOT NULL,
    NAME VARCHAR2(128) NOT NULL,
    COLOR VARCHAR2(32),
    ICON VARCHAR2(512),
    TYPE VARCHAR2(16) NOT NULL,
    ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_BUDGET_CATEGORIES PRIMARY KEY (ID)
);

CREATE INDEX IX_BUDGET_CATEGORIES_NAME ON BUDGET_CATEGORIES (UPPER(NAME));
