CREATE TABLE banks (
    id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    bank_name VARCHAR2(32) NOT NULL,
    logo VARCHAR2(255) NOT NULL,
    bic_code VARCHAR2(16) NOT NULL,
    is_cbe NUMBER(1) DEFAULT 0,
    is_enabled NUMBER(1) DEFAULT 1,
    account_length NUMBER NOT NULL,
    has_alpha_numeric NUMBER(1) DEFAULT 0,
    create_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    update_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE ACCOUNT_BLOCKS (
    ID RAW(24) PRIMARY KEY,
    NAME VARCHAR2(255),
    CODE VARCHAR2(100) UNIQUE,
    ADDRESS VARCHAR2(500),
    PARENT_ID RAW(24),
    SLUG VARCHAR2(255),
    TYPE VARCHAR2(1), -- R, D, C, B
    IS_ENABLED NUMBER(1) DEFAULT 1,
    CITY_ID RAW(24),
    REGION_ID RAW(24),
    DISTRICT_ID RAW(24),
    IS_DELETED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT FK_ACCOUNT_BLOCK_PARENT FOREIGN KEY (CITY_ID) REFERENCES ACCOUNT_BLOCKS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_ACCOUNT_BLOCK_REGION FOREIGN KEY (REGION_ID) REFERENCES ACCOUNT_BLOCKS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_ACCOUNT_BLOCK_DISTRICT FOREIGN KEY (DISTRICT_ID) REFERENCES ACCOUNT_BLOCKS (ID) ON DELETE CASCADE
);

ALTER TABLE ACCOUNT_BLOCKS
ADD CONSTRAINT CHK_AB_TYPE CHECK (TYPE IN ('R', 'D', 'C', 'B'));

CREATE TABLE ACCESS_ITEMS_RELATION (
    ID RAW(16) DEFAULT SYS_GUID() NOT NULL,
    PARENT_KEY VARCHAR2(128) NOT NULL,
    CHILD_KEY VARCHAR2(128) NOT NULL,
    CONSTRAINT PK_ACCESS_ITEMS_RELATION PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UX_ACCESS_ITEMS_RELATION_PAIR ON ACCESS_ITEMS_RELATION (
    UPPER(PARENT_KEY),
    UPPER(CHILD_KEY)
);

CREATE INDEX IX_ACCESS_ITEMS_RELATION_PARENT ON ACCESS_ITEMS_RELATION (UPPER(PARENT_KEY));

CREATE INDEX IX_ACCESS_ITEMS_RELATION_CHILD ON ACCESS_ITEMS_RELATION (UPPER(CHILD_KEY));