-- Parent/child edges for bulk_service tree (replaces Mongo access_items_relation aggregation)
CREATE TABLE ACCESS_ITEMS_RELATION (
    ID RAW(16) DEFAULT SYS_GUID() NOT NULL,
    PARENT_KEY VARCHAR2(128) NOT NULL,
    CHILD_KEY  VARCHAR2(128) NOT NULL,
    CONSTRAINT PK_ACCESS_ITEMS_RELATION PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UX_ACCESS_ITEMS_RELATION_PAIR
ON ACCESS_ITEMS_RELATION (UPPER(PARENT_KEY), UPPER(CHILD_KEY));

CREATE INDEX IX_ACCESS_ITEMS_RELATION_PARENT ON ACCESS_ITEMS_RELATION (UPPER(PARENT_KEY));
CREATE INDEX IX_ACCESS_ITEMS_RELATION_CHILD ON ACCESS_ITEMS_RELATION (UPPER(CHILD_KEY));
