CREATE TABLE ACCOUNT_BLOCKS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    NAME VARCHAR2(255),
    CODE VARCHAR2(255) UNIQUE,
    ADDRESS VARCHAR2(500),
    SLUG VARCHAR2(255),
    COMPANY_CODE VARCHAR2(128),
    TYPE VARCHAR2(1),
    REGION_ID RAW(16),
    DISTRICT_ID RAW(16),
    IS_ENABLED NUMBER(1) DEFAULT 1,
    IS_DELETED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHK_ACCOUNT_BLOCKS_TYPE CHECK (TYPE IN ('R', 'D', 'B')),
    CONSTRAINT CHK_ACCOUNT_BLOCKS_IS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHK_ACCOUNT_BLOCKS_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT FK_ACCOUNT_BLOCKS_REGION FOREIGN KEY (REGION_ID) REFERENCES ACCOUNT_BLOCKS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_ACCOUNT_BLOCKS_DISTRICT FOREIGN KEY (DISTRICT_ID) REFERENCES ACCOUNT_BLOCKS (ID) ON DELETE CASCADE
);

CREATE INDEX IDX_ACCOUNT_BLOCKS_REGION_ID ON ACCOUNT_BLOCKS(REGION_ID);
CREATE INDEX IDX_ACCOUNT_BLOCKS_DISTRICT_ID ON ACCOUNT_BLOCKS(DISTRICT_ID);

CREATE TABLE ACCOUNT_BLOCKS_DISABLED_REASONS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ACCOUNT_BLOCK_ID RAW(16) NOT NULL,
    REASON_TEXT VARCHAR2(512),
    CREATED_BY VARCHAR2(128),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_ACCOUNT_BLOCKS_DISABLED_REASONS_ACCOUNT_BLOCK_ID FOREIGN KEY (ACCOUNT_BLOCK_ID) REFERENCES ACCOUNT_BLOCKS (ID) ON DELETE CASCADE
);

CREATE INDEX IDX_ACCOUNT_BLOCKS_DISABLED_REASONS_ACCOUNT_BLOCK_ID ON ACCOUNT_BLOCKS_DISABLED_REASONS(ACCOUNT_BLOCK_ID);