CREATE TABLE COMPANY (
    ID                RAW(16) DEFAULT SYS_GUID() NOT NULL,
    BRANCH_NAME       VARCHAR2(255) NOT NULL,
    BRANCH_CODE       VARCHAR2(50) NOT NULL,
    REGION_NAME       VARCHAR2(16),
    REGION_CODE       VARCHAR2(50) NOT NULL,
    DISTRICT_NAME     VARCHAR2(16),
    DISTRICT_CODE     VARCHAR2(50) NOT NULL,
    BRANCH_TYPE       VARCHAR2(8) NOT NULL,
    IS_ENABLED        NUMBER(1) DEFAULT 1 NOT NULL CHECK (IS_ENABLED IN (0, 1)),
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_COMPANY PRIMARY KEY (ID),
    CONSTRAINT CK_COMPANY_BRANCH_TYPE CHECK (BRANCH_TYPE IN ('BOTH', 'CB', 'IFB')),
    CONSTRAINT UK_COMPANY_LOCATION UNIQUE (REGION_CODE, DISTRICT_CODE, BRANCH_CODE)
);
 