CREATE TABLE COMPANY (
    ID                  RAW(16)      DEFAULT SYS_GUID() NOT NULL,
    BRANCH_CODE         VARCHAR2(20) NOT NULL,
    BRANCH_NAME         VARCHAR2(128) NOT NULL,
    DISTRICT_NAME       VARCHAR2(64),
    REGION_NAME         VARCHAR2(32),
    FEDERAL_REGION_NAME VARCHAR2(64),
    DAO_CODE            NUMBER(10)   NOT NULL,
    ACCOUNT_TYPE        VARCHAR2(20) NOT NULL,
    IS_ENABLED          NUMBER(1)    DEFAULT 1 NOT NULL,
    CREATED_AT          TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_AT    TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_COMPANY PRIMARY KEY (ID),
    CONSTRAINT UQ_COMPANY_BRANCH_CODE UNIQUE (BRANCH_CODE),
    CONSTRAINT UQ_COMPANY_DAO_CODE UNIQUE (DAO_CODE),
    CONSTRAINT CHK_COMPANY_IS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHK_COMPANY_ACCOUNT_TYPE CHECK (ACCOUNT_TYPE IN ('CONVENTIONAL', 'CBENOOR'))
);

CREATE TABLE COMPANY_BLOCK_REASON (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ENTITY_TYPE CHAR(1) NOT NULL,
    ENTITY_ID VARCHAR2(255) NOT NULL,
    REASON VARCHAR2(1000),
    CREATED_BY VARCHAR2(128),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT CHK_COMPANY_BLOCK_REASON_ENTITY_TYPE
        CHECK (ENTITY_TYPE IN ('R', 'D', 'B'))
);