CREATE TABLE ACCESS_LISTS (
    ID RAW (16) DEFAULT SYS_GUID () PRIMARY KEY,
    NAME VARCHAR2 (64) NOT NULL,
    SERVICE_KEY VARCHAR2 (32) NOT NULL,
    IS_ENABLED NUMBER (1) DEFAULT 1,
    IS_DELETED NUMBER (1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHECK_ACCESS_LISTS_IS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHECK_ACCESS_LISTS_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE TABLE SERVICES (
    ID RAW (16) DEFAULT SYS_GUID () PRIMARY KEY,
    ACCESS_LIST_ID RAW (16) UNIQUE NOT NULL,
    SERVICE_CODE VARCHAR2 (64) NOT NULL UNIQUE,
    MINIMUM_FRAUD_AMOUNT NUMBER (19, 4) NOT NULL,
    PRODUCT_GL_ACCOUNT VARCHAR2 (16) NOT NULL,
    PRODUCT_GL_ACCOUNT_CURRENCY VARCHAR2 (3) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    IS_DELETED NUMBER (1) DEFAULT 0,
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_SERVICES_ACCESS_LIST_ID FOREIGN KEY (ACCESS_LIST_ID) REFERENCES ACCESS_LISTS (ID),
    CONSTRAINT CHECK_SERVICES_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE TABLE SERVICE_CAP (
    ID RAW (16) DEFAULT SYS_GUID () PRIMARY KEY,
    SERVICE_ID RAW (16) NOT NULL,
    SOURCE VARCHAR2 (16) NOT NULL,
    CURRENCY VARCHAR2 (3) NOT NULL,
    SINGLE_CAP NUMBER (19, 4) NOT NULL,
    MINIMUM_TRANSFER_CAP NUMBER (19, 4) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    IS_DELETED NUMBER (1) DEFAULT 0,
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_SERVICE_CAPS_SERVICE_ID FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES (ID),
    CONSTRAINT CHECK_SERVICE_CAPS_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CHECK_SERVICE_CAPS_SOURCE CHECK (
        SOURCE IN (
            'app',
            'ussd',
            'internet_banking'
        )
    )
);