-- ACCESS_LIST (Oracle); aligns with internal/constants/model.AccessListOracle
CREATE TABLE ACCESS_LIST (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    SERVICE_KEY VARCHAR2(32) NOT NULL,
    IS_ENABLED NUMBER(1) DEFAULT 1,
    IS_DELETED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);
