CREATE TABLE CUSTOMER_GROUPS (
    ID            RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    NAME          VARCHAR2(32) NOT NULL,
    IS_ENABLED       NUMBER(1) DEFAULT 1,
    IS_DELETED NUMBER (1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHECK_CUSTOMER_GROUPS_IS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHECK_CUSTOMER_GROUPS_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE TABLE SUPERAPP_ROLE (
    ID RAW (16) DEFAULT SYS_GUID () PRIMARY KEY,
    NAME VARCHAR2 (32) NOT NULL,
    ROLE_CODE VARCHAR2 (32) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2 (128),
    IS_ENABLED NUMBER (1) DEFAULT 1,
    IS_DELETED NUMBER (1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHECK_SUPERAPP_ROLE_IS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHECK_SUPERAPP_ROLE_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE TABLE CUSTOMER_SEGMENTATIONS (
    ID RAW (16) DEFAULT SYS_GUID () PRIMARY KEY,
    NAME VARCHAR2 (32) NOT NULL,
    CUSTOMER_GROUP_ID RAW (16) NOT NULL,
    IS_ENABLED NUMBER (1) DEFAULT 1,
    IS_DELETED NUMBER (1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHECK_CUSTOMER_SEGMENTATIONS_IS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHECK_CUSTOMER_SEGMENTATIONS_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT FK_CUSTOMER_SEGMENTATIONS_CUSTOMER_GROUP_ID FOREIGN KEY (CUSTOMER_GROUP_ID) REFERENCES CUSTOMER_GROUPS (ID)
);

CREATE TABLE CUSTOMER_SUB_SEGMENTS (
    ID RAW (16) DEFAULT SYS_GUID () PRIMARY KEY,
    NAME VARCHAR2 (32) NOT NULL,
    CUSTOMER_SEGMENTATION_ID RAW (16) NOT NULL,
    SUPERAPP_ROLE_ID RAW (16) NOT NULL,
    IS_ENABLED NUMBER (1) DEFAULT 1,
    IS_DELETED NUMBER (1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHECK_CUSTOMER_SUB_SEGMENTS_IS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHECK_CUSTOMER_SUB_SEGMENTS_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT FK_CUSTOMER_SUB_SEGMENTS_CUSTOMER_SEGMENTATION_ID FOREIGN KEY (CUSTOMER_SEGMENTATION_ID) REFERENCES CUSTOMER_SEGMENTATIONS (ID),
    CONSTRAINT FK_CUSTOMER_SUB_SEGMENTS_SUPERAPP_ROLE_ID FOREIGN KEY (SUPERAPP_ROLE_ID) REFERENCES SUPERAPP_ROLE (ID)
);