CREATE TABLE SERVICE_KEYS(
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    SERVICE_NAME VARCHAR(64) NOT NULL,
    SERVICE_KEY VARCHAR2(32) NOT NULL,
    IS_ENABLED NUMBER(1) DEFAULT 1,
    IS_DELETED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);

CREATE TABLE SERVICES(
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    SERVICE_KEY_ID RAW(16) UNIQUE NOT NULL,
    SERVICE_CODE VARCHAR(64) NOT NULL UNIQUE,
    MINIMUM_FRAUD_AMOUNT NUMBER(19, 4) NOT NULL,
    PRODUCT_GL_ACCOUNT VARCHAR(16) NOT NULL,
    PRODUCT_GL_ACCOUNT_CURRENCY VARCHAR(3) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SERVICE_KEY 
    FOREIGN KEY (SERVICE_KEY_ID) 
    REFERENCES SERVICE_KEYS(ID)
);

CREATE TABLE SERVICE_CAP(
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    SERVICE_ID RAW(16) NOT NULL,
    SOURCE VARCHAR(8) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    SINGLE_CAP NUMBER(10, 2) NOT NULL,
    MINIMUM_TRANSFER_CAP NUMBER(10, 2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SERVICE
    FOREIGN KEY (SERVICE_ID)
    REFERENCES SERVICES(ID)
);
