CREATE TABLE CUSTOMER_SEGMENTATIONS (
    ID            RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ROLE_NAME     VARCHAR2(255),
    IS_ENABLED    NUMBER(1) DEFAULT 1,
    IS_DELETED    NUMBER(1) DEFAULT 0,
    CREATED_AT    TIMESTAMP,
    UPDATED_AT    TIMESTAMP
);

CREATE TABLE CUSTOMER_SUB_SEGMENTS (
    ID                RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    CUSTOMER_SEG_ID   RAW(16),
    NAME              VARCHAR2(255),
    CUSTOMER_GROUP    VARCHAR2(100),
    CUSTOMER_SEGMENT  VARCHAR2(100),

    CONSTRAINT FK_CUSTOMER_SUB_SEG
        FOREIGN KEY (CUSTOMER_SEG_ID)
        REFERENCES CUSTOMER_SEGMENTATIONS(ID)
        ON DELETE CASCADE
);