
CREATE TABLE ACCESS_LIST_CUSTOMER_SEG (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ACCESS_LIST_KEY RAW(16),
    SEGMENTED_ID RAW(16), -- CUSTOMER_SEGMENTATIONS.ID
    ENABLED NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_AL_CUSTOMER_ACCESS_LIST FOREIGN KEY (ACCESS_LIST_KEY) REFERENCES ACCESS_LIST (id) ON DELETE CASCADE,
    CONSTRAINT FK_AL_CUSTOMER_SEGMENT FOREIGN KEY (SEGMENTED_ID) REFERENCES CUSTOMER_SEGMENTATIONS (ID) ON DELETE CASCADE
);
