CREATE TABLE ACCESS_LISTS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    NAME VARCHAR2(64) NOT NULL,
    SERVICE_KEY VARCHAR2(32) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(4) default 'BOTH',
    IS_ENABLED NUMBER(1) DEFAULT 1,
    IS_DELETED NUMBER(1) DEFAULT 0,
    IS_USSD_ENABLED NUMBER(1) DEFAULT 1,
    IS_SUPERAPP_ENABLED NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHK_ACCESS_LISTS_IS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHK_ACCESS_LISTS_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CHK_ACCESS_LISTS_IS_USSD_ENABLED CHECK (IS_USSD_ENABLED IN (0, 1)),
    CONSTRAINT CHK_ACCESS_LISTS_IS_SUPERAPP_ENABLED CHECK (IS_SUPERAPP_ENABLED IN (0, 1))
);


CREATE TABLE SERVICES (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ACCESS_LIST_ID RAW(16) UNIQUE NOT NULL,
    SERVICE_CODE VARCHAR2(64) NOT NULL,
    MINIMUM_FRAUD_AMOUNT NUMBER(19, 4) NOT NULL,
    IS_PL_ACCOUNT NUMBER(1) DEFAULT 0 NOT NULL,
    PRODUCT_GL_ACCOUNT_NUMBER VARCHAR2(16), 
    PRODUCT_GL_ACCOUNT_CURRENCY VARCHAR2(3),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    IS_DELETED NUMBER(1) DEFAULT 0,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHK_SERVICES_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CHK_SERVICES_IS_PL_ACCOUNT CHECK (IS_PL_ACCOUNT IN (0, 1)),
    CONSTRAINT FK_SERVICES_ACCESS_LIST_ID FOREIGN KEY (ACCESS_LIST_ID) REFERENCES ACCESS_LISTS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_SERVICES_PRODUCT_GL_ACCOUNT_NUMBER FOREIGN KEY (PRODUCT_GL_ACCOUNT_NUMBER) REFERENCES ACCOUNTS (ACCOUNT_NUMBER) ON DELETE CASCADE,
    CONSTRAINT CHK_SERVICES_PRODUCT_GL_ACCOUNT_CURRENCY CHECK (
        PRODUCT_GL_ACCOUNT_CURRENCY IN ('ETB', 'USD', 'GBP', 'EUR')
    )
);
CREATE INDEX IDX_SERVICES_ACCESS_LIST_ID ON SERVICES(ACCESS_LIST_ID);

CREATE TABLE SERVICE_CAP (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    SERVICE_ID RAW(16) NOT NULL,
    SOURCE VARCHAR2(16) NOT NULL,
    CURRENCY VARCHAR2(3) NOT NULL,
    SINGLE_CAP NUMBER(19, 4) NOT NULL,
    MINIMUM_TRANSFER_CAP NUMBER(19, 4) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    IS_DELETED NUMBER(1) DEFAULT 0,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHK_SERVICE_CAP_CURRENCY CHECK (
        CURRENCY IN ('ETB', 'USD', 'GBP', 'EUR')
    ),
    CONSTRAINT CHK_SERVICE_CAP_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CHK_SERVICE_CAP_SOURCE CHECK (
        SOURCE IN (
            'APP',
            'USSD',
            'INTERNET_BANKING',
            'ATM'
        )
    ),
    CONSTRAINT FK_SERVICE_CAP_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES (ID) ON DELETE CASCADE
);
CREATE INDEX IDX_SERVICE_CAP_SERVICE_ID ON SERVICE_CAP(SERVICE_ID);