CREATE TABLE ACCESS_LIST_GEO_SEG (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ACCESS_LIST_KEY RAW(16),
    SEGMENTED_ID VARCHAR2(32), -- ACCOUNT_BLOCKS.ID
    TYPE VARCHAR2(1), -- B, D, R, C
    ENABLED NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_AL_GEO_ACCESS_LIST FOREIGN KEY (ACCESS_LIST_KEY) REFERENCES ACCESS_LIST (ID) ON DELETE CASCADE,
    CONSTRAINT FK_AL_GEO_BLOCK FOREIGN KEY (SEGMENTED_ID) REFERENCES ACCOUNT_BLOCKS (ID) ON DELETE CASCADE
);