
CREATE TABLE CUSTOMER_GROUPS (
    ID            RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    NAME          VARCHAR2(32) NOT NULL,
    IS_ENABLED       NUMBER(1) DEFAULT 1,
    IS_DELETED    NUMBER(1) DEFAULT 0,
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT    TIMESTAMP
);

CREATE TABLE SUPERAPP_ROLE (
    ID RAW (16) DEFAULT SYS_GUID () PRIMARY KEY,
    NAME VARCHAR2 (32) NOT NULL,
    ROLE_CODE VARCHAR2 (32) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2 (128),
    ENABLED NUMBER (1) DEFAULT 1,
    IS_DELETED NUMBER (1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);

CREATE TABLE CUSTOMER_SEGMENTATIONS (
    ID RAW (16) DEFAULT SYS_GUID () PRIMARY KEY,
    NAME VARCHAR2 (32) NOT NULL,
    CUSTOMER_GROUPS_ID RAW (16) NOT NULL,
    IS_ENABLED NUMBER (1) DEFAULT 1,
    IS_DELETED NUMBER (1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_CUSTOMER_GROUPS FOREIGN KEY (CUSTOMER_GROUPS_ID) REFERENCES CUSTOMER_GROUPS (ID) ON DELETE CASCADE
);

CREATE TABLE CUSTOMER_SUB_SEGMENTS (
    ID RAW (16) DEFAULT SYS_GUID () PRIMARY KEY,
    NAME VARCHAR2 (32) NOT NULL,
    CUSTOMER_SEGMENTATIONS_ID RAW (16) NOT NULL,
    SUPERAPP_ROLE_ID RAW (16) NOT NULL,
    IS_ENABLED NUMBER (1) DEFAULT 1,
    IS_DELETED NUMBER (1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_CUSTOMER_SEGMENTATIONS FOREIGN KEY (CUSTOMER_SEGMENTATIONS_ID) REFERENCES CUSTOMER_SEGMENTATIONS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_SUB_SEG_SUPERAPP_ROLE FOREIGN KEY (SUPERAPP_ROLE_ID) REFERENCES SUPERAPP_ROLE (ID)
);
