CREATE TABLE MERCHANT_BRANCHES (
  ID                     RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  MERCHANT_ID            RAW(16) NOT NULL,
  BRANCH_CODE            VARCHAR2(32)  NOT NULL,
  BRANCH_NAME            VARCHAR2(128) NOT NULL,
  BRANCH_ADDRESS         VARCHAR2(256),
  BRANCH_OWNER           VARCHAR2(128),
  BRANCH_ACCOUNT_NUMBER  VARCHAR2(64),
  IS_ENABLED             NUMBER(1)  DEFAULT 1,
  IS_DELETED             NUMBER(1)  DEFAULT 0,
  CREATED_AT             TIMESTAMP  DEFAULT SYSTIMESTAMP,
  LAST_MODIFIED_AT       TIMESTAMP  DEFAULT SYSTIMESTAMP,
  DELETED_AT             TIMESTAMP,

  CONSTRAINT UQ_MERCHANT_BRANCHES_CODE    UNIQUE (MERCHANT_ID, BRANCH_CODE),
  CONSTRAINT CHK_MERCHANT_BRANCHES_ENABLED  CHECK (IS_ENABLED  IN (0, 1)),
  CONSTRAINT CHK_MERCHANT_BRANCHES_DELETED  CHECK (IS_DELETED  IN (0, 1)),
  CONSTRAINT FK_MERCHANT_BRANCHES_MERCHANT
      FOREIGN KEY (MERCHANT_ID) REFERENCES MERCHANTS (ID)
);

CREATE TABLE MERCHANTS(
  ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  ACCOUNT_ID RAW(16),
  BRANCH_ID RAW(16),
  MERCHANT_CODE VARCHAR(32) NOT NULL UNIQUE,
  MERCHANT_NAME VARCHAR(96) NOT NULL,
  SETTLEMENT_METHOD VARCHAR(8) NOT NULL,
  MERCHANT_TYPE VARCHAR(12) NOT NULL,
  CONTACT_EMAIL VARCHAR(128),
  CONTACT_PHONE VARCHAR(12),
  IS_ENABLED NUMBER(1) DEFAULT 1,
  IS_DELETED NUMBER(1) DEFAULT 0,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP, 
  LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP, 
  DELETED_AT TIMESTAMP,
  CONSTRAINT CHK_MERCHANTS_IS_ENABLED CHECK(IS_ENABLED IN (0, 1)),
  CONSTRAINT CHK_MERCHANTS_IS_DELETED CHECK(IS_DELETED IN (0, 1)),
  CONSTRAINT FK_MERCHANTS_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID),
  CONSTRAINT FK_MERCHANTS_BRANCH_ID FOREIGN KEY (BRANCH_ID) REFERENCES ACCOUNT_BLOCKS(ID),
  CONSTRAINT CHK_MERCHANTS_TYPE CHECK(MERCHANT_TYPE IN ('MINI_APP', 'ECOMMERCE', 'EVENT')),
  CONSTRAINT CHK_MERCHANTS_SETTLEMENT_METHOD CHECK(SETTLEMENT_METHOD IN ('GL', 'DIRECT'))
);