DROP TABLE MERCHANTS CASCADE CONSTRAINTS;
DROP TABLE MERCHANT_BRANCHES CASCADE CONSTRAINTS;

CREATE TABLE MERCHANTS(
  ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  MERCHANT_ACCOUNT_NUMBER VARCHAR2(16),
  MERCHANT_CODE VARCHAR(32) NOT NULL UNIQUE,
  MERCHANT_NAME VARCHAR(96) NOT NULL,
  SETTLEMENT_METHOD VARCHAR(13) NOT NULL,
  MERCHANT_TYPE VARCHAR(12) NOT NULL,
  CONTACT_EMAIL VARCHAR(128),
  CONTACT_PHONE VARCHAR(12),
  IS_ENABLED NUMBER(1) DEFAULT 1,
  IS_DELETED NUMBER(1) DEFAULT 0,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP, 
  LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP, 
  DELETED_AT TIMESTAMP,
  CONSTRAINT CHK_MERCHANTS_IS_ENABLED CHECK(IS_ENABLED IN (0, 1)),
  CONSTRAINT CHK_MERCHANTS_IS_DELETED CHECK(IS_DELETED IN (0, 1)),
  CONSTRAINT CHK_MERCHANTS_TYPE CHECK(MERCHANT_TYPE IN ('MINI_APP', 'ECOMMERCE', 'EVENT', 'LOGISTICS', 'USSD_PUSH')),
  CONSTRAINT CHK_MERCHANTS_SETTLEMENT_METHOD CHECK(SETTLEMENT_METHOD IN ('GL', 'DIRECT', 'MULTI_ACCOUNT'))
);

CREATE TABLE USSD_MERCHANT_SERVICE(
  ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  MERCHANT_ID RAW(16) NOT NULL,
  SERVICE_ID RAW(16),
  LOGO VARCHAR2(512),
  CREDENTIAL VARCHAR2(256),
  IS_DELETED NUMBER(1) DEFAULT 0,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
  LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
  DELETED_AT TIMESTAMP,
  CONSTRAINT CHK_USSD_MERCHANTS_IS_DELETED CHECK(IS_DELETED IN (0, 1)),
  CONSTRAINT FK_USSD_MERCHANTS_MERCHANT_ID FOREIGN KEY (MERCHANT_ID) REFERENCES MERCHANTS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_USSD_MERCHANTS_SERVICE_ID FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES (ID)
);

CREATE TABLE MERCHANT_BRANCHES (
  ID                     RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  MERCHANT_ID            RAW(16) NOT NULL,
  BRANCH_CODE            VARCHAR2(32)  NOT NULL,
  BRANCH_NAME            VARCHAR2(128) NOT NULL,
  BRANCH_ADDRESS         VARCHAR2(256),
  BRANCH_OWNER           VARCHAR2(128),
  BRANCH_ACCOUNT_NUMBER  VARCHAR2(16),
  IS_ENABLED             NUMBER(1)  DEFAULT 1,
  IS_DELETED             NUMBER(1)  DEFAULT 0,
  CREATED_AT             TIMESTAMP  DEFAULT SYSTIMESTAMP,
  LAST_MODIFIED_AT       TIMESTAMP  DEFAULT SYSTIMESTAMP,
  DELETED_AT             TIMESTAMP,
  CONSTRAINT UQ_MERCHANT_BRANCHES    UNIQUE (MERCHANT_ID, BRANCH_CODE),
  CONSTRAINT CHK_MERCHANT_BRANCHES_IS_ENABLED  CHECK (IS_ENABLED  IN (0, 1)),
  CONSTRAINT CHK_MERCHANT_BRANCHES_IS_DELETED  CHECK (IS_DELETED  IN (0, 1)),
  CONSTRAINT FK_MERCHANT_BRANCHES_MERCHANT_ID FOREIGN KEY (MERCHANT_ID) REFERENCES MERCHANTS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_MERCHANT_BRANCHES_BRANCH_ACCOUNT_NUMBER FOREIGN KEY (BRANCH_ACCOUNT_NUMBER) REFERENCES ACCOUNTS (ACCOUNT_NUMBER)
);
