CREATE TABLE USERS (
    ID                      RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    USER_CODE               VARCHAR2(32) NOT NULL UNIQUE,
    USERNAME                VARCHAR2(32) UNIQUE,
    BRANCH_CODE             VARCHAR2(255) NOT NULL,
    CONTACT_EMAIL           VARCHAR2(255),
    CONTACT_PHONE           VARCHAR2(32) NOT NULL UNIQUE,
    CUSTOMER_NUMBER         VARCHAR2(32) NOT NULL UNIQUE,
    FIRST_NAME              VARCHAR2(32),
    LAST_NAME               VARCHAR2(32),
    MIDDLE_NAME             VARCHAR2(32),
    FULL_NAME               VARCHAR2(96),
    GENDER                  VARCHAR2(6) NOT NULL,
    BIRTH_OF_DATE           DATE,
    AVATAR                  VARCHAR2(255),
    SECTOR                  VARCHAR2(64),
    OWNERSHIP               VARCHAR2(64),
    PUSH_TOKEN              VARCHAR2(255),
    INDUSTRY                VARCHAR2(64),
    LANGUAGE                VARCHAR2(3) DEFAULT 'EN',
    PIN                     VARCHAR2(255) NOT NULL,
    PIN_HISTORY             CLOB,
    EXCLUDED_ACCESS_LIST    CLOB,
    FAILED_LOGIN_ATTEMPT    NUMBER DEFAULT 0,
    IS_LOCKED               NUMBER(1) DEFAULT 0,
    IS_BUDGET_ENABLED       NUMBER(1) DEFAULT 0,
    IS_SUPERAPP_ACTIVE      NUMBER(1) DEFAULT 0,
    IS_SUPERAPP_ENABLED     NUMBER(1) DEFAULT 0,
    IS_USSD_ACTIVE          NUMBER(1) DEFAULT 0,
    IS_USSD_ENABLED         NUMBER(1) DEFAULT 0,
    IS_BLOCKED              NUMBER(1) DEFAULT 0,
    LOCK_EXPIRES_AT         TIMESTAMP,
    PIN_CREATED_AT          TIMESTAMP,
    CREATED_AT              TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_LOGIN_AT           TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP,
    EXPIRY_AT               TIMESTAMP,
    CUSTOMER_SEGMENTATION   VARCHAR2(64),
    ACCOUNT_TYPE            VARCHAR2(3),
    CUSTOMER_GROUP          VARCHAR2(32),
    CUSTOMER_SUBSEGMENT     VARCHAR2(32),
    SUPERAPP_ROLE           VARCHAR2(32),
    IS_RESET_PIN            NUMBER(1) DEFAULT 0,
    IS_TERMINATED           NUMBER(1) DEFAULT 0,
    TERMINATION_COUNTER     NUMBER(3) DEFAULT 0,
    HAS_CHANGE              VARCHAR2(255),

    CONSTRAINT CHK_USERS_GENDER
        CHECK (GENDER IN ('MALE', 'FEMALE', 'OTHER')),

    CONSTRAINT CHK_USERS_LANGUAGE
        CHECK (LANGUAGE IN ('EN', 'AM', 'AR')),

    CONSTRAINT CHK_USERS_IS_LOCKED
        CHECK (IS_LOCKED IN (0,1)),

    CONSTRAINT CHK_USERS_IS_BLOCKED
        CHECK (IS_BLOCKED IN (0,1)),

    CONSTRAINT CHK_USERS_IS_USSD_ACTIVE
        CHECK (IS_USSD_ACTIVE IN (0,1)),

    CONSTRAINT CHK_USERS_IS_USSD_ENABLED
        CHECK (IS_USSD_ENABLED IN (0,1)),

    CONSTRAINT CHK_USERS_IS_BUDGET_ENABLED
        CHECK (IS_BUDGET_ENABLED IN (0,1)),

    CONSTRAINT CHK_USERS_IS_SUPERAPP_ENABLED
        CHECK (IS_SUPERAPP_ENABLED IN (0,1)),

    CONSTRAINT CHK_USERS_ACCOUNT_TYPE
        CHECK (ACCOUNT_TYPE IN ('CB', 'IFB'))
);