// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/department/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/department/repository.go -destination=internal/domain/department/mock/repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	entities "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/domain/department/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockCPSActionRepository is a mock of CPSActionRepository interface.
type MockCPSActionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCPSActionRepositoryMockRecorder
	isgomock struct{}
}

// MockCPSActionRepositoryMockRecorder is the mock recorder for MockCPSActionRepository.
type MockCPSActionRepositoryMockRecorder struct {
	mock *MockCPSActionRepository
}

// NewMockCPSActionRepository creates a new mock instance.
func NewMockCPSActionRepository(ctrl *gomock.Controller) *MockCPSActionRepository {
	mock := &MockCPSActionRepository{ctrl: ctrl}
	mock.recorder = &MockCPSActionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCPSActionRepository) EXPECT() *MockCPSActionRepositoryMockRecorder {
	return m.recorder
}

// ApproveActionRequest mocks base method.
func (m *MockCPSActionRepository) ApproveActionRequest(actionCode string, action entities.CPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveActionRequest", actionCode, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveActionRequest indicates an expected call of ApproveActionRequest.
func (mr *MockCPSActionRepositoryMockRecorder) ApproveActionRequest(actionCode, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveActionRequest", reflect.TypeOf((*MockCPSActionRepository)(nil).ApproveActionRequest), actionCode, action)
}

// CheckRequestExists mocks base method.
func (m *MockCPSActionRepository) CheckRequestExists(action entities.CPSAction) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRequestExists", action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRequestExists indicates an expected call of CheckRequestExists.
func (mr *MockCPSActionRepositoryMockRecorder) CheckRequestExists(action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRequestExists", reflect.TypeOf((*MockCPSActionRepository)(nil).CheckRequestExists), action)
}

// CreateCPSAction mocks base method.
func (m *MockCPSActionRepository) CreateCPSAction(department string, portalCards []string, action entities.CPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCPSAction", department, portalCards, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCPSAction indicates an expected call of CreateCPSAction.
func (mr *MockCPSActionRepositoryMockRecorder) CreateCPSAction(department, portalCards, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCPSAction", reflect.TypeOf((*MockCPSActionRepository)(nil).CreateCPSAction), department, portalCards, action)
}

// FindByActionCode mocks base method.
func (m *MockCPSActionRepository) FindByActionCode(code string) (*entities.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByActionCode", code)
	ret0, _ := ret[0].(*entities.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByActionCode indicates an expected call of FindByActionCode.
func (mr *MockCPSActionRepositoryMockRecorder) FindByActionCode(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByActionCode", reflect.TypeOf((*MockCPSActionRepository)(nil).FindByActionCode), code)
}

// UpdateActionStatus mocks base method.
func (m *MockCPSActionRepository) UpdateActionStatus(actionCode, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActionStatus", actionCode, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActionStatus indicates an expected call of UpdateActionStatus.
func (mr *MockCPSActionRepositoryMockRecorder) UpdateActionStatus(actionCode, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActionStatus", reflect.TypeOf((*MockCPSActionRepository)(nil).UpdateActionStatus), actionCode, status)
}

// ValidateActionRequest mocks base method.
func (m *MockCPSActionRepository) ValidateActionRequest(actionCode, userDept string) (*entities.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateActionRequest", actionCode, userDept)
	ret0, _ := ret[0].(*entities.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateActionRequest indicates an expected call of ValidateActionRequest.
func (mr *MockCPSActionRepositoryMockRecorder) ValidateActionRequest(actionCode, userDept any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateActionRequest", reflect.TypeOf((*MockCPSActionRepository)(nil).ValidateActionRequest), actionCode, userDept)
}

// MockDepartmentRepository is a mock of DepartmentRepository interface.
type MockDepartmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentRepositoryMockRecorder
	isgomock struct{}
}

// MockDepartmentRepositoryMockRecorder is the mock recorder for MockDepartmentRepository.
type MockDepartmentRepositoryMockRecorder struct {
	mock *MockDepartmentRepository
}

// NewMockDepartmentRepository creates a new mock instance.
func NewMockDepartmentRepository(ctrl *gomock.Controller) *MockDepartmentRepository {
	mock := &MockDepartmentRepository{ctrl: ctrl}
	mock.recorder = &MockDepartmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartmentRepository) EXPECT() *MockDepartmentRepositoryMockRecorder {
	return m.recorder
}

// CheckDepartmentExists mocks base method.
func (m *MockDepartmentRepository) CheckDepartmentExists(department string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDepartmentExists", department)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckDepartmentExists indicates an expected call of CheckDepartmentExists.
func (mr *MockDepartmentRepositoryMockRecorder) CheckDepartmentExists(department any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDepartmentExists", reflect.TypeOf((*MockDepartmentRepository)(nil).CheckDepartmentExists), department)
}

// CreateDepartment mocks base method.
func (m *MockDepartmentRepository) CreateDepartment(dept entities.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDepartment", dept)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDepartment indicates an expected call of CreateDepartment.
func (mr *MockDepartmentRepositoryMockRecorder) CreateDepartment(dept any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDepartment", reflect.TypeOf((*MockDepartmentRepository)(nil).CreateDepartment), dept)
}

// UpdateDepartment mocks base method.
func (m *MockDepartmentRepository) UpdateDepartment(code, department string, portalCards []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDepartment", code, department, portalCards)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDepartment indicates an expected call of UpdateDepartment.
func (mr *MockDepartmentRepositoryMockRecorder) UpdateDepartment(code, department, portalCards any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDepartment", reflect.TypeOf((*MockDepartmentRepository)(nil).UpdateDepartment), code, department, portalCards)
}
