// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/department/repository.go

// Package mock is a generated GoMock package.
package mock

import (
	entities "gitlab.com/bersufekadgetachew/cbe-super-app-cps-action/internal/domain/department/entities"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCPSActionRepository is a mock of CPSActionRepository interface.
type MockCPSActionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCPSActionRepositoryMockRecorder
}

// MockCPSActionRepositoryMockRecorder is the mock recorder for MockCPSActionRepository.
type MockCPSActionRepositoryMockRecorder struct {
	mock *MockCPSActionRepository
}

// NewMockCPSActionRepository creates a new mock instance.
func NewMockCPSActionRepository(ctrl *gomock.Controller) *MockCPSActionRepository {
	mock := &MockCPSActionRepository{ctrl: ctrl}
	mock.recorder = &MockCPSActionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCPSActionRepository) EXPECT() *MockCPSActionRepositoryMockRecorder {
	return m.recorder
}

// ApproveActionRequest mocks base method.
func (m *MockCPSActionRepository) ApproveActionRequest(ctx context.Context, actionCode string, action entities.CPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveActionRequest", ctx, actionCode, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveActionRequest indicates an expected call of ApproveActionRequest.
func (mr *MockCPSActionRepositoryMockRecorder) ApproveActionRequest(ctx, actionCode, action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveActionRequest", reflect.TypeOf((*MockCPSActionRepository)(nil).ApproveActionRequest), ctx, actionCode, action)
}

// CheckRequestExists mocks base method.
func (m *MockCPSActionRepository) CheckRequestExists(ctx context.Context, action entities.CPSAction) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRequestExists", ctx, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRequestExists indicates an expected call of CheckRequestExists.
func (mr *MockCPSActionRepositoryMockRecorder) CheckRequestExists(ctx, action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRequestExists", reflect.TypeOf((*MockCPSActionRepository)(nil).CheckRequestExists), ctx, action)
}

// CreateCPSAction mocks base method.
func (m *MockCPSActionRepository) CreateCPSAction(ctx context.Context, department string, portalCards []string, action entities.CPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCPSAction", ctx, department, portalCards, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCPSAction indicates an expected call of CreateCPSAction.
func (mr *MockCPSActionRepositoryMockRecorder) CreateCPSAction(ctx, department, portalCards, action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCPSAction", reflect.TypeOf((*MockCPSActionRepository)(nil).CreateCPSAction), ctx, department, portalCards, action)
}

// FindByActionCode mocks base method.
func (m *MockCPSActionRepository) FindByActionCode(ctx context.Context, code string) (*entities.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByActionCode", ctx, code)
	ret0, _ := ret[0].(*entities.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByActionCode indicates an expected call of FindByActionCode.
func (mr *MockCPSActionRepositoryMockRecorder) FindByActionCode(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByActionCode", reflect.TypeOf((*MockCPSActionRepository)(nil).FindByActionCode), ctx, code)
}

// UpdateActionStatus mocks base method.
func (m *MockCPSActionRepository) UpdateActionStatus(ctx context.Context, actionCode, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActionStatus", ctx, actionCode, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActionStatus indicates an expected call of UpdateActionStatus.
func (mr *MockCPSActionRepositoryMockRecorder) UpdateActionStatus(ctx, actionCode, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActionStatus", reflect.TypeOf((*MockCPSActionRepository)(nil).UpdateActionStatus), ctx, actionCode, status)
}

// ValidateActionRequest mocks base method.
func (m *MockCPSActionRepository) ValidateActionRequest(ctx context.Context, actionCode, userDept string) (*entities.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateActionRequest", ctx, actionCode, userDept)
	ret0, _ := ret[0].(*entities.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateActionRequest indicates an expected call of ValidateActionRequest.
func (mr *MockCPSActionRepositoryMockRecorder) ValidateActionRequest(ctx, actionCode, userDept interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateActionRequest", reflect.TypeOf((*MockCPSActionRepository)(nil).ValidateActionRequest), ctx, actionCode, userDept)
}

// MockDepartmentRepository is a mock of DepartmentRepository interface.
type MockDepartmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentRepositoryMockRecorder
}

// MockDepartmentRepositoryMockRecorder is the mock recorder for MockDepartmentRepository.
type MockDepartmentRepositoryMockRecorder struct {
	mock *MockDepartmentRepository
}

// NewMockDepartmentRepository creates a new mock instance.
func NewMockDepartmentRepository(ctrl *gomock.Controller) *MockDepartmentRepository {
	mock := &MockDepartmentRepository{ctrl: ctrl}
	mock.recorder = &MockDepartmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartmentRepository) EXPECT() *MockDepartmentRepositoryMockRecorder {
	return m.recorder
}

// CheckDepartmentExists mocks base method.
func (m *MockDepartmentRepository) CheckDepartmentExists(ctx context.Context, department string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDepartmentExists", ctx, department)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckDepartmentExists indicates an expected call of CheckDepartmentExists.
func (mr *MockDepartmentRepositoryMockRecorder) CheckDepartmentExists(ctx, department interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDepartmentExists", reflect.TypeOf((*MockDepartmentRepository)(nil).CheckDepartmentExists), ctx, department)
}

// CreateDepartment mocks base method.
func (m *MockDepartmentRepository) CreateDepartment(ctx context.Context, dept entities.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDepartment", ctx, dept)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDepartment indicates an expected call of CreateDepartment.
func (mr *MockDepartmentRepositoryMockRecorder) CreateDepartment(ctx, dept interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDepartment", reflect.TypeOf((*MockDepartmentRepository)(nil).CreateDepartment), ctx, dept)
}

// UpdateDepartment mocks base method.
func (m *MockDepartmentRepository) UpdateDepartment(ctx context.Context, code, department string, portalCards []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDepartment", ctx, code, department, portalCards)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDepartment indicates an expected call of UpdateDepartment.
func (mr *MockDepartmentRepositoryMockRecorder) UpdateDepartment(ctx, code, department, portalCards interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDepartment", reflect.TypeOf((*MockDepartmentRepository)(nil).UpdateDepartment), ctx, code, department, portalCards)
}