// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/port/inbound/miniapp/inbound.go

// Package mock_inbound is a generated GoMock package.
package mock_inbound

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInbound is a mock of Inbound interface.
type MockInbound struct {
	ctrl     *gomock.Controller
	recorder *MockInboundMockRecorder
}

// MockInboundMockRecorder is the mock recorder for MockInbound.
type MockInboundMockRecorder struct {
	mock *MockInbound
}

// NewMockInbound creates a new mock instance.
func NewMockInbound(ctrl *gomock.Controller) *MockInbound {
	mock := &MockInbound{ctrl: ctrl}
	mock.recorder = &MockInboundMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInbound) EXPECT() *MockInboundMockRecorder {
	return m.recorder
}

// CheckerMiniApp mocks base method.
func (m *MockInbound) CheckerMiniApp(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckerMiniApp", w, r)
}

// CheckerMiniApp indicates an expected call of CheckerMiniApp.
func (mr *MockInboundMockRecorder) CheckerMiniApp(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckerMiniApp", reflect.TypeOf((*MockInbound)(nil).CheckerMiniApp), w, r)
}

// MakerCreateMiniApp mocks base method.
func (m *MockInbound) MakerCreateMiniApp(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MakerCreateMiniApp", w, r)
}

// MakerCreateMiniApp indicates an expected call of MakerCreateMiniApp.
func (mr *MockInboundMockRecorder) MakerCreateMiniApp(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakerCreateMiniApp", reflect.TypeOf((*MockInbound)(nil).MakerCreateMiniApp), w, r)
}
