// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/bulkcustomer/repository/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/domain/bulkcustomer/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockBulkCustomerRepo is a mock of BulkCustomerRepo interface.
type MockBulkCustomerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBulkCustomerRepoMockRecorder
}

// MockBulkCustomerRepoMockRecorder is the mock recorder for MockBulkCustomerRepo.
type MockBulkCustomerRepoMockRecorder struct {
	mock *MockBulkCustomerRepo
}

// NewMockBulkCustomerRepo creates a new mock instance.
func NewMockBulkCustomerRepo(ctrl *gomock.Controller) *MockBulkCustomerRepo {
	mock := &MockBulkCustomerRepo{ctrl: ctrl}
	mock.recorder = &MockBulkCustomerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBulkCustomerRepo) EXPECT() *MockBulkCustomerRepoMockRecorder {
	return m.recorder
}

// ApproveBulkBranchesDisable mocks base method.
func (m *MockBulkCustomerRepo) ApproveBulkBranchesDisable(ctx context.Context, actionID string, approve bool, reason *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveBulkBranchesDisable", ctx, actionID, approve, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveBulkBranchesDisable indicates an expected call of ApproveBulkBranchesDisable.
func (mr *MockBulkCustomerRepoMockRecorder) ApproveBulkBranchesDisable(ctx, actionID, approve, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveBulkBranchesDisable", reflect.TypeOf((*MockBulkCustomerRepo)(nil).ApproveBulkBranchesDisable), ctx, actionID, approve, reason)
}

// ApproveSingleBranchDisable mocks base method.
func (m *MockBulkCustomerRepo) ApproveSingleBranchDisable(ctx context.Context, actionID string, approve bool, reason *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveSingleBranchDisable", ctx, actionID, approve, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveSingleBranchDisable indicates an expected call of ApproveSingleBranchDisable.
func (mr *MockBulkCustomerRepoMockRecorder) ApproveSingleBranchDisable(ctx, actionID, approve, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveSingleBranchDisable", reflect.TypeOf((*MockBulkCustomerRepo)(nil).ApproveSingleBranchDisable), ctx, actionID, approve, reason)
}

// DisableMultipleBranches mocks base method.
func (m *MockBulkCustomerRepo) DisableMultipleBranches(ctx context.Context, branches []entities.Branch, maker entities.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableMultipleBranches", ctx, branches, maker)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableMultipleBranches indicates an expected call of DisableMultipleBranches.
func (mr *MockBulkCustomerRepoMockRecorder) DisableMultipleBranches(ctx, branches, maker interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableMultipleBranches", reflect.TypeOf((*MockBulkCustomerRepo)(nil).DisableMultipleBranches), ctx, branches, maker)
}

// DisableSingleBranch mocks base method.
func (m *MockBulkCustomerRepo) DisableSingleBranch(ctx context.Context, branch entities.Branch, maker entities.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableSingleBranch", ctx, branch, maker)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableSingleBranch indicates an expected call of DisableSingleBranch.
func (mr *MockBulkCustomerRepoMockRecorder) DisableSingleBranch(ctx, branch, maker interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableSingleBranch", reflect.TypeOf((*MockBulkCustomerRepo)(nil).DisableSingleBranch), ctx, branch, maker)
}

// GetAllBranches mocks base method.
func (m *MockBulkCustomerRepo) GetAllBranches(ctx context.Context, region, district string) ([]entities.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBranches", ctx, region, district)
	ret0, _ := ret[0].([]entities.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBranches indicates an expected call of GetAllBranches.
func (mr *MockBulkCustomerRepoMockRecorder) GetAllBranches(ctx, region, district interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBranches", reflect.TypeOf((*MockBulkCustomerRepo)(nil).GetAllBranches), ctx, region, district)
}

// GetBranch mocks base method.
func (m *MockBulkCustomerRepo) GetBranch(ctx context.Context, region, district string) ([]entities.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBranch", ctx, region, district)
	ret0, _ := ret[0].([]entities.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBranch indicates an expected call of GetBranch.
func (mr *MockBulkCustomerRepoMockRecorder) GetBranch(ctx, region, district interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBranch", reflect.TypeOf((*MockBulkCustomerRepo)(nil).GetBranch), ctx, region, district)
}

// GetBranchByCode mocks base method.
func (m *MockBulkCustomerRepo) GetBranchByCode(ctx context.Context, branchCode string) (entities.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBranchByCode", ctx, branchCode)
	ret0, _ := ret[0].(entities.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBranchByCode indicates an expected call of GetBranchByCode.
func (mr *MockBulkCustomerRepoMockRecorder) GetBranchByCode(ctx, branchCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBranchByCode", reflect.TypeOf((*MockBulkCustomerRepo)(nil).GetBranchByCode), ctx, branchCode)
}
