// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/bulkcustomer/repository/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "gitlab.com/bersufekadgetachew/cbe-super-app-cps-action/internal/domain/bulkcustomer/entities"
)

// MockBulkCustomerRepo is a mock of BulkCustomerRepo interface.
type MockBulkCustomerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBulkCustomerRepoMockRecorder
}

// MockBulkCustomerRepoMockRecorder is the mock recorder for MockBulkCustomerRepo.
type MockBulkCustomerRepoMockRecorder struct {
	mock *MockBulkCustomerRepo
}

// NewMockBulkCustomerRepo creates a new mock instance.
func NewMockBulkCustomerRepo(ctrl *gomock.Controller) *MockBulkCustomerRepo {
	mock := &MockBulkCustomerRepo{ctrl: ctrl}
	mock.recorder = &MockBulkCustomerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBulkCustomerRepo) EXPECT() *MockBulkCustomerRepoMockRecorder {
	return m.recorder
}

// ApproveBulkBranchesDisable mocks base method.
func (m *MockBulkCustomerRepo) ApproveBulkBranchesDisable(ctx context.Context, actionID string, approve bool, reason *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveBulkBranchesDisable", ctx, actionID, approve, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveBulkBranchesDisable indicates an expected call of ApproveBulkBranchesDisable.
func (mr *MockBulkCustomerRepoMockRecorder) ApproveBulkBranchesDisable(ctx, actionID, approve, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveBulkBranchesDisable", reflect.TypeOf((*MockBulkCustomerRepo)(nil).ApproveBulkBranchesDisable), ctx, actionID, approve, reason)
}

// ApproveSingleBranchDisable mocks base method.
func (m *MockBulkCustomerRepo) ApproveSingleBranchDisable(ctx context.Context, actionID string, approve bool, reason *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveSingleBranchDisable", ctx, actionID, approve, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveSingleBranchDisable indicates an expected call of ApproveSingleBranchDisable.
func (mr *MockBulkCustomerRepoMockRecorder) ApproveSingleBranchDisable(ctx, actionID, approve, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveSingleBranchDisable", reflect.TypeOf((*MockBulkCustomerRepo)(nil).ApproveSingleBranchDisable), ctx, actionID, approve, reason)
}

// DisableMultipleBranches mocks base method.
func (m *MockBulkCustomerRepo) DisableMultipleBranches(ctx context.Context, branchCodes []string) (*entities.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableMultipleBranches", ctx, branchCodes)
	ret0, _ := ret[0].(*entities.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableMultipleBranches indicates an expected call of DisableMultipleBranches.
func (mr *MockBulkCustomerRepoMockRecorder) DisableMultipleBranches(ctx, branchCodes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableMultipleBranches", reflect.TypeOf((*MockBulkCustomerRepo)(nil).DisableMultipleBranches), ctx, branchCodes)
}

// DisableSingleBranch mocks base method.
func (m *MockBulkCustomerRepo) DisableSingleBranch(ctx context.Context, branchCode string, cpsData entities.CPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableSingleBranch", ctx, branchCode, cpsData)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableSingleBranch indicates an expected call of DisableSingleBranch.
func (mr *MockBulkCustomerRepoMockRecorder) DisableSingleBranch(ctx, branchCode, cpsData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableSingleBranch", reflect.TypeOf((*MockBulkCustomerRepo)(nil).DisableSingleBranch), ctx, branchCode, cpsData)
}

// FilterMultipleBranches mocks base method.
func (m *MockBulkCustomerRepo) FilterMultipleBranches(ctx context.Context, region, district string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterMultipleBranches", ctx, region, district)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterMultipleBranches indicates an expected call of FilterMultipleBranches.
func (mr *MockBulkCustomerRepoMockRecorder) FilterMultipleBranches(ctx, region, district interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterMultipleBranches", reflect.TypeOf((*MockBulkCustomerRepo)(nil).FilterMultipleBranches), ctx, region, district)
}

// FilterSingleBranches mocks base method.
func (m *MockBulkCustomerRepo) FilterSingleBranches(ctx context.Context, region, district string) ([]entities.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterSingleBranches", ctx, region, district)
	ret0, _ := ret[0].([]entities.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterSingleBranches indicates an expected call of FilterSingleBranches.
func (mr *MockBulkCustomerRepoMockRecorder) FilterSingleBranches(ctx, region, district interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterSingleBranches", reflect.TypeOf((*MockBulkCustomerRepo)(nil).FilterSingleBranches), ctx, region, district)
}
