// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: proto/topup.proto

package topup

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopupRequest) Reset() {
	*x = TopupRequest{}
	mi := &file_proto_topup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupRequest) ProtoMessage() {}

func (x *TopupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_topup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupRequest.ProtoReflect.Descriptor instead.
func (*TopupRequest) Descriptor() ([]byte, []int) {
	return file_proto_topup_proto_rawDescGZIP(), []int{0}
}

type Services struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Self          bool                   `protobuf:"varint,1,opt,name=Self,proto3" json:"Self,omitempty"`
	Other         bool                   `protobuf:"varint,2,opt,name=Other,proto3" json:"Other,omitempty"`
	Agent         bool                   `protobuf:"varint,3,opt,name=Agent,proto3" json:"Agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Services) Reset() {
	*x = Services{}
	mi := &file_proto_topup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Services) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Services) ProtoMessage() {}

func (x *Services) ProtoReflect() protoreflect.Message {
	mi := &file_proto_topup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Services.ProtoReflect.Descriptor instead.
func (*Services) Descriptor() ([]byte, []int) {
	return file_proto_topup_proto_rawDescGZIP(), []int{1}
}

func (x *Services) GetSelf() bool {
	if x != nil {
		return x.Self
	}
	return false
}

func (x *Services) GetOther() bool {
	if x != nil {
		return x.Other
	}
	return false
}

func (x *Services) GetAgent() bool {
	if x != nil {
		return x.Agent
	}
	return false
}

type Topup struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code           string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Avatar         string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Enabled        bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Services       *Services              `protobuf:"bytes,6,opt,name=services,proto3" json:"services,omitempty"`
	IsDeleted      bool                   `protobuf:"varint,7,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastModifiedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_modified_at,json=lastModifiedAt,proto3" json:"last_modified_at,omitempty"`
	DeletedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Topup) Reset() {
	*x = Topup{}
	mi := &file_proto_topup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topup) ProtoMessage() {}

func (x *Topup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_topup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topup.ProtoReflect.Descriptor instead.
func (*Topup) Descriptor() ([]byte, []int) {
	return file_proto_topup_proto_rawDescGZIP(), []int{2}
}

func (x *Topup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Topup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topup) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Topup) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Topup) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Topup) GetServices() *Services {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Topup) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Topup) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Topup) GetLastModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedAt
	}
	return nil
}

func (x *Topup) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type TopupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topups        []*Topup               `protobuf:"bytes,1,rep,name=topups,proto3" json:"topups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopupResponse) Reset() {
	*x = TopupResponse{}
	mi := &file_proto_topup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupResponse) ProtoMessage() {}

func (x *TopupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_topup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupResponse.ProtoReflect.Descriptor instead.
func (*TopupResponse) Descriptor() ([]byte, []int) {
	return file_proto_topup_proto_rawDescGZIP(), []int{3}
}

func (x *TopupResponse) GetTopups() []*Topup {
	if x != nil {
		return x.Topups
	}
	return nil
}

var File_proto_topup_proto protoreflect.FileDescriptor

const file_proto_topup_proto_rawDesc = "" +
	"\n" +
	"\x11proto/topup.proto\x12\x05topup\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0e\n" +
	"\fTopupRequest\"J\n" +
	"\bServices\x12\x12\n" +
	"\x04Self\x18\x01 \x01(\bR\x04Self\x12\x14\n" +
	"\x05Other\x18\x02 \x01(\bR\x05Other\x12\x14\n" +
	"\x05Agent\x18\x03 \x01(\bR\x05Agent\"\xf9\x02\n" +
	"\x05Topup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12+\n" +
	"\bservices\x18\x06 \x01(\v2\x0f.topup.ServicesR\bservices\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\a \x01(\bR\tisDeleted\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12D\n" +
	"\x10last_modified_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0elastModifiedAt\x129\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"5\n" +
	"\rTopupResponse\x12$\n" +
	"\x06topups\x18\x01 \x03(\v2\f.topup.TopupR\x06topups2H\n" +
	"\fTopupService\x128\n" +
	"\vGetAllTopup\x12\x13.topup.TopupRequest\x1a\x14.topup.TopupResponseBBZ@github.com/cbesuperapp/cbe-super-app-cps-action/grpc/topup;topupb\x06proto3"

var (
	file_proto_topup_proto_rawDescOnce sync.Once
	file_proto_topup_proto_rawDescData []byte
)

func file_proto_topup_proto_rawDescGZIP() []byte {
	file_proto_topup_proto_rawDescOnce.Do(func() {
		file_proto_topup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_topup_proto_rawDesc), len(file_proto_topup_proto_rawDesc)))
	})
	return file_proto_topup_proto_rawDescData
}

var file_proto_topup_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_topup_proto_goTypes = []any{
	(*TopupRequest)(nil),          // 0: topup.TopupRequest
	(*Services)(nil),              // 1: topup.Services
	(*Topup)(nil),                 // 2: topup.Topup
	(*TopupResponse)(nil),         // 3: topup.TopupResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_topup_proto_depIdxs = []int32{
	1, // 0: topup.Topup.services:type_name -> topup.Services
	4, // 1: topup.Topup.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: topup.Topup.last_modified_at:type_name -> google.protobuf.Timestamp
	4, // 3: topup.Topup.deleted_at:type_name -> google.protobuf.Timestamp
	2, // 4: topup.TopupResponse.topups:type_name -> topup.Topup
	0, // 5: topup.TopupService.GetAllTopup:input_type -> topup.TopupRequest
	3, // 6: topup.TopupService.GetAllTopup:output_type -> topup.TopupResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_topup_proto_init() }
func file_proto_topup_proto_init() {
	if File_proto_topup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_topup_proto_rawDesc), len(file_proto_topup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_topup_proto_goTypes,
		DependencyIndexes: file_proto_topup_proto_depIdxs,
		MessageInfos:      file_proto_topup_proto_msgTypes,
	}.Build()
	File_proto_topup_proto = out.File
	file_proto_topup_proto_goTypes = nil
	file_proto_topup_proto_depIdxs = nil
}
