version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - revive
    - misspell
    - gocyclo
    - dupl
    - goconst
    - nakedret
    - unconvert
    - prealloc
    - whitespace
    - copyloopvar
    - gosec
    - gocritic
    - nolintlint
    - predeclared
    - dogsled
    - bodyclose
    - durationcheck
    - errorlint
    - cyclop
    - funlen

linters-settings:
  revive:
    severity: warning
    rules:
      - name: exported
      - name: package-comments
      - name: var-naming
      - name: indent-error-flow
      - name: if-return
      - name: blank-imports
      - name: context-keys-type
      - name: empty-lines
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 12
  misspell:
    locale: US
  dupl:
    threshold: 120
  goconst:
    min-len: 2
    min-occurrences: 2
  gosec:
    excludes:
      - G304 # file path provided as taint input
      - G306 # Expect WriteFile permissions to be 0600 or less
    severity: medium
    confidence: medium
  cyclop:
    max-complexity: 12
  funlen:
    lines: 120
    statements: 70
  gocritic:
    enabled-tags:
      - performance
      - style
      - diagnostic
  nolintlint:
    require-explanation: true
    require-specific: true

issues:
  exclude-dirs-use-default: true
  exclude-dirs:
    - docs
    - grpc
    - mock-test/mocks
    - vendor
  exclude-files:
    - ".*\\.pb\\.go"
    - ".*_grpc\\.pb\\.go"
    - ".*mock.*\\.go"
    - "cmd/__debug_bin\\..*"
  exclude-rules:
    - path: _test\\.go
      linters:
        - gocyclo
        - dupl
        - funlen
    - path: internal/constants/.*
      linters:
        - goconst
  max-issues-per-linter: 0
  max-same-issues: 0
  new: true

output:
  sort-results: true
  formats:
    colored-line-number: {}
