CREATE TABLE USERS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    USER_CODE VARCHAR2(64) UNIQUE NOT NULL,
    USERNAME VARCHAR2(32) UNIQUE,
    BRANCH_ID RAW(16) NOT NULL,
    CONTACT_EMAIL VARCHAR2(255),
    CONTACT_PHONE VARCHAR2(12) UNIQUE NOT NULL,
    CUSTOMER_NUMBER VARCHAR2(32) UNIQUE NOT NULL,
    CUSTOMER_SEGMENTATION VARCHAR2(64),
    FIRST_NAME VARCHAR2(32),
    LAST_NAME VARCHAR2(32),
    MIDDLE_NAME VARCHAR2(32),
    FULL_NAME VARCHAR2(96),
    GENDER VARCHAR2(6) NOT NULL,
    BIRTH_OF_DATE DATE,
    AVATAR VARCHAR2(255),
    SECTOR VARCHAR2(64),
    OWNERSHIP VARCHAR2(64),
    PUSH_TOKEN VARCHAR2(255) NOT NULL,
    INDUSTRY VARCHAR2(64),
    LANGUAGE VARCHAR2(3) DEFAULT 'EN',
    PIN VARCHAR2(255) NOT NULL,
    PIN_HISTORY CLOB,
    FAILED_LOGIN_ATTEMPT NUMBER DEFAULT 0,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    IS_LOCKED NUMBER(1) DEFAULT 0,
    IS_BUDGET_ENABLED NUMBER(1) DEFAULT 0,
    IS_SUPERAPP_ENABLED NUMBER(1) DEFAULT 0,
    IS_USSD_ENABLED NUMBER(1) DEFAULT 0,
    IS_BLOCKED NUMBER(1) DEFAULT 0,
    LOCK_EXPIRES_AT TIMESTAMP,
    LAST_LOGIN_AT TIMESTAMP,
    PIN_CREATED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_USERS_GENDER CHECK (GENDER IN ('MALE', 'FEMALE')),
    CONSTRAINT CHK_USERS_LANGUAGE CHECK (
        LANGUAGE IN ('EN', 'AM', 'AR')
    ),
    CONSTRAINT CHECK_USERS_IS_ACTIVE CHECK (IS_ACTIVE IN (0, 1)),
    CONSTRAINT CHECK_USERS_IS_LOCKED CHECK (IS_LOCKED IN (0, 1)),
    CONSTRAINT CHECK_USERS_IS_BLOCKED CHECK (IS_BLOCKED IN (0, 1)),
    CONSTRAINT CHECK_USERS_IS_USSD_ENABLED CHECK (IS_USSD_ENABLED IN (0, 1)),
    CONSTRAINT CHECK_USERS_IS_BUDGET_ENABLED CHECK (IS_BUDGET_ENABLED IN (0, 1)),
    CONSTRAINT CHECK_USERS_IS_SUPERAPP_ENABLED CHECK (IS_SUPERAPP_ENABLED IN (0, 1)),
    CONSTRAINT FK_USERS_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES ACCOUNT_BLOCKS (ID) ON DELETE CASCADE
);

CREATE TABLE ACCESS_LISTS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    NAME VARCHAR2(64) NOT NULL,
    SERVICE_KEY VARCHAR2(32) NOT NULL,
    IS_USSD_ENABLED NUMBER(1) DEFAULT 0 NOT NULL,
    IS_ENABLED NUMBER(1) DEFAULT 1,
    IS_DELETED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHECK_ACCESS_LISTS_IS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHECK_ACCESS_LISTS_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE TABLE SERVICES (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ACCESS_LIST_ID RAW(16) UNIQUE NOT NULL,
    SERVICE_CODE VARCHAR2(64) NOT NULL UNIQUE,
    MINIMUM_FRAUD_AMOUNT NUMBER(19, 4) NOT NULL,
    PRODUCT_GL_ACCOUNT VARCHAR2(16) NOT NULL,
    PRODUCT_GL_ACCOUNT_CURRENCY VARCHAR2(3) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    IS_DELETED NUMBER(1) DEFAULT 0,
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_SERVICES_ACCESS_LIST_ID FOREIGN KEY (ACCESS_LIST_ID) REFERENCES ACCESS_LISTS (ID),
    CONSTRAINT CHECK_SERVICES_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE TABLE SERVICE_CAP (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    SERVICE_ID RAW(16) NOT NULL,
    SOURCE VARCHAR2(16) NOT NULL,
    CURRENCY VARCHAR2(3) NOT NULL,
    SINGLE_CAP NUMBER(19, 4) NOT NULL,
    MINIMUM_TRANSFER_CAP NUMBER(19, 4) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    IS_DELETED NUMBER(1) DEFAULT 0,
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_SERVICE_CAPS_SERVICE_ID FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES (ID),
    CONSTRAINT CHECK_SERVICE_CAPS_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CHECK_SERVICE_CAPS_SOURCE CHECK (
        SOURCE IN (
            'APP',
            'USSD',
            'INTERNET_BANKING'
        )
    ),
    CONSTRAINT CHECK_SERVICE_CAPS_CURRENCY CHECK (
        CURRENCY IN ('ETB', 'USD', 'EUR', 'GBP')
    )
);

# ---

CREATE TABLE CUSTOMER_GROUPS (
    ID            RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    NAME          VARCHAR2(32) NOT NULL,
    IS_ENABLED       NUMBER(1) DEFAULT 1,
    IS_DELETED NUMBER (1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHECK_CUSTOMER_GROUPS_IS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHECK_CUSTOMER_GROUPS_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE TABLE CUSTOMER_SEGMENTATIONS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    NAME VARCHAR2(32) NOT NULL,
    CUSTOMER_GROUP_ID RAW(16) NOT NULL,
    IS_ENABLED NUMBER(1) DEFAULT 1,
    IS_DELETED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHECK_CUSTOMER_SEGMENTATIONS_IS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHECK_CUSTOMER_SEGMENTATIONS_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT FK_CUSTOMER_SEGMENTATIONS_CUSTOMER_GROUP_ID FOREIGN KEY (CUSTOMER_GROUP_ID) REFERENCES CUSTOMER_GROUPS (ID)
);

CREATE TABLE CUSTOMER_SUB_SEGMENTS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    NAME VARCHAR2(32) NOT NULL,
    CUSTOMER_SEGMENTATION_ID RAW(16) NOT NULL,
    SUPERAPP_ROLE_ID RAW(16) NOT NULL,
    IS_ENABLED NUMBER(1) DEFAULT 1,
    IS_DELETED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHECK_CUSTOMER_SUB_SEGMENTS_IS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHECK_CUSTOMER_SUB_SEGMENTS_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT FK_CUSTOMER_SUB_SEGMENTS_CUSTOMER_SEGMENTATION_ID FOREIGN KEY (CUSTOMER_SEGMENTATION_ID) REFERENCES CUSTOMER_SEGMENTATIONS (ID),
    CONSTRAINT FK_CUSTOMER_SUB_SEGMENTS_SUPERAPP_ROLE_ID FOREIGN KEY (SUPERAPP_ROLE_ID) REFERENCES SUPERAPP_ROLE (ID)
);

CREATE TABLE SUPERAPP_ROLE (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    NAME VARCHAR2(32) NOT NULL,
    ROLE_CODE VARCHAR2(32) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(128),
    IS_ENABLED NUMBER(1) DEFAULT 1,
    IS_DELETED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHECK_SUPERAPP_ROLE_IS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHECK_SUPERAPP_ROLE_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
);

CREATE TABLE SITOTA (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    USER_CODE RAW(16) NOT NULL,
    SENDER_ACCOUNT_ID RAW(16) NOT NULL,
    BUDGET_ID RAW(16),
    RECEIVER_CUSTOMER_NUMBER VARCHAR2(32) NOT NULL,
    CLAIMED_AMOUNT NUMBER(19, 4),
    OPENING_DATE TIMESTAMP,
    FT_NUMBER VARCHAR2(24),
    DEBIT_AMOUNT NUMBER(19, 4) NOT NULL,
    DEBIT_CURRENCY VARCHAR2(3) NOT NULL,
    CREDIT_CURRENCY VARCHAR2(3),
    LOCK_ID VARCHAR2(32),
    LOCKED_AMOUNT NUMBER(19, 4) NOT NULL,
    LOCK_EXPIRY TIMESTAMP,
    REMARK VARCHAR2(128),
    STATUS VARCHAR2(20) DEFAULT 'UNCLAIMED',
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_SITOTA_LOCKED_AMOUNT CHECK (LOCKED_AMOUNT > 0),
    CONSTRAINT CHK_SITOTA_CLAIMED_AMOUNT CHECK (CLAIMED_AMOUNT > 0),
    CONSTRAINT CHK_SITOTA_LOCK_EXPIRY CHECK (LOCK_EXPIRY > SYSTIMESTAMP),
    CONSTRAINT CHK_SITOTA_DEBIT_CURRENCY CHECK (
        DEBIT_CURRENCY IN ('ETB', 'USD', 'GBP', 'EUR')
    ),
    CONSTRAINT CHK_SITOTA_CREDIT_CURRENCY CHECK (
        CREDIT_CURRENCY IN ('ETB', 'USD', 'GBP', 'EUR')
    ),
    CONSTRAINT CHK_SITOTA_STATUS CHECK (
        STATUS IN (
            'UNCLAIMED',
            'CLAIMED',
            'EXPIRED',
            'CANCELLED'
        )
    ),
    CONSTRAINT FK_SITOTA_USER_CODE FOREIGN KEY (USER_CODE) REFERENCES USERS (USER_CODE),
    CONSTRAINT FK_SITOTA_SENDER_ACCOUNT FOREIGN KEY (SENDER_ACCOUNT_ID) REFERENCES ACCOUNTS (ID)
);

CREATE TABLE CARDS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    USER_CODE VARCHAR2(64) NOT NULL,
    CARD_TYPE VARCHAR2(8) NOT NULL,
    CARD_STATUS VARCHAR2(64) NOT NULL,
    COLLECTION_BRANCH_ID RAW(16) NOT NULL,
    REASON VARCHAR2(255),
    FT_NUMBER VARCHAR2(24),
    IS_SET_PIN NUMBER(1) DEFAULT 0,
    CLIENT_ID NUMBER(20, 0) NOT NULL,
    ACCOUNT_CONTRACT_ID NUMBER(20, 0) NOT NULL,
    CARD_CONTRACT_ID NUMBER(20, 0) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHECK_CARD_IS_SET_PIN CHECK (IS_SET_PIN IN (0, 1)),
    CONSTRAINT CHECK_CARD_CARD_TYPE CHECK (
        CARD_TYPE IN ('PHYSICAL', 'VIRTUAL')
    ),
    CONSTRAINT FK_CARDS_USER_CODE FOREIGN KEY (USER_CODE) REFERENCES USERS (USER_CODE) ON DELETE CASCADE,
    CONSTRAINT FK_COLLECTION_BRANCH_ID FOREIGN KEY (COLLECTION_BRANCH_ID) REFERENCES ACCOUNT_BLOCKS (ID) ON DELETE CASCADE
);

CREATE INDEX idx_card_user_code_is_physical ON card (user_code, is_physical);

CREATE TABLE BANKS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    BANK_NAME VARCHAR2(96),
    LOGO VARCHAR2(128),
    BIC_CODE VARCHAR2(32) UNIQUE,
    ACCOUNT_LENGTH NUMBER(5),
    HAS_ALPHA_NUMERIC NUMBER(1) DEFAULT 0,
    IS_CBE NUMBER(1) DEFAULT 0,
    IS_ENABLED NUMBER(1) DEFAULT 1,
    IS_DELETED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHECK_CARD_IS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHECK_CARD_IS_CBE CHECK (IS_CBE IN (0, 1)),
    CONSTRAINT CHECK_CARD_IS_DELETED CHECK (IS_DELETED IN (0, 1)) CONSTRAINT CHK_BANKS_ACCOUNT_LENGTH CHECK (ACCOUNT_LENGTH > 0),
    CONSTRAINT CHK_BANKS_HAS_ALPHA_NUMERIC CHECK (HAS_ALPHA_NUMERIC IN (0, 1)),
);

CREATE TABLE ACCOUNTS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    BANK_ID RAW(16) NOT NULL,
    ACCOUNT_HOLDER_NAME VARCHAR2(96) NOT NULL,
    ACCOUNT_NUMBER VARCHAR2(20) NOT NULL,
    ACCOUNT_CURRENCY VARCHAR2(3) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(64) NULL,
    CUSTOMER_NUMBER VARCHAR2(32) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_ACCOUNTS_BANK FOREIGN KEY (BANK_ID) REFERENCES BANKS (ID)
);

CREATE TABLE TRANSACTIONS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    USER_CODE VARCHAR2(64),
    DEBIT_ACCOUNT_ID RAW(16) NOT NULL,
    CREDIT_ACCOUNT_ID RAW(16) NOT NULL,
    BUDGET_CATEGORY_ID RAW(16),
    TRANSACTION_TYPE VARCHAR2(32) NOT NULL,
    TRANSACTION_PLATFORM VARCHAR2(32) NOT NULL,
    DEBIT_CURRENCY VARCHAR2(3) NOT NULL,
    CREDIT_CURRENCY VARCHAR2(3) NOT NULL,
    PAID_AMOUNT NUMBER(19, 4),
    TOTAL_AMOUNT NUMBER(19, 4),
    SERVICE_FEE NUMBER(19, 4),
    TIP NUMBER(19, 4),
    VAT NUMBER(19, 4),
    CREDIT_AMOUNT NUMBER(19, 4),
    FT_NUMBER VARCHAR2(24),
    NARRATIVE VARCHAR2(64),
    TRANSACTION_REFERENCE VARCHAR2(128),
    EXTERNAL_REFERENCE VARCHAR2(128),
    STATUS VARCHAR2(16),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    PAID_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_TRANSACTIONS_STATUS CHECK (
        STATUS IN (
            'PAID',
            'PENDING',
            'FAILED',
            'REVERSED'
        )
    ),
    CONSTRAINT CHK_TRANSACTIONS_DEBIT_CURRENCY CHECK (
        DEBIT_CURRENCY IN ('ETB', 'USD', 'GBP', 'EUR')
    ),
    CONSTRAINT CHK_TRANSACTIONS_CREDIT_CURRENCY CHECK (
        CREDIT_CURRENCY IN ('ETB', 'USD', 'GBP', 'EUR')
    ),
    CONSTRAINT CHK_TRANSACTIONS_TRANSACTION_TYPE CHECK (
        TRANSACTION_TYPE IN (
            'CBE_TO_CBE',
            'MERCHANT_PAYMENT',
            'VOUCHER',
            'UTILITY',
            'DONATION',
            'CHAT_TOP_UP',
            'CHAT_MONEYREQUEST',
            'CHAT_CBE_TO_CBE',
            'OTHER_BANK',
            'WALLET',
            'BILL',
            'SPLIT_PAYMENT',
            'TOP_UP',
            'CARD',
            'SITOTA',
            'E_COMMERCE',
            'OTHER'
        )
    ),
    CONSTRAINT CHK_TRANSACTIONS_TRANSACTION_PLATFORM CHECK (
        TRANSACTION_PLATFORM IN (
            'APP',
            'USSD',
            'INTERNET_BANKING'
        )
    ),
    CONSTRAINT FK_TRANSACTIONS_DEBIT_ACCOUNT_ID FOREIGN KEY (DEBIT_ACCOUNT_ID) REFERENCES ACCOUNTS (ID),
    CONSTRAINT FK_TRANSACTIONS_CREDIT_ACCOUNT_ID FOREIGN KEY (CREDIT_ACCOUNT_ID) REFERENCES ACCOUNTS (ID),
    CONSTRAINT FK_TRANSACTIONS_USER_CODE FOREIGN KEY (USER_CODE) REFERENCES USERS (USER_CODE),
    CONSTRAINT FK_TRANSACTIONS_BUDGET_CATEGORY_ID FOREIGN KEY (BUDGET_CATEGORY_ID) REFERENCES BUDGET_CATEGORIES (ID)
);

CREATE TABLE WALLET_TRANSACTION (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    TRANSACTION_ID RAW(16) NOT NULL,
    WALLET_ID RAW(16) NOT NULL,
    PHONE_NUMBER VARCHAR2(20),
    CONSTRAINT FK_WALLET_TRANSACTION_TRANSACTION_ID FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS (ID),
    CONSTRAINT FK_WALLET_TRANSACTION_WALLET_ID FOREIGN KEY (WALLET_ID) REFERENCES WALLETS (ID),
);

CREATE TABLE OTHER_BANK_TRANSACTIONS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    TRANSACTION_ID RAW(16) NOT NULL,
    BENEFICIARY_BANK_ID RAW(16) NOT NULL,
    BENEFICIARY_ACCOUNT_ID RAW(16) NOT NULL,
    CONSTRAINT FK_OTHER_BANK_TRANSACTIONS_TRANSACTION_ID FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS (ID),
    CONSTRAINT FK_OTHER_BANK_TRANSACTIONS_BENEFICIARY_BANK_ID FOREIGN KEY (BENEFICIARY_BANK_ID) REFERENCES BANKS (ID),
    CONSTRAINT FK_OTHER_BANK_TRANSACTIONS_BENEFICIARY_ACCOUNT_ID FOREIGN KEY (BENEFICIARY_ACCOUNT_ID) REFERENCES ACCOUNTS (ID),
);

CREATE TABLE BILL_TRANSACTIONS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    TRANSACTION_ID RAW(16) NOT NULL,
    BILL_ID VARCHAR2(128) NOT NULL,
    BILL_PERIOD VARCHAR2(64) NOT NULL,
    CONSTRAINT FK_BILL_TRANSACTIONS_TRANSACTION_ID FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS (ID)
);

CREATE TABLE TOPUP_TRANSACTIONS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    TRANSACTION_ID RAW(16) NOT NULL,
    PHONE_NUMBER VARCHAR2(20) NOT NULL,
    TELECO_OPERATOR VARCHAR2(16) NOT NULL,
    CONSTRAINT CHK_TOPUP_TRANSACTIONS_TELECO_OPERATOR CHECK (
        TELECO_OPERATOR IN ('ethiotelecom', 'safaricom')
    ),
    CONSTRAINT FK_TOPUP_TRANSACTIONS_TRANSACTION_ID FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS (ID)
);


CREATE TABLE VOUCHERS (
    ID RAW(16) PRIMARY KEY,
    USER_CODE VARCHAR2(64) NOT NULL,
    ACCOUNT_ID RAW(16) NOT NULL,
    AMOUNT NUMBER(9, 2) NOT NULL,
    PHONE_NUMBER VARCHAR2(12) NOT NULL,
    VOUCHER_CODE VARCHAR2(12) NOT NULL,
    VOUCHER_STATUS VARCHAR2(20) DEFAULT 'PENDING',
    BUDGET_ID RAW(16),
    GENERATED_FOR VARCHAR2(16) NOT NULL,
    COLLECT_FROM VARCHAR2(8) NOT NULL,
    FT_NUMBER VARCHAR2(24),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    EXPIRED_AT TIMESTAMP,

    CONSTRAINT FK_VOUCHER_USER_CODE FOREIGN KEY (USER_CODE) REFERENCES USERS(USER_CODE),
    CONSTRAINT FK_VOUCHER_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID),
    CONSTRAINT FK_VOUCHER_BUDGET FOREIGN KEY (BUDGET_ID) REFERENCES BUDGETS(ID),

    CONSTRAINT CHK_VOUCHERS_VOUCHER_STATUS CHECK (VOUCHER_STATUS IN ('PENDING', 'CLAIMED', 'EXPIRED', 'CANCELLED')),
    CONSTRAINT CHK_VOUCHERS_GENERATED_FOR CHECK (GENERATED_FOR IN ('APP', 'USSD', 'INTERNET_BANKING')),
    CONSTRAINT CHK_VOUCHERS_COLLECT_FROM CHECK (COLLECT_FROM IN ('ATM', 'BRANCH', 'AGENT')),
    CONSTRAINT CHK_VOUCHERS_AMOUNT CHECK (AMOUNT > 0),

-- Unique Constraint
CONSTRAINT UQ_VOUCHER UNIQUE (VOUCHER_CODE, PHONE_NUMBER, VOUCHER_STATUS, EXPIRED_AT)
);

-- Index
CREATE INDEX IDX_VOUCHER_USER_CREATED ON VOUCHERS (USER_CODE, CREATED_AT DESC);

CREATE TABLE ACCOUNT_BLOCKS (
    ID RAW(24) PRIMARY KEY,
    NAME VARCHAR2(255),
    CODE VARCHAR2(100) UNIQUE,
    ADDRESS VARCHAR2(500),
    SLUG VARCHAR2(255),
    TYPE VARCHAR2(1), -- R, D, C, B
    IS_ENABLED NUMBER(1) DEFAULT 1,
    CITY_ID RAW(24),
    REGION_ID RAW(24),
    DISTRICT_ID RAW(24),
    IS_DELETED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    -- Separate Constraints for each relationship
    CONSTRAINT FK_AB_CITY FOREIGN KEY (CITY_ID) REFERENCES ACCOUNT_BLOCKS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_AB_REGION FOREIGN KEY (REGION_ID) REFERENCES ACCOUNT_BLOCKS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_AB_DISTRICT FOREIGN KEY (DISTRICT_ID) REFERENCES ACCOUNT_BLOCKS (ID) ON DELETE CASCADE
);

-- Adding the type check constraint separately as you intended
ALTER TABLE ACCOUNT_BLOCKS
ADD CONSTRAINT CHK_AB_TYPE CHECK (TYPE IN ('R', 'D', 'C', 'B'));

CREATE TABLE ACCOUNT_BLOCKS_DISABLED_REASONS (
    ID RAW(16) PRIMARY KEY DEFAULT SYS_GUID(),
    account_block_id RAW(16) NOT NULL,
    reason_text VARCHAR2(512),
    created_by VARCHAR2(128),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ABDR_ACCOUNT_BLOCK_ID FOREIGN KEY (account_block_id) REFERENCES ACCOUNT_BLOCKS (ID) ON DELETE CASCADE
);

CREATE INDEX idx_abdr_account_block_id ON ACCOUNT_BLOCKS_DISABLED_REASONS (account_block_id);

CREATE TABLE ACCESS_LIST_CUSTOMER_SEG (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ACCESS_LIST_KEY RAW(16),
    SEGMENTED_ID RAW(16), -- CUSTOMER_SEGMENTATIONS.ID
    ENABLED NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_AL_CUSTOMER_ACCESS_LIST FOREIGN KEY (ACCESS_LIST_KEY) REFERENCES ACCESS_LISTS (id) ON DELETE CASCADE,
    CONSTRAINT FK_AL_CUSTOMER_SEGMENT FOREIGN KEY (SEGMENTED_ID) REFERENCES SUPERAPP_ROLE (ID) ON DELETE CASCADE
);

DROP TABLE ACCESS_LIST_CUSTOMER_SEG CASCADE CONSTRAINTS;

-- 2. Now recreate it
CREATE TABLE ACCESS_LIST_GEO_SEG (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ACCESS_LIST_KEY RAW(16),
    SEGMENTED_ID RAW(16),
    ENABLED NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT FK_AL_GEO_ACCESS_LIST FOREIGN KEY (ACCESS_LIST_KEY) REFERENCES ACCESS_LISTS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_AL_GEO_SEGMENT FOREIGN KEY (SEGMENTED_ID) REFERENCES ACCOUNT_BLOCKS (ID) ON DELETE CASCADE
);

CREATE TABLE WALLETS (
    id RAW(16) PRIMARY KEY,
    name VARCHAR2(255),
    wallet_code VARCHAR2(255),
    service_id RAW(16),
    enabled NUMBER(1) DEFAULT 0,
    avatar VARCHAR2(255),
    services_self NUMBER(1) DEFAULT 0,
    services_other NUMBER(1) DEFAULT 0,
    services_agent NUMBER(1) DEFAULT 0,
    is_deleted NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    last_modified_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    deleted_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_WALLETS_SERVICE FOREIGN KEY (service_id) REFERENCES SERVICES (ID) ON DELETE CASCADE
);