// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/ad/repository/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/adapter/outbound/model"
	entity "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/domain/ad/entity"
	utils "github.com/CBE-Super-App/cbe-super-app-cps-action/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockRepository) Authorize(ctx context.Context, cpsAction model.AuthorizeCPSAction) (*model.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx, cpsAction)
	ret0, _ := ret[0].(*model.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockRepositoryMockRecorder) Authorize(ctx, cpsAction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockRepository)(nil).Authorize), ctx, cpsAction)
}

// CreateOneAdvert mocks base method.
func (m *MockRepository) CreateOneAdvert(ctx context.Context, cpsAction model.CreateCPSAction) (*model.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOneAdvert", ctx, cpsAction)
	ret0, _ := ret[0].(*model.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOneAdvert indicates an expected call of CreateOneAdvert.
func (mr *MockRepositoryMockRecorder) CreateOneAdvert(ctx, cpsAction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOneAdvert", reflect.TypeOf((*MockRepository)(nil).CreateOneAdvert), ctx, cpsAction)
}

// DeleteOneAdvert mocks base method.
func (m *MockRepository) DeleteOneAdvert(ctx context.Context, id string, cpsAction model.CreateCPSAction) (*model.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOneAdvert", ctx, id, cpsAction)
	ret0, _ := ret[0].(*model.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOneAdvert indicates an expected call of DeleteOneAdvert.
func (mr *MockRepositoryMockRecorder) DeleteOneAdvert(ctx, id, cpsAction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOneAdvert", reflect.TypeOf((*MockRepository)(nil).DeleteOneAdvert), ctx, id, cpsAction)
}

// GetAllAdvert mocks base method.
func (m *MockRepository) GetAllAdvert(ctx context.Context, filterParams *utils.Filter) (*entity.AdvertResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAdvert", ctx, filterParams)
	ret0, _ := ret[0].(*entity.AdvertResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAdvert indicates an expected call of GetAllAdvert.
func (mr *MockRepositoryMockRecorder) GetAllAdvert(ctx, filterParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAdvert", reflect.TypeOf((*MockRepository)(nil).GetAllAdvert), ctx, filterParams)
}

// GetOneAdvert mocks base method.
func (m *MockRepository) GetOneAdvert(ctx context.Context, id string) (*entity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneAdvert", ctx, id)
	ret0, _ := ret[0].(*entity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneAdvert indicates an expected call of GetOneAdvert.
func (mr *MockRepositoryMockRecorder) GetOneAdvert(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneAdvert", reflect.TypeOf((*MockRepository)(nil).GetOneAdvert), ctx, id)
}

// Reject mocks base method.
func (m *MockRepository) Reject(ctx context.Context, cpsAction model.RejectCPSAction) (*model.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject", ctx, cpsAction)
	ret0, _ := ret[0].(*model.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reject indicates an expected call of Reject.
func (mr *MockRepositoryMockRecorder) Reject(ctx, cpsAction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*MockRepository)(nil).Reject), ctx, cpsAction)
}

// UpdateOneAdvert mocks base method.
func (m *MockRepository) UpdateOneAdvert(ctx context.Context, id string, cpsAction model.CreateCPSAction) (*model.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOneAdvert", ctx, id, cpsAction)
	ret0, _ := ret[0].(*model.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOneAdvert indicates an expected call of UpdateOneAdvert.
func (mr *MockRepositoryMockRecorder) UpdateOneAdvert(ctx, id, cpsAction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOneAdvert", reflect.TypeOf((*MockRepository)(nil).UpdateOneAdvert), ctx, id, cpsAction)
}
