// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/permission/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/permission/repository.go -destination=internal/domain/permission/mock/repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	entities "github.com/CBE-Super-App/cbe-super-app-cps-action/pkgs/entities"
	gomock "go.uber.org/mock/gomock"
	"context"
)

// MockPermissionGroupRepository is a mock of PermissionGroupRepository interface.
type MockPermissionGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockPermissionGroupRepositoryMockRecorder is the mock recorder for MockPermissionGroupRepository.
type MockPermissionGroupRepositoryMockRecorder struct {
	mock *MockPermissionGroupRepository
}

// NewMockPermissionGroupRepository creates a new mock instance.
func NewMockPermissionGroupRepository(ctrl *gomock.Controller) *MockPermissionGroupRepository {
	mock := &MockPermissionGroupRepository{ctrl: ctrl}
	mock.recorder = &MockPermissionGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionGroupRepository) EXPECT() *MockPermissionGroupRepositoryMockRecorder {
	return m.recorder
}

// CheckPermissionGroupExists mocks base method.
func (m *MockPermissionGroupRepository) CheckPermissionGroupExists(groupName string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermissionGroupExists", groupName)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckPermissionGroupExists indicates an expected call of CheckPermissionGroupExists.
func (mr *MockPermissionGroupRepositoryMockRecorder) CheckPermissionGroupExists(groupName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermissionGroupExists", reflect.TypeOf((*MockPermissionGroupRepository)(nil).CheckPermissionGroupExists), groupName)
}

// CreatePermissionGroupFromAction mocks base method.
func (m *MockPermissionGroupRepository) CreatePermissionGroupFromAction(action entities.CPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePermissionGroupFromAction", action)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePermissionGroupFromAction indicates an expected call of CreatePermissionGroupFromAction.
func (mr *MockPermissionGroupRepositoryMockRecorder) CreatePermissionGroupFromAction(action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePermissionGroupFromAction", reflect.TypeOf((*MockPermissionGroupRepository)(nil).CreatePermissionGroupFromAction), action)
}

// UpdatePermissionGroupFromAction mocks base method.
func (m *MockPermissionGroupRepository) UpdatePermissionGroupFromAction(action entities.CPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePermissionGroupFromAction", action)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePermissionGroupFromAction indicates an expected call of UpdatePermissionGroupFromAction.
func (mr *MockPermissionGroupRepositoryMockRecorder) UpdatePermissionGroupFromAction(action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePermissionGroupFromAction", reflect.TypeOf((*MockPermissionGroupRepository)(nil).UpdatePermissionGroupFromAction), action)
}

// MockPermissionCategoryRepository is a mock of PermissionCategoryRepository interface.
type MockPermissionCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionCategoryRepositoryMockRecorder
	isgomock struct{}
}

// MockPermissionCategoryRepositoryMockRecorder is the mock recorder for MockPermissionCategoryRepository.
type MockPermissionCategoryRepositoryMockRecorder struct {
	mock *MockPermissionCategoryRepository
}

// NewMockPermissionCategoryRepository creates a new mock instance.
func NewMockPermissionCategoryRepository(ctrl *gomock.Controller) *MockPermissionCategoryRepository {
	mock := &MockPermissionCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockPermissionCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionCategoryRepository) EXPECT() *MockPermissionCategoryRepositoryMockRecorder {
	return m.recorder
}

// ValidatePermissionCategories mocks base method.
func (m *MockPermissionCategoryRepository) ValidatePermissionCategories(ctx context.Context,ids []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePermissionCategories", ids)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidatePermissionCategories indicates an expected call of ValidatePermissionCategories.
func (mr *MockPermissionCategoryRepositoryMockRecorder) ValidatePermissionCategories(ctx context.Context,ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePermissionCategories", reflect.TypeOf((*MockPermissionCategoryRepository)(nil).ValidatePermissionCategories), ids)
}

// MockCPSActionRepository is a mock of CPSActionRepository interface.
type MockCPSActionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCPSActionRepositoryMockRecorder
	isgomock struct{}
}

// MockCPSActionRepositoryMockRecorder is the mock recorder for MockCPSActionRepository.
type MockCPSActionRepositoryMockRecorder struct {
	mock *MockCPSActionRepository
}

// NewMockCPSActionRepository creates a new mock instance.
func NewMockCPSActionRepository(ctrl *gomock.Controller) *MockCPSActionRepository {
	mock := &MockCPSActionRepository{ctrl: ctrl}
	mock.recorder = &MockCPSActionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCPSActionRepository) EXPECT() *MockCPSActionRepositoryMockRecorder {
	return m.recorder
}

// ApproveActionRequest mocks base method.
func (m *MockCPSActionRepository) ApproveActionRequest(actionCode string, action entities.CPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveActionRequest", actionCode, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveActionRequest indicates an expected call of ApproveActionRequest.
func (mr *MockCPSActionRepositoryMockRecorder) ApproveActionRequest(actionCode, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveActionRequest", reflect.TypeOf((*MockCPSActionRepository)(nil).ApproveActionRequest), actionCode, action)
}

// CheckPendingRequest mocks base method.
func (m *MockCPSActionRepository) CheckPendingRequest(makerId string, actionStatus entities.ActionStatus, requestAction entities.RequestAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPendingRequest", makerId, actionStatus, requestAction)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckPendingRequest indicates an expected call of CheckPendingRequest.
func (mr *MockCPSActionRepositoryMockRecorder) CheckPendingRequest(makerId, actionStatus, requestAction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPendingRequest", reflect.TypeOf((*MockCPSActionRepository)(nil).CheckPendingRequest), makerId, actionStatus, requestAction)
}

// CreatePermissionGroup mocks base method.
func (m *MockCPSActionRepository) CreatePermissionGroup(action entities.CPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePermissionGroup", action)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePermissionGroup indicates an expected call of CreatePermissionGroup.
func (mr *MockCPSActionRepositoryMockRecorder) CreatePermissionGroup(action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePermissionGroup", reflect.TypeOf((*MockCPSActionRepository)(nil).CreatePermissionGroup), action)
}

// ValidateActionRequest mocks base method.
func (m *MockCPSActionRepository) ValidateActionRequest(actionCode, department string) (entities.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateActionRequest", actionCode, department)
	ret0, _ := ret[0].(entities.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateActionRequest indicates an expected call of ValidateActionRequest.
func (mr *MockCPSActionRepositoryMockRecorder) ValidateActionRequest(actionCode, department any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateActionRequest", reflect.TypeOf((*MockCPSActionRepository)(nil).ValidateActionRequest), actionCode, department)
}
