// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/avatar/repository.go
//
// Generated by this command:
//
//	cursor.appimage -source=internal/domain/avatar/repository.go -destination=tests/avatar/mocks/repository_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "gitlab.com/bersufekadgetachew/cbe-super-app-cps-action/internal/adapter/outbound/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarRepository is a mock of AvatarRepository interface.
type MockAvatarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarRepositoryMockRecorder
	isgomock struct{}
}

// MockAvatarRepositoryMockRecorder is the mock recorder for MockAvatarRepository.
type MockAvatarRepositoryMockRecorder struct {
	mock *MockAvatarRepository
}

// NewMockAvatarRepository creates a new mock instance.
func NewMockAvatarRepository(ctrl *gomock.Controller) *MockAvatarRepository {
	mock := &MockAvatarRepository{ctrl: ctrl}
	mock.recorder = &MockAvatarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarRepository) EXPECT() *MockAvatarRepositoryMockRecorder {
	return m.recorder
}

// CPSActionExists mocks base method.
func (m *MockAvatarRepository) CPSActionExists(ctx context.Context, cpsReq model.CreateCPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CPSActionExists", ctx, cpsReq)
	ret0, _ := ret[0].(error)
	return ret0
}

// CPSActionExists indicates an expected call of CPSActionExists.
func (mr *MockAvatarRepositoryMockRecorder) CPSActionExists(ctx, cpsReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CPSActionExists", reflect.TypeOf((*MockAvatarRepository)(nil).CPSActionExists), ctx, cpsReq)
}

// CreateAvatar mocks base method.
func (m *MockAvatarRepository) CreateAvatar(ctx context.Context, req model.CreateCPSAction) (model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAvatar", ctx, req)
	ret0, _ := ret[0].(model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAvatar indicates an expected call of CreateAvatar.
func (mr *MockAvatarRepositoryMockRecorder) CreateAvatar(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAvatar", reflect.TypeOf((*MockAvatarRepository)(nil).CreateAvatar), ctx, req)
}
