// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/avatar/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/avatar/repository.go -destination=tests/avatar/mocks/repository_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "cbe-super-app-cps-action/internal/adapter/outbound/model"
	avatar "cbe-super-app-cps-action/internal/domain/avatar"
	utils "cbe-super-app-cps-action/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarRepository is a mock of AvatarRepository interface.
type MockAvatarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarRepositoryMockRecorder
	isgomock struct{}
}

// MockAvatarRepositoryMockRecorder is the mock recorder for MockAvatarRepository.
type MockAvatarRepositoryMockRecorder struct {
	mock *MockAvatarRepository
}

// NewMockAvatarRepository creates a new mock instance.
func NewMockAvatarRepository(ctrl *gomock.Controller) *MockAvatarRepository {
	mock := &MockAvatarRepository{ctrl: ctrl}
	mock.recorder = &MockAvatarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarRepository) EXPECT() *MockAvatarRepositoryMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockAvatarRepository) Authorize(ctx context.Context, req model.AuthorizeCPSAction) (model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx, req)
	ret0, _ := ret[0].(model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockAvatarRepositoryMockRecorder) Authorize(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockAvatarRepository)(nil).Authorize), ctx, req)
}

// CPSActionExists mocks base method.
func (m *MockAvatarRepository) CPSActionExists(ctx context.Context, cpsReq model.CreateCPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CPSActionExists", ctx, cpsReq)
	ret0, _ := ret[0].(error)
	return ret0
}

// CPSActionExists indicates an expected call of CPSActionExists.
func (mr *MockAvatarRepositoryMockRecorder) CPSActionExists(ctx, cpsReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CPSActionExists", reflect.TypeOf((*MockAvatarRepository)(nil).CPSActionExists), ctx, cpsReq)
}

// CreateAvatar mocks base method.
func (m *MockAvatarRepository) CreateAvatar(ctx context.Context, req model.CreateCPSAction) (model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAvatar", ctx, req)
	ret0, _ := ret[0].(model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAvatar indicates an expected call of CreateAvatar.
func (mr *MockAvatarRepositoryMockRecorder) CreateAvatar(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAvatar", reflect.TypeOf((*MockAvatarRepository)(nil).CreateAvatar), ctx, req)
}

// DeleteAvatar mocks base method.
func (m *MockAvatarRepository) DeleteAvatar(ctx context.Context, id string, cpsActionReq model.CreateCPSAction) (model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatar", ctx, id, cpsActionReq)
	ret0, _ := ret[0].(model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAvatar indicates an expected call of DeleteAvatar.
func (mr *MockAvatarRepositoryMockRecorder) DeleteAvatar(ctx, id, cpsActionReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatar", reflect.TypeOf((*MockAvatarRepository)(nil).DeleteAvatar), ctx, id, cpsActionReq)
}

// EnableOrDisableAvatar mocks base method.
func (m *MockAvatarRepository) EnableOrDisableAvatar(ctx context.Context, id string, requestAction model.RequestAction, cpsReq model.CreateCPSAction) (*model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableOrDisableAvatar", ctx, id, requestAction, cpsReq)
	ret0, _ := ret[0].(*model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnableOrDisableAvatar indicates an expected call of EnableOrDisableAvatar.
func (mr *MockAvatarRepositoryMockRecorder) EnableOrDisableAvatar(ctx, id, requestAction, cpsReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableOrDisableAvatar", reflect.TypeOf((*MockAvatarRepository)(nil).EnableOrDisableAvatar), ctx, id, requestAction, cpsReq)
}

// GetAllAvatar mocks base method.
func (m *MockAvatarRepository) GetAllAvatar(ctx context.Context, filterParams utils.Filter) (avatar.AvatarResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAvatar", ctx, filterParams)
	ret0, _ := ret[0].(avatar.AvatarResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAvatar indicates an expected call of GetAllAvatar.
func (mr *MockAvatarRepositoryMockRecorder) GetAllAvatar(ctx, filterParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAvatar", reflect.TypeOf((*MockAvatarRepository)(nil).GetAllAvatar), ctx, filterParams)
}

// GetAvatar mocks base method.
func (m *MockAvatarRepository) GetAvatar(ctx context.Context, id string) (*avatar.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatar", ctx, id)
	ret0, _ := ret[0].(*avatar.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatar indicates an expected call of GetAvatar.
func (mr *MockAvatarRepositoryMockRecorder) GetAvatar(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatar", reflect.TypeOf((*MockAvatarRepository)(nil).GetAvatar), ctx, id)
}

// Reject mocks base method.
func (m *MockAvatarRepository) Reject(ctx context.Context, req model.RejectCPSAction) (model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject", ctx, req)
	ret0, _ := ret[0].(model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reject indicates an expected call of Reject.
func (mr *MockAvatarRepositoryMockRecorder) Reject(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*MockAvatarRepository)(nil).Reject), ctx, req)
}

// UpdateAvatar mocks base method.
func (m *MockAvatarRepository) UpdateAvatar(ctx context.Context, id string, req model.CreateCPSAction) (model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", ctx, id, req)
	ret0, _ := ret[0].(model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAvatar indicates an expected call of UpdateAvatar.
func (mr *MockAvatarRepositoryMockRecorder) UpdateAvatar(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockAvatarRepository)(nil).UpdateAvatar), ctx, id, req)
}
