// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/ad/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/ad/repository/repository.go -destination=internal/domain/ad/mocks/repository_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/adapter/outbound/model"
	entity "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/domain/ad"
	utils "github.com/CBE-Super-App/cbe-super-app-cps-action/pkgs/utils"
	utils0 "github.com/CBE-Super-App/cbe-super-app-cps-action/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockAdRepository is a mock of AdRepository interface.
type MockAdRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdRepositoryMockRecorder
	isgomock struct{}
}

// MockAdRepositoryMockRecorder is the mock recorder for MockAdRepository.
type MockAdRepositoryMockRecorder struct {
	mock *MockAdRepository
}

// NewMockAdRepository creates a new mock instance.
func NewMockAdRepository(ctrl *gomock.Controller) *MockAdRepository {
	mock := &MockAdRepository{ctrl: ctrl}
	mock.recorder = &MockAdRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdRepository) EXPECT() *MockAdRepositoryMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockAdRepository) Authorize(ctx context.Context, cpsAction model.AuthorizeCPSAction) (*model.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx, cpsAction)
	ret0, _ := ret[0].(*model.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockAdRepositoryMockRecorder) Authorize(ctx, cpsAction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockAdRepository)(nil).Authorize), ctx, cpsAction)
}

// CreateOneAdvert mocks base method.
func (m *MockAdRepository) CreateOneAdvert(ctx context.Context, cpsAction model.CreateCPSAction) (*model.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOneAdvert", ctx, cpsAction)
	ret0, _ := ret[0].(*model.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOneAdvert indicates an expected call of CreateOneAdvert.
func (mr *MockAdRepositoryMockRecorder) CreateOneAdvert(ctx, cpsAction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOneAdvert", reflect.TypeOf((*MockAdRepository)(nil).CreateOneAdvert), ctx, cpsAction)
}

// DeleteOneAdvert mocks base method.
func (m *MockAdRepository) DeleteOneAdvert(ctx context.Context, id string, cpsAction model.CreateCPSAction) (*model.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOneAdvert", ctx, id, cpsAction)
	ret0, _ := ret[0].(*model.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOneAdvert indicates an expected call of DeleteOneAdvert.
func (mr *MockAdRepositoryMockRecorder) DeleteOneAdvert(ctx, id, cpsAction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOneAdvert", reflect.TypeOf((*MockAdRepository)(nil).DeleteOneAdvert), ctx, id, cpsAction)
}

// GetAllAdvert mocks base method.
func (m *MockAdRepository) GetAllAdvert(ctx context.Context, filterParams *utils0.Filter) (*utils.PaginatedResponse[[]*entity.Advert], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAdvert", ctx, filterParams)
	ret0, _ := ret[0].(*utils.PaginatedResponse[[]*entity.Advert])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAdvert indicates an expected call of GetAllAdvert.
func (mr *MockAdRepositoryMockRecorder) GetAllAdvert(ctx, filterParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAdvert", reflect.TypeOf((*MockAdRepository)(nil).GetAllAdvert), ctx, filterParams)
}

// GetOneAdvert mocks base method.
func (m *MockAdRepository) GetOneAdvert(ctx context.Context, id string) (*entity.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneAdvert", ctx, id)
	ret0, _ := ret[0].(*entity.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneAdvert indicates an expected call of GetOneAdvert.
func (mr *MockAdRepositoryMockRecorder) GetOneAdvert(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneAdvert", reflect.TypeOf((*MockAdRepository)(nil).GetOneAdvert), ctx, id)
}

// Reject mocks base method.
func (m *MockAdRepository) Reject(ctx context.Context, cpsAction model.RejectCPSAction) (*model.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject", ctx, cpsAction)
	ret0, _ := ret[0].(*model.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reject indicates an expected call of Reject.
func (mr *MockAdRepositoryMockRecorder) Reject(ctx, cpsAction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*MockAdRepository)(nil).Reject), ctx, cpsAction)
}

// UpdateOneAdvert mocks base method.
func (m *MockAdRepository) UpdateOneAdvert(ctx context.Context, id string, cpsAction model.CreateCPSAction) (*model.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOneAdvert", ctx, id, cpsAction)
	ret0, _ := ret[0].(*model.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOneAdvert indicates an expected call of UpdateOneAdvert.
func (mr *MockAdRepositoryMockRecorder) UpdateOneAdvert(ctx, id, cpsAction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOneAdvert", reflect.TypeOf((*MockAdRepository)(nil).UpdateOneAdvert), ctx, id, cpsAction)
}
