// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/fayda_account/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/fayda_account/repository/repository.go -destination=internal/domain/fayda_account/mocks/repository_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	cpsactions "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/domain/cps_actions/entities"
	entity "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/domain/fayda_account/entity"
	utils "github.com/CBE-Super-App/cbe-super-app-cps-action/pkgs/utils"
	utils0 "github.com/CBE-Super-App/cbe-super-app-cps-action/utils"
	member "gitlab.com/bersufekadgetachew/cbe-super-app-shared/shared/entities/member"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AuthorizeFaydaAccountDisable mocks base method.
func (m *MockRepository) AuthorizeFaydaAccountDisable(ctx context.Context, action *cpsactions.CPSAction) (*cpsactions.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorizeFaydaAccountDisable", ctx, action)
	ret0, _ := ret[0].(*cpsactions.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthorizeFaydaAccountDisable indicates an expected call of AuthorizeFaydaAccountDisable.
func (mr *MockRepositoryMockRecorder) AuthorizeFaydaAccountDisable(ctx, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizeFaydaAccountDisable", reflect.TypeOf((*MockRepository)(nil).AuthorizeFaydaAccountDisable), ctx, action)
}

// GetAllFaydaAccounts mocks base method.
func (m *MockRepository) GetAllFaydaAccounts(ctx context.Context, filterParams *utils0.Filter) (*utils.PaginatedResponse[[]*member.User], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllFaydaAccounts", ctx, filterParams)
	ret0, _ := ret[0].(*utils.PaginatedResponse[[]*member.User])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllFaydaAccounts indicates an expected call of GetAllFaydaAccounts.
func (mr *MockRepositoryMockRecorder) GetAllFaydaAccounts(ctx, filterParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllFaydaAccounts", reflect.TypeOf((*MockRepository)(nil).GetAllFaydaAccounts), ctx, filterParams)
}

// InitiateDisableFaydaAccount mocks base method.
func (m *MockRepository) InitiateDisableFaydaAccount(ctx context.Context, req entity.CPSAction) (*entity.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateDisableFaydaAccount", ctx, req)
	ret0, _ := ret[0].(*entity.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateDisableFaydaAccount indicates an expected call of InitiateDisableFaydaAccount.
func (mr *MockRepositoryMockRecorder) InitiateDisableFaydaAccount(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateDisableFaydaAccount", reflect.TypeOf((*MockRepository)(nil).InitiateDisableFaydaAccount), ctx, req)
}
