// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/fayda_account/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/fayda_account/repository/repository.go -destination=internal/domain/fayda_account/mocks/repository_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "gitlab.com/bersufekadgetachew/cbe-super-app-cps-action/internal/domain/fayda_account/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AuthorizeFaydaAccountDisable mocks base method.
func (m *MockRepository) AuthorizeFaydaAccountDisable(ctx context.Context, req entity.CPSAction) (*entity.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorizeFaydaAccountDisable", ctx, req)
	ret0, _ := ret[0].(*entity.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthorizeFaydaAccountDisable indicates an expected call of AuthorizeFaydaAccountDisable.
func (mr *MockRepositoryMockRecorder) AuthorizeFaydaAccountDisable(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizeFaydaAccountDisable", reflect.TypeOf((*MockRepository)(nil).AuthorizeFaydaAccountDisable), ctx, req)
}

// InitiateDisableFaydaAccount mocks base method.
func (m *MockRepository) InitiateDisableFaydaAccount(ctx context.Context, req entity.CPSAction) (*entity.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateDisableFaydaAccount", ctx, req)
	ret0, _ := ret[0].(*entity.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateDisableFaydaAccount indicates an expected call of InitiateDisableFaydaAccount.
func (mr *MockRepositoryMockRecorder) InitiateDisableFaydaAccount(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateDisableFaydaAccount", reflect.TypeOf((*MockRepository)(nil).InitiateDisableFaydaAccount), ctx, req)
}

// RejectFaydaAccountDisable mocks base method.
func (m *MockRepository) RejectFaydaAccountDisable(ctx context.Context, req entity.CPSAction) (*entity.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectFaydaAccountDisable", ctx, req)
	ret0, _ := ret[0].(*entity.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RejectFaydaAccountDisable indicates an expected call of RejectFaydaAccountDisable.
func (mr *MockRepositoryMockRecorder) RejectFaydaAccountDisable(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectFaydaAccountDisable", reflect.TypeOf((*MockRepository)(nil).RejectFaydaAccountDisable), ctx, req)
}
