// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/account_block/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	"github.com/CBE-Super-App/cbe-super-app-cps-action/internal/adapter/outbound/model"
	action "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/domain/action"
	constant_utils "github.com/CBE-Super-App/cbe-super-app-cps-action/pkgs/utils"
	constant "github.com/CBE-Super-App/cbe-super-app-cps-action/utils"
	gomock "github.com/golang/mock/gomock"
	member "gitlab.com/bersufekadgetachew/cbe-super-app-shared/shared/entities/member"
)

// MockAccountBlockRepo is a mock of AccountBlockRepo interface.
type MockAccountBlockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAccountBlockRepoMockRecorder
}

// MockAccountBlockRepoMockRecorder is the mock recorder for MockAccountBlockRepo.
type MockAccountBlockRepoMockRecorder struct {
	mock *MockAccountBlockRepo
}

// NewMockAccountBlockRepo creates a new mock instance.
func NewMockAccountBlockRepo(ctrl *gomock.Controller) *MockAccountBlockRepo {
	mock := &MockAccountBlockRepo{ctrl: ctrl}
	mock.recorder = &MockAccountBlockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountBlockRepo) EXPECT() *MockAccountBlockRepoMockRecorder {
	return m.recorder
}

// ApproveBlockCity mocks base method.
func (m *MockAccountBlockRepo) ApproveBlockCity(ctx context.Context, actionID string, approve bool, reason *string, checker action.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveBlockCity", ctx, actionID, approve, reason, checker)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveBlockCity indicates an expected call of ApproveBlockCity.
func (mr *MockAccountBlockRepoMockRecorder) ApproveBlockCity(ctx, actionID, approve, reason, checker interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveBlockCity", reflect.TypeOf((*MockAccountBlockRepo)(nil).ApproveBlockCity), ctx, actionID, approve, reason, checker)
}

// ApproveBlockDistrict mocks base method.
func (m *MockAccountBlockRepo) ApproveBlockDistrict(ctx context.Context, actionID string, approve bool, reason *string, checker action.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveBlockDistrict", ctx, actionID, approve, reason, checker)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveBlockDistrict indicates an expected call of ApproveBlockDistrict.
func (mr *MockAccountBlockRepoMockRecorder) ApproveBlockDistrict(ctx, actionID, approve, reason, checker interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveBlockDistrict", reflect.TypeOf((*MockAccountBlockRepo)(nil).ApproveBlockDistrict), ctx, actionID, approve, reason, checker)
}

// ApproveBlockUser mocks base method.
func (m *MockAccountBlockRepo) ApproveBlockUser(ctx context.Context, actionID string, approve bool, reason *string, checker action.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveBlockUser", ctx, actionID, approve, reason, checker)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveBlockUser indicates an expected call of ApproveBlockUser.
func (mr *MockAccountBlockRepoMockRecorder) ApproveBlockUser(ctx, actionID, approve, reason, checker interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveBlockUser", reflect.TypeOf((*MockAccountBlockRepo)(nil).ApproveBlockUser), ctx, actionID, approve, reason, checker)
}

// ApproveBulkBranchesDisable mocks base method.
func (m *MockAccountBlockRepo) ApproveBulkBranchesDisable(ctx context.Context, actionID string, approve bool, reason *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveBulkBranchesDisable", ctx, actionID, approve, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveBulkBranchesDisable indicates an expected call of ApproveBulkBranchesDisable.
func (mr *MockAccountBlockRepoMockRecorder) ApproveBulkBranchesDisable(ctx, actionID, approve, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveBulkBranchesDisable", reflect.TypeOf((*MockAccountBlockRepo)(nil).ApproveBulkBranchesDisable), ctx, actionID, approve, reason)
}

// ApproveRegionBlock mocks base method.
func (m *MockAccountBlockRepo) ApproveRegionBlock(ctx context.Context, actionID string, approve bool, reason *string, checker action.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveRegionBlock", ctx, actionID, approve, reason, checker)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveRegionBlock indicates an expected call of ApproveRegionBlock.
func (mr *MockAccountBlockRepoMockRecorder) ApproveRegionBlock(ctx, actionID, approve, reason, checker interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveRegionBlock", reflect.TypeOf((*MockAccountBlockRepo)(nil).ApproveRegionBlock), ctx, actionID, approve, reason, checker)
}

// ApproveSingleBranchDisable mocks base method.
func (m *MockAccountBlockRepo) ApproveSingleBranchDisable(ctx context.Context, actionID string, approve bool, reason *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveSingleBranchDisable", ctx, actionID, approve, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveSingleBranchDisable indicates an expected call of ApproveSingleBranchDisable.
func (mr *MockAccountBlockRepoMockRecorder) ApproveSingleBranchDisable(ctx, actionID, approve, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveSingleBranchDisable", reflect.TypeOf((*MockAccountBlockRepo)(nil).ApproveSingleBranchDisable), ctx, actionID, approve, reason)
}

// BlockCity mocks base method.
func (m *MockAccountBlockRepo) BlockCity(ctx context.Context, cityCode string, maker action.CPSAction) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockCity", ctx, cityCode, maker)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockCity indicates an expected call of BlockCity.
func (mr *MockAccountBlockRepoMockRecorder) BlockCity(ctx, cityCode, maker interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockCity", reflect.TypeOf((*MockAccountBlockRepo)(nil).BlockCity), ctx, cityCode, maker)
}

// BlockDistrict mocks base method.
func (m *MockAccountBlockRepo) BlockDistrict(ctx context.Context, districtCode string, maker action.CPSAction) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockDistrict", ctx, districtCode, maker)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockDistrict indicates an expected call of BlockDistrict.
func (mr *MockAccountBlockRepoMockRecorder) BlockDistrict(ctx, districtCode, maker interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockDistrict", reflect.TypeOf((*MockAccountBlockRepo)(nil).BlockDistrict), ctx, districtCode, maker)
}

// BlockRegion mocks base method.
func (m *MockAccountBlockRepo) BlockRegion(ctx context.Context, regionCode string, maker action.CPSAction) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockRegion", ctx, regionCode, maker)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockRegion indicates an expected call of BlockRegion.
func (mr *MockAccountBlockRepoMockRecorder) BlockRegion(ctx, regionCode, maker interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockRegion", reflect.TypeOf((*MockAccountBlockRepo)(nil).BlockRegion), ctx, regionCode, maker)
}

// BlockUser mocks base method.
func (m *MockAccountBlockRepo) BlockUser(ctx context.Context, userID string, maker action.CPSAction) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockUser", ctx, userID, maker)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockUser indicates an expected call of BlockUser.
func (mr *MockAccountBlockRepoMockRecorder) BlockUser(ctx, userID, maker interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockUser", reflect.TypeOf((*MockAccountBlockRepo)(nil).BlockUser), ctx, userID, maker)
}

// DisableMultipleBranches mocks base method.
func (m *MockAccountBlockRepo) DisableMultipleBranches(ctx context.Context, branches []action.Branch, maker action.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableMultipleBranches", ctx, branches, maker)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableMultipleBranches indicates an expected call of DisableMultipleBranches.
func (mr *MockAccountBlockRepoMockRecorder) DisableMultipleBranches(ctx, branches, maker interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableMultipleBranches", reflect.TypeOf((*MockAccountBlockRepo)(nil).DisableMultipleBranches), ctx, branches, maker)
}

// DisableSingleBranch mocks base method.
func (m *MockAccountBlockRepo) DisableSingleBranch(ctx context.Context, branch action.Branch, maker action.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableSingleBranch", ctx, branch, maker)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableSingleBranch indicates an expected call of DisableSingleBranch.
func (mr *MockAccountBlockRepoMockRecorder) DisableSingleBranch(ctx, branch, maker interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableSingleBranch", reflect.TypeOf((*MockAccountBlockRepo)(nil).DisableSingleBranch), ctx, branch, maker)
}

// FilterMultipleBranches mocks base method.
func (m *MockAccountBlockRepo) FilterMultipleBranches(ctx context.Context, region, district string, filterParams *constant.Filter) (*constant_utils.PaginatedResponse[[]*model.Branch], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterMultipleBranches", ctx, region, district)
	ret0, _ := ret[0].([]action.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterMultipleBranches indicates an expected call of FilterMultipleBranches.
func (mr *MockAccountBlockRepoMockRecorder) FilterMultipleBranches(ctx, region, district interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterMultipleBranches", reflect.TypeOf((*MockAccountBlockRepo)(nil).FilterMultipleBranches), ctx, region, district)
}

// FilterSingleBranches mocks base method.
func (m *MockAccountBlockRepo) FilterSingleBranches(ctx context.Context, region, district string, filterParams *constant.Filter) (*constant_utils.PaginatedResponse[[]*model.Branch], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterSingleBranches", ctx, region, district)
	ret0, _ := ret[0].([]action.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterSingleBranches indicates an expected call of FilterSingleBranches.
func (mr *MockAccountBlockRepoMockRecorder) FilterSingleBranches(ctx, region, district interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterSingleBranches", reflect.TypeOf((*MockAccountBlockRepo)(nil).FilterSingleBranches), ctx, region, district)
}

// FindDisableSingleBranchAction mocks base method.
func (m *MockAccountBlockRepo) FindDisableSingleBranchAction(ctx context.Context, branchCode, userID, department string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDisableSingleBranchAction", ctx, branchCode, userID, department)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDisableSingleBranchAction indicates an expected call of FindDisableSingleBranchAction.
func (mr *MockAccountBlockRepoMockRecorder) FindDisableSingleBranchAction(ctx, branchCode, userID, department interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDisableSingleBranchAction", reflect.TypeOf((*MockAccountBlockRepo)(nil).FindDisableSingleBranchAction), ctx, branchCode, userID, department)
}

// GetBranchByCode mocks base method.
func (m *MockAccountBlockRepo) GetBranchByCode(ctx context.Context, branchCode string) (action.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBranchByCode", ctx, branchCode)
	ret0, _ := ret[0].(action.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBranchByCode indicates an expected call of GetBranchByCode.
func (mr *MockAccountBlockRepoMockRecorder) GetBranchByCode(ctx, branchCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBranchByCode", reflect.TypeOf((*MockAccountBlockRepo)(nil).GetBranchByCode), ctx, branchCode)
}

// GetCityByCode mocks base method.
func (m *MockAccountBlockRepo) GetCityByCode(ctx context.Context, cityCode string) (action.City, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCityByCode", ctx, cityCode)
	ret0, _ := ret[0].(action.City)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCityByCode indicates an expected call of GetCityByCode.
func (mr *MockAccountBlockRepoMockRecorder) GetCityByCode(ctx, cityCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCityByCode", reflect.TypeOf((*MockAccountBlockRepo)(nil).GetCityByCode), ctx, cityCode)
}

// GetDistrictByCode mocks base method.
func (m *MockAccountBlockRepo) GetDistrictByCode(ctx context.Context, districtCode string) (action.District, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistrictByCode", ctx, districtCode)
	ret0, _ := ret[0].(action.District)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistrictByCode indicates an expected call of GetDistrictByCode.
func (mr *MockAccountBlockRepoMockRecorder) GetDistrictByCode(ctx, districtCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistrictByCode", reflect.TypeOf((*MockAccountBlockRepo)(nil).GetDistrictByCode), ctx, districtCode)
}

// GetRegionByCode mocks base method.
func (m *MockAccountBlockRepo) GetRegionByCode(ctx context.Context, regionCode string) (action.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegionByCode", ctx, regionCode)
	ret0, _ := ret[0].(action.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegionByCode indicates an expected call of GetRegionByCode.
func (mr *MockAccountBlockRepoMockRecorder) GetRegionByCode(ctx, regionCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegionByCode", reflect.TypeOf((*MockAccountBlockRepo)(nil).GetRegionByCode), ctx, regionCode)
}

// GetUserByPhone mocks base method.
func (m *MockAccountBlockRepo) GetUserByPhone(ctx context.Context, phoneNumber string, maker action.CPSAction) (member.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByPhone", ctx, phoneNumber, maker)
	ret0, _ := ret[0].(member.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByPhone indicates an expected call of GetUserByPhone.
func (mr *MockAccountBlockRepoMockRecorder) GetUserByPhone(ctx, phoneNumber, maker interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByPhone", reflect.TypeOf((*MockAccountBlockRepo)(nil).GetUserByPhone), ctx, phoneNumber, maker)
}

// UpdateRegion mocks base method.
func (m *MockAccountBlockRepo) UpdateRegion(ctx context.Context, region action.Region) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRegion", ctx, region)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRegion indicates an expected call of UpdateRegion.
func (mr *MockAccountBlockRepoMockRecorder) UpdateRegion(ctx, region interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRegion", reflect.TypeOf((*MockAccountBlockRepo)(nil).UpdateRegion), ctx, region)
}
