// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/feedback/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/feedback/repository.go -destination=internal/domain/feedback/mock/repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "gitlab.com/bersufekadgetachew/cbe-super-app-cps-action/internal/domain/feedback/entity"
	utils "gitlab.com/bersufekadgetachew/cbe-super-app-cps-action/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockFeedbackRepository is a mock of FeedbackRepository interface.
type MockFeedbackRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedbackRepositoryMockRecorder
	isgomock struct{}
}

// MockFeedbackRepositoryMockRecorder is the mock recorder for MockFeedbackRepository.
type MockFeedbackRepositoryMockRecorder struct {
	mock *MockFeedbackRepository
}

// NewMockFeedbackRepository creates a new mock instance.
func NewMockFeedbackRepository(ctrl *gomock.Controller) *MockFeedbackRepository {
	mock := &MockFeedbackRepository{ctrl: ctrl}
	mock.recorder = &MockFeedbackRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedbackRepository) EXPECT() *MockFeedbackRepositoryMockRecorder {
	return m.recorder
}

// GetFeedbackByID mocks base method.
func (m *MockFeedbackRepository) GetFeedbackByID(ctx context.Context, id string) (*entity.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedbackByID", ctx, id)
	ret0, _ := ret[0].(*entity.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedbackByID indicates an expected call of GetFeedbackByID.
func (mr *MockFeedbackRepositoryMockRecorder) GetFeedbackByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedbackByID", reflect.TypeOf((*MockFeedbackRepository)(nil).GetFeedbackByID), ctx, id)
}

// GetFeedbacks mocks base method.
func (m *MockFeedbackRepository) GetFeedbacks(ctx context.Context, filterParams *utils.Filter) (*entity.FeedbackResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedbacks", ctx, filterParams)
	ret0, _ := ret[0].(*entity.FeedbackResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedbacks indicates an expected call of GetFeedbacks.
func (mr *MockFeedbackRepositoryMockRecorder) GetFeedbacks(ctx, filterParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedbacks", reflect.TypeOf((*MockFeedbackRepository)(nil).GetFeedbacks), ctx, filterParams)
}
