// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.6
// source: proto/service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tier message
type Tier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Min           uint64                 `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max           uint64                 `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	FeeAmount     uint64                 `protobuf:"varint,4,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tier) Reset() {
	*x = Tier{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tier) ProtoMessage() {}

func (x *Tier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tier.ProtoReflect.Descriptor instead.
func (*Tier) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *Tier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tier) GetMin() uint64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Tier) GetMax() uint64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Tier) GetFeeAmount() uint64 {
	if x != nil {
		return x.FeeAmount
	}
	return 0
}

// Cap message
type Cap struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	KycLevel            string                 `protobuf:"bytes,1,opt,name=kyc_level,json=kycLevel,proto3" json:"kyc_level,omitempty"`
	IndividualSingleCap uint64                 `protobuf:"varint,2,opt,name=individual_single_cap,json=individualSingleCap,proto3" json:"individual_single_cap,omitempty"`
	IndividualDailyCap  uint64                 `protobuf:"varint,3,opt,name=individual_daily_cap,json=individualDailyCap,proto3" json:"individual_daily_cap,omitempty"`
	CorporateSingleCap  uint64                 `protobuf:"varint,4,opt,name=corporate_single_cap,json=corporateSingleCap,proto3" json:"corporate_single_cap,omitempty"`
	CorporateDailyCap   uint64                 `protobuf:"varint,5,opt,name=corporate_daily_cap,json=corporateDailyCap,proto3" json:"corporate_daily_cap,omitempty"`
	MinAmount           uint64                 `protobuf:"varint,6,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Cap) Reset() {
	*x = Cap{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cap) ProtoMessage() {}

func (x *Cap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cap.ProtoReflect.Descriptor instead.
func (*Cap) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *Cap) GetKycLevel() string {
	if x != nil {
		return x.KycLevel
	}
	return ""
}

func (x *Cap) GetIndividualSingleCap() uint64 {
	if x != nil {
		return x.IndividualSingleCap
	}
	return 0
}

func (x *Cap) GetIndividualDailyCap() uint64 {
	if x != nil {
		return x.IndividualDailyCap
	}
	return 0
}

func (x *Cap) GetCorporateSingleCap() uint64 {
	if x != nil {
		return x.CorporateSingleCap
	}
	return 0
}

func (x *Cap) GetCorporateDailyCap() uint64 {
	if x != nil {
		return x.CorporateDailyCap
	}
	return 0
}

func (x *Cap) GetMinAmount() uint64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

// ProductCodes message
type ProductCodes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prd           string                 `protobuf:"bytes,1,opt,name=prd,proto3" json:"prd,omitempty"`
	Vatprd        string                 `protobuf:"bytes,2,opt,name=vatprd,proto3" json:"vatprd,omitempty"`
	Sfprd         string                 `protobuf:"bytes,3,opt,name=sfprd,proto3" json:"sfprd,omitempty"`
	Trxn          string                 `protobuf:"bytes,4,opt,name=trxn,proto3" json:"trxn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCodes) Reset() {
	*x = ProductCodes{}
	mi := &file_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCodes) ProtoMessage() {}

func (x *ProductCodes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCodes.ProtoReflect.Descriptor instead.
func (*ProductCodes) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProductCodes) GetPrd() string {
	if x != nil {
		return x.Prd
	}
	return ""
}

func (x *ProductCodes) GetVatprd() string {
	if x != nil {
		return x.Vatprd
	}
	return ""
}

func (x *ProductCodes) GetSfprd() string {
	if x != nil {
		return x.Sfprd
	}
	return ""
}

func (x *ProductCodes) GetTrxn() string {
	if x != nil {
		return x.Trxn
	}
	return ""
}

// GLEntry message
type GLEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductAccount    string                 `protobuf:"bytes,1,opt,name=product_account,json=productAccount,proto3" json:"product_account,omitempty"`
	ProductBranchCode string                 `protobuf:"bytes,2,opt,name=product_branch_code,json=productBranchCode,proto3" json:"product_branch_code,omitempty"`
	ServiceAccount    string                 `protobuf:"bytes,3,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	ServiceBranchCode string                 `protobuf:"bytes,4,opt,name=service_branch_code,json=serviceBranchCode,proto3" json:"service_branch_code,omitempty"`
	VatAccount        string                 `protobuf:"bytes,5,opt,name=vat_account,json=vatAccount,proto3" json:"vat_account,omitempty"`
	VatBranchCode     string                 `protobuf:"bytes,6,opt,name=vat_branch_code,json=vatBranchCode,proto3" json:"vat_branch_code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GLEntry) Reset() {
	*x = GLEntry{}
	mi := &file_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GLEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GLEntry) ProtoMessage() {}

func (x *GLEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GLEntry.ProtoReflect.Descriptor instead.
func (*GLEntry) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *GLEntry) GetProductAccount() string {
	if x != nil {
		return x.ProductAccount
	}
	return ""
}

func (x *GLEntry) GetProductBranchCode() string {
	if x != nil {
		return x.ProductBranchCode
	}
	return ""
}

func (x *GLEntry) GetServiceAccount() string {
	if x != nil {
		return x.ServiceAccount
	}
	return ""
}

func (x *GLEntry) GetServiceBranchCode() string {
	if x != nil {
		return x.ServiceBranchCode
	}
	return ""
}

func (x *GLEntry) GetVatAccount() string {
	if x != nil {
		return x.VatAccount
	}
	return ""
}

func (x *GLEntry) GetVatBranchCode() string {
	if x != nil {
		return x.VatBranchCode
	}
	return ""
}

// ServiceDetails message
type ServiceDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceCode     string                 `protobuf:"bytes,2,opt,name=service_code,json=serviceCode,proto3" json:"service_code,omitempty"`
	ServiceName     string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceType     string                 `protobuf:"bytes,4,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	Key             string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	AboveAmount     uint64                 `protobuf:"varint,6,opt,name=above_amount,json=aboveAmount,proto3" json:"above_amount,omitempty"`
	AboveServiceFee uint64                 `protobuf:"varint,7,opt,name=above_service_fee,json=aboveServiceFee,proto3" json:"above_service_fee,omitempty"`
	PaymentType     string                 `protobuf:"bytes,8,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	Enabled         bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	IsDeleted       bool                   `protobuf:"varint,10,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceDetails) Reset() {
	*x = ServiceDetails{}
	mi := &file_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDetails) ProtoMessage() {}

func (x *ServiceDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDetails.ProtoReflect.Descriptor instead.
func (*ServiceDetails) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceDetails) GetServiceCode() string {
	if x != nil {
		return x.ServiceCode
	}
	return ""
}

func (x *ServiceDetails) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceDetails) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *ServiceDetails) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ServiceDetails) GetAboveAmount() uint64 {
	if x != nil {
		return x.AboveAmount
	}
	return 0
}

func (x *ServiceDetails) GetAboveServiceFee() uint64 {
	if x != nil {
		return x.AboveServiceFee
	}
	return 0
}

func (x *ServiceDetails) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *ServiceDetails) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ServiceDetails) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type Docs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceDetails      `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Docs) Reset() {
	*x = Docs{}
	mi := &file_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Docs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Docs) ProtoMessage() {}

func (x *Docs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Docs.ProtoReflect.Descriptor instead.
func (*Docs) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *Docs) GetServices() []*ServiceDetails {
	if x != nil {
		return x.Services
	}
	return nil
}

type GetOneServiceDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneServiceDetailRequest) Reset() {
	*x = GetOneServiceDetailRequest{}
	mi := &file_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneServiceDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneServiceDetailRequest) ProtoMessage() {}

func (x *GetOneServiceDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneServiceDetailRequest.ProtoReflect.Descriptor instead.
func (*GetOneServiceDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetOneServiceDetailRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllServiceDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllServiceDetailsRequest) Reset() {
	*x = GetAllServiceDetailsRequest{}
	mi := &file_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllServiceDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllServiceDetailsRequest) ProtoMessage() {}

func (x *GetAllServiceDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllServiceDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetAllServiceDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllServiceDetailsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllServiceDetailsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetAllServiceDetailsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type GetServiceDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceDetails        `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceDetailResponse) Reset() {
	*x = GetServiceDetailResponse{}
	mi := &file_proto_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceDetailResponse) ProtoMessage() {}

func (x *GetServiceDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceDetailResponse.ProtoReflect.Descriptor instead.
func (*GetServiceDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetServiceDetailResponse) GetService() *ServiceDetails {
	if x != nil {
		return x.Service
	}
	return nil
}

type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalPages    int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalDocs     int32                  `protobuf:"varint,3,opt,name=total_docs,json=totalDocs,proto3" json:"total_docs,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	HasNextPage   bool                   `protobuf:"varint,5,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	HasPrevPage   bool                   `protobuf:"varint,6,opt,name=has_prev_page,json=hasPrevPage,proto3" json:"has_prev_page,omitempty"`
	NextPage      int32                  `protobuf:"varint,7,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_proto_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{9}
}

func (x *Meta) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Meta) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *Meta) GetTotalDocs() int32 {
	if x != nil {
		return x.TotalDocs
	}
	return 0
}

func (x *Meta) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Meta) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *Meta) GetHasPrevPage() bool {
	if x != nil {
		return x.HasPrevPage
	}
	return false
}

func (x *Meta) GetNextPage() int32 {
	if x != nil {
		return x.NextPage
	}
	return 0
}

type GetAllServiceDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceDetails      `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Metadata      *Meta                  `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllServiceDetailsResponse) Reset() {
	*x = GetAllServiceDetailsResponse{}
	mi := &file_proto_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllServiceDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllServiceDetailsResponse) ProtoMessage() {}

func (x *GetAllServiceDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllServiceDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetAllServiceDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllServiceDetailsResponse) GetServices() []*ServiceDetails {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *GetAllServiceDetailsResponse) GetMetadata() *Meta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\x12\aservice\"Y\n" +
	"\x04Tier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x04R\x03min\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x04R\x03max\x12\x1d\n" +
	"\n" +
	"fee_amount\x18\x04 \x01(\x04R\tfeeAmount\"\x89\x02\n" +
	"\x03Cap\x12\x1b\n" +
	"\tkyc_level\x18\x01 \x01(\tR\bkycLevel\x122\n" +
	"\x15individual_single_cap\x18\x02 \x01(\x04R\x13individualSingleCap\x120\n" +
	"\x14individual_daily_cap\x18\x03 \x01(\x04R\x12individualDailyCap\x120\n" +
	"\x14corporate_single_cap\x18\x04 \x01(\x04R\x12corporateSingleCap\x12.\n" +
	"\x13corporate_daily_cap\x18\x05 \x01(\x04R\x11corporateDailyCap\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x06 \x01(\x04R\tminAmount\"b\n" +
	"\fProductCodes\x12\x10\n" +
	"\x03prd\x18\x01 \x01(\tR\x03prd\x12\x16\n" +
	"\x06vatprd\x18\x02 \x01(\tR\x06vatprd\x12\x14\n" +
	"\x05sfprd\x18\x03 \x01(\tR\x05sfprd\x12\x12\n" +
	"\x04trxn\x18\x04 \x01(\tR\x04trxn\"\x84\x02\n" +
	"\aGLEntry\x12'\n" +
	"\x0fproduct_account\x18\x01 \x01(\tR\x0eproductAccount\x12.\n" +
	"\x13product_branch_code\x18\x02 \x01(\tR\x11productBranchCode\x12'\n" +
	"\x0fservice_account\x18\x03 \x01(\tR\x0eserviceAccount\x12.\n" +
	"\x13service_branch_code\x18\x04 \x01(\tR\x11serviceBranchCode\x12\x1f\n" +
	"\vvat_account\x18\x05 \x01(\tR\n" +
	"vatAccount\x12&\n" +
	"\x0fvat_branch_code\x18\x06 \x01(\tR\rvatBranchCode\"\xc6\x02\n" +
	"\x0eServiceDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fservice_code\x18\x02 \x01(\tR\vserviceCode\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12!\n" +
	"\fservice_type\x18\x04 \x01(\tR\vserviceType\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\x12!\n" +
	"\fabove_amount\x18\x06 \x01(\x04R\vaboveAmount\x12*\n" +
	"\x11above_service_fee\x18\a \x01(\x04R\x0faboveServiceFee\x12!\n" +
	"\fpayment_type\x18\b \x01(\tR\vpaymentType\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\n" +
	" \x01(\bR\tisDeleted\";\n" +
	"\x04docs\x123\n" +
	"\bservices\x18\x01 \x03(\v2\x17.service.ServiceDetailsR\bservices\",\n" +
	"\x1aGetOneServiceDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"d\n" +
	"\x1bGetAllServiceDetailsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"M\n" +
	"\x18GetServiceDetailResponse\x121\n" +
	"\aservice\x18\x01 \x01(\v2\x17.service.ServiceDetailsR\aservice\"\xd5\x01\n" +
	"\x04Meta\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12\x1d\n" +
	"\n" +
	"total_docs\x18\x03 \x01(\x05R\ttotalDocs\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\"\n" +
	"\rhas_next_page\x18\x05 \x01(\bR\vhasNextPage\x12\"\n" +
	"\rhas_prev_page\x18\x06 \x01(\bR\vhasPrevPage\x12\x1b\n" +
	"\tnext_page\x18\a \x01(\x05R\bnextPage\"~\n" +
	"\x1cGetAllServiceDetailsResponse\x123\n" +
	"\bservices\x18\x01 \x03(\v2\x17.service.ServiceDetailsR\bservices\x12)\n" +
	"\bmetadata\x18\x02 \x01(\v2\r.service.MetaR\bmetadata2\xd5\x01\n" +
	"\x15ServiceDetailsService\x12]\n" +
	"\x13GetOneServiceDetail\x12#.service.GetOneServiceDetailRequest\x1a!.service.GetServiceDetailResponse\x12]\n" +
	"\x0eGetAllServices\x12$.service.GetAllServiceDetailsRequest\x1a%.service.GetAllServiceDetailsResponseBFZDgithub.com/cbesuperapp/cbe-super-app-cps-action/grpc/service;serviceb\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_service_proto_goTypes = []any{
	(*Tier)(nil),                         // 0: service.Tier
	(*Cap)(nil),                          // 1: service.Cap
	(*ProductCodes)(nil),                 // 2: service.ProductCodes
	(*GLEntry)(nil),                      // 3: service.GLEntry
	(*ServiceDetails)(nil),               // 4: service.ServiceDetails
	(*Docs)(nil),                         // 5: service.docs
	(*GetOneServiceDetailRequest)(nil),   // 6: service.GetOneServiceDetailRequest
	(*GetAllServiceDetailsRequest)(nil),  // 7: service.GetAllServiceDetailsRequest
	(*GetServiceDetailResponse)(nil),     // 8: service.GetServiceDetailResponse
	(*Meta)(nil),                         // 9: service.Meta
	(*GetAllServiceDetailsResponse)(nil), // 10: service.GetAllServiceDetailsResponse
}
var file_proto_service_proto_depIdxs = []int32{
	4,  // 0: service.docs.services:type_name -> service.ServiceDetails
	4,  // 1: service.GetServiceDetailResponse.service:type_name -> service.ServiceDetails
	4,  // 2: service.GetAllServiceDetailsResponse.services:type_name -> service.ServiceDetails
	9,  // 3: service.GetAllServiceDetailsResponse.metadata:type_name -> service.Meta
	6,  // 4: service.ServiceDetailsService.GetOneServiceDetail:input_type -> service.GetOneServiceDetailRequest
	7,  // 5: service.ServiceDetailsService.GetAllServices:input_type -> service.GetAllServiceDetailsRequest
	8,  // 6: service.ServiceDetailsService.GetOneServiceDetail:output_type -> service.GetServiceDetailResponse
	10, // 7: service.ServiceDetailsService.GetAllServices:output_type -> service.GetAllServiceDetailsResponse
	6,  // [6:8] is the sub-list for method output_type
	4,  // [4:6] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
