// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceDetailsService_GetOneServiceDetail_FullMethodName = "/service.ServiceDetailsService/GetOneServiceDetail"
	ServiceDetailsService_GetAllServices_FullMethodName      = "/service.ServiceDetailsService/GetAllServices"
)

// ServiceDetailsServiceClient is the client API for ServiceDetailsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceDetailsServiceClient interface {
	GetOneServiceDetail(ctx context.Context, in *GetOneServiceDetailRequest, opts ...grpc.CallOption) (*GetServiceDetailResponse, error)
	GetAllServices(ctx context.Context, in *GetAllServiceDetailsRequest, opts ...grpc.CallOption) (*GetAllServiceDetailsResponse, error)
}

type serviceDetailsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceDetailsServiceClient(cc grpc.ClientConnInterface) ServiceDetailsServiceClient {
	return &serviceDetailsServiceClient{cc}
}

func (c *serviceDetailsServiceClient) GetOneServiceDetail(ctx context.Context, in *GetOneServiceDetailRequest, opts ...grpc.CallOption) (*GetServiceDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceDetailResponse)
	err := c.cc.Invoke(ctx, ServiceDetailsService_GetOneServiceDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceDetailsServiceClient) GetAllServices(ctx context.Context, in *GetAllServiceDetailsRequest, opts ...grpc.CallOption) (*GetAllServiceDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllServiceDetailsResponse)
	err := c.cc.Invoke(ctx, ServiceDetailsService_GetAllServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceDetailsServiceServer is the server API for ServiceDetailsService service.
// All implementations must embed UnimplementedServiceDetailsServiceServer
// for forward compatibility.
type ServiceDetailsServiceServer interface {
	GetOneServiceDetail(context.Context, *GetOneServiceDetailRequest) (*GetServiceDetailResponse, error)
	GetAllServices(context.Context, *GetAllServiceDetailsRequest) (*GetAllServiceDetailsResponse, error)
	mustEmbedUnimplementedServiceDetailsServiceServer()
}

// UnimplementedServiceDetailsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceDetailsServiceServer struct{}

func (UnimplementedServiceDetailsServiceServer) GetOneServiceDetail(context.Context, *GetOneServiceDetailRequest) (*GetServiceDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOneServiceDetail not implemented")
}
func (UnimplementedServiceDetailsServiceServer) GetAllServices(context.Context, *GetAllServiceDetailsRequest) (*GetAllServiceDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllServices not implemented")
}
func (UnimplementedServiceDetailsServiceServer) mustEmbedUnimplementedServiceDetailsServiceServer() {}
func (UnimplementedServiceDetailsServiceServer) testEmbeddedByValue()                               {}

// UnsafeServiceDetailsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceDetailsServiceServer will
// result in compilation errors.
type UnsafeServiceDetailsServiceServer interface {
	mustEmbedUnimplementedServiceDetailsServiceServer()
}

func RegisterServiceDetailsServiceServer(s grpc.ServiceRegistrar, srv ServiceDetailsServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceDetailsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceDetailsService_ServiceDesc, srv)
}

func _ServiceDetailsService_GetOneServiceDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneServiceDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceDetailsServiceServer).GetOneServiceDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceDetailsService_GetOneServiceDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceDetailsServiceServer).GetOneServiceDetail(ctx, req.(*GetOneServiceDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceDetailsService_GetAllServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllServiceDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceDetailsServiceServer).GetAllServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceDetailsService_GetAllServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceDetailsServiceServer).GetAllServices(ctx, req.(*GetAllServiceDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceDetailsService_ServiceDesc is the grpc.ServiceDesc for ServiceDetailsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceDetailsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.ServiceDetailsService",
	HandlerType: (*ServiceDetailsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOneServiceDetail",
			Handler:    _ServiceDetailsService_GetOneServiceDetail_Handler,
		},
		{
			MethodName: "GetAllServices",
			Handler:    _ServiceDetailsService_GetAllServices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
