// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/miniapp/repository.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	a "cbe-super-app-cps-action/internal/domain/action"
	action "cbe-super-app-cps-action/internal/domain/action"
	miniapp "cbe-super-app-cps-action/internal/domain/miniapp"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateMiniApp mocks base method.
func (m *MockRepository) CreateMiniApp(ctx context.Context, miniapp miniapp.MiniApp) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMiniApp", ctx, miniapp)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMiniApp indicates an expected call of CreateMiniApp.
func (mr *MockRepositoryMockRecorder) CreateMiniApp(ctx, miniapp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMiniApp", reflect.TypeOf((*MockRepository)(nil).CreateMiniApp), ctx, miniapp)
}

// CreateMiniAppAction mocks base method.
func (m *MockRepository) CreateMiniAppAction(ctx context.Context, action action.CPSAction) (action.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMiniAppAction", ctx, action)
	ret0, _ := ret[0].(a.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMiniAppAction indicates an expected call of CreateMiniAppAction.
func (mr *MockRepositoryMockRecorder) CreateMiniAppAction(ctx, action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMiniAppAction", reflect.TypeOf((*MockRepository)(nil).CreateMiniAppAction), ctx, action)
}

// GetMiniAppActionId mocks base method.
func (m *MockRepository) GetMiniAppActionId(ctx context.Context, action_id string) (action.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMiniAppActionId", ctx, action_id)
	ret0, _ := ret[0].(action.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMiniAppActionId indicates an expected call of GetMiniAppActionId.
func (mr *MockRepositoryMockRecorder) GetMiniAppActionId(ctx, action_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMiniAppActionId", reflect.TypeOf((*MockRepository)(nil).GetMiniAppActionId), ctx, action_id)
}

// UpdateCpsAction mocks base method.
func (m *MockRepository) UpdateCpsAction(ctx context.Context, action action.CPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCpsAction", ctx, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCpsAction indicates an expected call of UpdateCpsAction.
func (mr *MockRepositoryMockRecorder) UpdateCpsAction(ctx, action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCpsAction", reflect.TypeOf((*MockRepository)(nil).UpdateCpsAction), ctx, action)
}
