// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/topup.proto

package topup

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TopupService_GetAllTopup_FullMethodName = "/topup.TopupService/GetAllTopup"
)

// TopupServiceClient is the client API for TopupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TopupServiceClient interface {
	GetAllTopup(ctx context.Context, in *TopupRequest, opts ...grpc.CallOption) (*TopupResponse, error)
}

type topupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTopupServiceClient(cc grpc.ClientConnInterface) TopupServiceClient {
	return &topupServiceClient{cc}
}

func (c *topupServiceClient) GetAllTopup(ctx context.Context, in *TopupRequest, opts ...grpc.CallOption) (*TopupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopupResponse)
	err := c.cc.Invoke(ctx, TopupService_GetAllTopup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopupServiceServer is the server API for TopupService service.
// All implementations must embed UnimplementedTopupServiceServer
// for forward compatibility.
type TopupServiceServer interface {
	GetAllTopup(context.Context, *TopupRequest) (*TopupResponse, error)
	mustEmbedUnimplementedTopupServiceServer()
}

// UnimplementedTopupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTopupServiceServer struct{}

func (UnimplementedTopupServiceServer) GetAllTopup(context.Context, *TopupRequest) (*TopupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllTopup not implemented")
}
func (UnimplementedTopupServiceServer) mustEmbedUnimplementedTopupServiceServer() {}
func (UnimplementedTopupServiceServer) testEmbeddedByValue()                      {}

// UnsafeTopupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TopupServiceServer will
// result in compilation errors.
type UnsafeTopupServiceServer interface {
	mustEmbedUnimplementedTopupServiceServer()
}

func RegisterTopupServiceServer(s grpc.ServiceRegistrar, srv TopupServiceServer) {
	// If the following call panics, it indicates UnimplementedTopupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TopupService_ServiceDesc, srv)
}

func _TopupService_GetAllTopup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopupServiceServer).GetAllTopup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopupService_GetAllTopup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopupServiceServer).GetAllTopup(ctx, req.(*TopupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TopupService_ServiceDesc is the grpc.ServiceDesc for TopupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TopupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "topup.TopupService",
	HandlerType: (*TopupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllTopup",
			Handler:    _TopupService_GetAllTopup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/topup.proto",
}
