// Package utils err_msg centralizes error code constants to avoid typos and duplication.
package utils

const (
	// General
	ConflictKey                  = "CONFLICT_KEY"
	InvalidID                    = "INVALID_ID"
	InvalidJSONPayload           = "INVALID_JSON_PAYLOAD"
	UnhandledServerError         = "UNHANDLED_SERVER_ERROR"
	InvalidTokenFormat           = "INVALID_TOKEN_FORMAT"
	InvalidToken                 = "INVALID_TOKEN"
	ExpiredToken                 = "EXPIRED_TOKEN"
	ErrorChangingPin             = "ERROR_CHANGING_PIN"
	EncryptedPayloadRequired     = "ENCRYPTED_PAYLOAD_REQUIRED"
	InvalidServerConfiguration   = "INVALID_SERVER_CONFIGURATION"
	AuthHeaderMissing            = "AUTH_HEADER_MISSING"
	InvalidKeyConfiguration      = "INVALID_KEY_CONFIGURATION"
	InvalidEncryptedPayload      = "INVALID_ENCRYPTED_PAYLOAD"
	DecryptionError              = "DECRYPTION_ERROR"
	ServerKeysNotConfigured      = "SERVER_KEYS_NOT_CONFIGURED"
	InvalidInput                 = "INVALID_INPUT"
	Unauthorized                 = "UNAUTHORIZED"
	UserRealmNotFound            = "USER_REALM_NOT_FOUND"
	ActionNotAllowed             = "ACTION_NOT_ALLOWED"
	WaitForPreviousOtpExpiration = "WAIT_FOR_PREVIOUS_OTP_EXPIRATION"
	EmptyOrg                     = "EMPTY_ORG"
	InvalidReq                   = "INVALID_REQ"
	RegFrst                      = "REG_FRST"
	WeakPin                      = "WEAK_PIN"
	NotFound                     = "NOT_FOUND"
	DeviceIDRequired             = "DEVICE_ID_REQUIRED"
	NoLinkedDevices              = "NO_LINKED_DEVICES"
	CouldNotUnlinkDevice         = "COULD_NOT_UNLINK_DEVICE"
	IncompleteUserInfo           = "INCOMPLETE_USER_INFO"
	InvalidActionType            = "INVALID_ACTION_TYPE"
	ActionNotFound               = "ACTION_NOT_FOUND"
	PendingRequestExists         = "PENDING_REQUEST_EXISTS"
	InvalidActionData            = "INVALID_ACTION_DATA"
	GeneralDBQueryFailed         = "GENERAL_DB_QUERY_FAILED"

	// Auth
	AuthUserNotFound              = "AUTH_USER_NOT_FOUND"
	AuthUserDisabled              = "AUTH_USER_DISABLED"
	AuthInvalidPassword           = "AUTH_INVALID_PASSWORD"
	AuthUserHasNoPassword         = "AUTH_USER_HAS_NO_PASSWORD"
	AuthTooManyAttempts           = "AUTH_TOO_MANY_ATTEMPTS"
	AuthInvalidOtp                = "AUTH_INVALID_OTP"
	AuthExpiredOtp                = "AUTH_EXPIRED_OTP"
	AuthUserResetPasswordRequired = "AUTH_USER_RESET_PASSWORD_REQUIRED"
	AuthUserAlreadyExists         = "AUTH_USER_ALREADY_EXISTS"
	LoginProhibitedFor15Min       = "LOGIN_PROHIBITED_FOR_15_MIN"
	IncorrectPassword             = "INCORRECT_PASSWORD"
	OldPasswordSameAsNew          = "OLD_PASSWORD_SAME_AS_NEW"
	PinOnlyDigit                  = "PIN_OLY_DIG"
	PinLimit                      = "PIN_LIMIT"
	PinRedundant                  = "PIN_REDANDANT"
	PinSeq                        = "PIN_SEQ"
	FailedToGenToken              = "FAILD_TO_GEN_TOKEN"
	FailedToResetPass             = "FAILD_TO_RESET_PASS"
	FailedValidation              = "FAILD_VALIDATION"
	OldPinMismatch                = "OLD_PIN_MISMATCH"
	SamePin                       = "SAME_PIN"
	PinInHistory                  = "PIN_IN_HISTORY"
	InvalidBearer                 = "INVALID_BEARER"
	UseRightAuth                  = "USE_RIGHT_AUTH"
	InvalidClaim                  = "INVALID_CLAIM"
	InvalidTokenData              = "INVALID_TOKEN_DATA"
	UnableToDecryptToken          = "UNABLE_TO_DYCRYPT_TOKEN"
	FailedLogin                   = "FAILED_LOGIN"
	AccountLocked                 = "ACCOUNT_LOCKED"

	// Transaction
	TransactionNotFound = "TRANSACTION_NOT_FOUND"
	InsufficientFunds   = "INSUFFICIENT_FUNDS"
	CommissionNotFound  = "COMMISSION_NOT_FOUND"
	CustomerNotFound    = "CUSTOMER_NOT_FOUND"

	// Account
	PhoneLookupFailed          = "PHONE_LOOKUP_FAILED"
	APIRequestFailed           = "API_REQUEST_FAILED"
	AccountNotFound            = "ACCOUNT_NOT_FOUND"
	UserPhoneExists            = "USER_PHONE_EXISTS"
	GeneralSifGenerationFailed = "GENERAL_SIF_GENERATION_FAILED"
	GeneralDBUpdateFailed      = "GENERAL_DB_UPDATE_FAILED"
	GeneralDBInsertFailed      = "GENERAL_DB_INSERT_FAILED"
	CoreAccountNotFound        = "CORE_ACCOUNT_NOT_FOUND"
	CoreAccountTypeError       = "CORE_ACCOUNT_TYPE_ERROR"
	AccountLookupFailed        = "ACCOUNT_LOOKUP_FAILED"
	AccountDetailFailed        = "ACCOUNT_DETAIL_FAILED"
	InvalidCoreResponse        = "INVALID_CORE_RESPONSE"
	AccountUpdateFailed        = "ACCOUNT_UPDATE_FAILED"

	// OTP
	InvalidOtp          = "INVALID_OTP"
	ExpiredOtp          = "EXPIRED_OTP"
	EmailInUse          = "EMAIL_IN_USE"
	UserAlreadyHasEmail = "USER_ALREADY_HAS_EMAIL"
	OtpGenerationFailed = "OTP_GENERATION_FAILED"
	UserKycLevelZero    = "USER_KYC_LEVEL_ZERO"
	UserKycLevelWrong   = "USER_KYC_LEVEL_WRONG"

	// File
	InvalidForm          = "INVALID_FORM"
	NoFile               = "NO_FILE"
	FileTooLarge         = "FILE_TOO_LARGE"
	InvalidFileType      = "INVALID_FILE_TYPE"
	UploadFailed         = "UPLOAD_FAILED"
	MissingOrInvalidLogo = "MISSING_OR_INVALID_LOGO"

	// Branch
	BranchNotFound        = "BRANCH_NOT_FOUND"
	BranchDisabled        = "BRANCH_DISABLED"
	FailedToFetchBranches = "FAILED_TO_FETCH_BRANCHES"
	InvalidBranchID       = "INVALID_BRANCH_ID"
	InvalidLocationFilter = "INVALID_LOCATION_FILTER"
	BranchIDRequired      = "BRANCH_ID_REQUIRED"

	// Department
	DepartmentNotFound      = "DEPARTMENT_NOT_FOUND"
	DepartmentAlreadyExists = "DEPARTMENT_ALREADY_EXISTS"
	DepartmentCodeRequired  = "DEPARTMENT_CODE_REQUIRED"
	DepartmentNameRequired  = "DEPARTMENT_NAME_REQUIRED"
	PortalCardsInvalid      = "PORTAL_CARDS_INVALID"

	// Bank
	BankNotFound    = "BANKS_NOT_FOUND"
	MissingBankName = "MISSING_BANK_NAME"
	InvalidBankName = "INVALID_BANK_NAME"
	MissingBankCode = "MISSING_BANK_CODE"
	MissingBankBIC  = "MISSING_BANK_BIC"

	// Action
	InvalidDecison               = "INVALID_DECISION"
	ActionRejectionFailed        = "ACTION_REJECTION_FAILED"
	ActionApprovalFailed         = "ACTION_APPROVAL_FAILED"
	UnlinkActionFailed           = "UNLINK_ACTION_REQUEST_FAILED"
	PendingActionRejectionFailed = "PENDING_ACTION_REJECTION_FAILED"
	PendingActionCheckFailed     = "PENDING_ACTION_CHECK_FAILED"
	PendingCPSActionExists       = "PENDING_CPS_ACTION_EXISTS"

	// User
	UserStatusUpdateFailed = "USER_STATUS_UPDATE_FAILED"
)
