// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/port/outbound/mini_app/outbound.go

// Package mock_outbound is a generated GoMock package.
package mock_outbound

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	a "cbe-super-app-cps-action/internal/domain/action"
	action "cbe-super-app-cps-action/internal/domain/action"
	miniapp "cbe-super-app-cps-action/internal/domain/miniapp"
)

// MockOutbound is a mock of Outbound interface.
type MockOutbound struct {
	ctrl     *gomock.Controller
	recorder *MockOutboundMockRecorder
}

// MockOutboundMockRecorder is the mock recorder for MockOutbound.
type MockOutboundMockRecorder struct {
	mock *MockOutbound
}

// NewMockOutbound creates a new mock instance.
func NewMockOutbound(ctrl *gomock.Controller) *MockOutbound {
	mock := &MockOutbound{ctrl: ctrl}
	mock.recorder = &MockOutboundMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutbound) EXPECT() *MockOutboundMockRecorder {
	return m.recorder
}

// CreateMiniApp mocks base method.
func (m *MockOutbound) CreateMiniApp(ctx context.Context, miniapp miniapp.MiniApp) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMiniApp", ctx, miniapp)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMiniApp indicates an expected call of CreateMiniApp.
func (mr *MockOutboundMockRecorder) CreateMiniApp(ctx, miniapp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMiniApp", reflect.TypeOf((*MockOutbound)(nil).CreateMiniApp), ctx, miniapp)
}

// CreateMiniAppAction mocks base method.
func (m *MockOutbound) CreateMiniAppAction(ctx context.Context, action action.CPSAction) (action.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMiniAppAction", ctx, action)
	ret0, _ := ret[0].(a.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMiniAppAction indicates an expected call of CreateMiniAppAction.
func (mr *MockOutboundMockRecorder) CreateMiniAppAction(ctx, action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMiniAppAction", reflect.TypeOf((*MockOutbound)(nil).CreateMiniAppAction), ctx, action)
}

// GetMiniAppActionId mocks base method.
func (m *MockOutbound) GetMiniAppActionId(ctx context.Context, action_id string) (action.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMiniAppActionId", ctx, action_id)
	ret0, _ := ret[0].(action.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMiniAppActionId indicates an expected call of GetMiniAppActionId.
func (mr *MockOutboundMockRecorder) GetMiniAppActionId(ctx, action_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMiniAppActionId", reflect.TypeOf((*MockOutbound)(nil).GetMiniAppActionId), ctx, action_id)
}

// UpdateCpsAction mocks base method.
func (m *MockOutbound) UpdateCpsAction(ctx context.Context, action action.CPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCpsAction", ctx, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCpsAction indicates an expected call of UpdateCpsAction.
func (mr *MockOutboundMockRecorder) UpdateCpsAction(ctx, action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCpsAction", reflect.TypeOf((*MockOutbound)(nil).UpdateCpsAction), ctx, action)
}
