// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: wallet.proto

package grpcwallet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Wallet struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UniqueCode       string                 `protobuf:"bytes,3,opt,name=unique_code,json=uniqueCode,proto3" json:"unique_code,omitempty"`
	Avatar           string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Enabled          bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	IsDeleted        bool                   `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	Services         *Services              `protobuf:"bytes,7,opt,name=services,proto3" json:"services,omitempty"`
	ServiceCode      string                 `protobuf:"bytes,8,opt,name=service_code,json=serviceCode,proto3" json:"service_code,omitempty"`
	ServiceKey       string                 `protobuf:"bytes,9,opt,name=service_key,json=serviceKey,proto3" json:"service_key,omitempty"`
	ServiceId        string                 `protobuf:"bytes,10,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ChildServiceKeys []*ChildServiceKey     `protobuf:"bytes,11,rep,name=child_service_keys,json=childServiceKeys,proto3" json:"child_service_keys,omitempty"`
	Cap              []*Cap                 `protobuf:"bytes,12,rep,name=cap,proto3" json:"cap,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *Wallet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wallet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Wallet) GetUniqueCode() string {
	if x != nil {
		return x.UniqueCode
	}
	return ""
}

func (x *Wallet) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Wallet) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Wallet) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Wallet) GetServices() *Services {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Wallet) GetServiceCode() string {
	if x != nil {
		return x.ServiceCode
	}
	return ""
}

func (x *Wallet) GetServiceKey() string {
	if x != nil {
		return x.ServiceKey
	}
	return ""
}

func (x *Wallet) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Wallet) GetChildServiceKeys() []*ChildServiceKey {
	if x != nil {
		return x.ChildServiceKeys
	}
	return nil
}

func (x *Wallet) GetCap() []*Cap {
	if x != nil {
		return x.Cap
	}
	return nil
}

type ChildServiceKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceKey    string                 `protobuf:"bytes,1,opt,name=service_key,json=serviceKey,proto3" json:"service_key,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildServiceKey) Reset() {
	*x = ChildServiceKey{}
	mi := &file_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildServiceKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildServiceKey) ProtoMessage() {}

func (x *ChildServiceKey) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildServiceKey.ProtoReflect.Descriptor instead.
func (*ChildServiceKey) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *ChildServiceKey) GetServiceKey() string {
	if x != nil {
		return x.ServiceKey
	}
	return ""
}

func (x *ChildServiceKey) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type Services struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Self          bool                   `protobuf:"varint,1,opt,name=self,proto3" json:"self,omitempty"`
	Other         bool                   `protobuf:"varint,2,opt,name=other,proto3" json:"other,omitempty"`
	Agent         bool                   `protobuf:"varint,3,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Services) Reset() {
	*x = Services{}
	mi := &file_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Services) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Services) ProtoMessage() {}

func (x *Services) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Services.ProtoReflect.Descriptor instead.
func (*Services) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *Services) GetSelf() bool {
	if x != nil {
		return x.Self
	}
	return false
}

func (x *Services) GetOther() bool {
	if x != nil {
		return x.Other
	}
	return false
}

func (x *Services) GetAgent() bool {
	if x != nil {
		return x.Agent
	}
	return false
}

type Cap struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SingleCap          string                 `protobuf:"bytes,1,opt,name=single_cap,json=singleCap,proto3" json:"single_cap,omitempty"`
	MinimumTransferCap string                 `protobuf:"bytes,2,opt,name=minimum_transfer_cap,json=minimumTransferCap,proto3" json:"minimum_transfer_cap,omitempty"`
	Currency           string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Cap) Reset() {
	*x = Cap{}
	mi := &file_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cap) ProtoMessage() {}

func (x *Cap) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cap.ProtoReflect.Descriptor instead.
func (*Cap) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *Cap) GetSingleCap() string {
	if x != nil {
		return x.SingleCap
	}
	return ""
}

func (x *Cap) GetMinimumTransferCap() string {
	if x != nil {
		return x.MinimumTransferCap
	}
	return ""
}

func (x *Cap) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Docs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallets       []*Wallet              `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Docs) Reset() {
	*x = Docs{}
	mi := &file_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Docs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Docs) ProtoMessage() {}

func (x *Docs) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Docs.ProtoReflect.Descriptor instead.
func (*Docs) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *Docs) GetWallets() []*Wallet {
	if x != nil {
		return x.Wallets
	}
	return nil
}

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *GetWalletRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllWalletRequest) Reset() {
	*x = GetAllWalletRequest{}
	mi := &file_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllWalletRequest) ProtoMessage() {}

func (x *GetAllWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllWalletRequest.ProtoReflect.Descriptor instead.
func (*GetAllWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllWalletRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllWalletRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetAllWalletRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type GetWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *Wallet                `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResponse) Reset() {
	*x = GetWalletResponse{}
	mi := &file_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResponse) ProtoMessage() {}

func (x *GetWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResponse.ProtoReflect.Descriptor instead.
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *GetWalletResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalPages    int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalDocs     int32                  `protobuf:"varint,3,opt,name=total_docs,json=totalDocs,proto3" json:"total_docs,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	HasNextPage   bool                   `protobuf:"varint,5,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	HasPrevPage   bool                   `protobuf:"varint,6,opt,name=has_prev_page,json=hasPrevPage,proto3" json:"has_prev_page,omitempty"`
	NextPage      int32                  `protobuf:"varint,7,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *Meta) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Meta) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *Meta) GetTotalDocs() int32 {
	if x != nil {
		return x.TotalDocs
	}
	return 0
}

func (x *Meta) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Meta) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *Meta) GetHasPrevPage() bool {
	if x != nil {
		return x.HasPrevPage
	}
	return false
}

func (x *Meta) GetNextPage() int32 {
	if x != nil {
		return x.NextPage
	}
	return 0
}

type GetAllWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallets       []*Wallet              `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
	Metadata      *Meta                  `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllWalletResponse) Reset() {
	*x = GetAllWalletResponse{}
	mi := &file_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllWalletResponse) ProtoMessage() {}

func (x *GetAllWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllWalletResponse.ProtoReflect.Descriptor instead.
func (*GetAllWalletResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllWalletResponse) GetWallets() []*Wallet {
	if x != nil {
		return x.Wallets
	}
	return nil
}

func (x *GetAllWalletResponse) GetMetadata() *Meta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_wallet_proto protoreflect.FileDescriptor

const file_wallet_proto_rawDesc = "" +
	"\n" +
	"\fwallet.proto\x12\x06wallet\"\x95\x03\n" +
	"\x06Wallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vunique_code\x18\x03 \x01(\tR\n" +
	"uniqueCode\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x06 \x01(\bR\tisDeleted\x12,\n" +
	"\bservices\x18\a \x01(\v2\x10.wallet.ServicesR\bservices\x12!\n" +
	"\fservice_code\x18\b \x01(\tR\vserviceCode\x12\x1f\n" +
	"\vservice_key\x18\t \x01(\tR\n" +
	"serviceKey\x12\x1d\n" +
	"\n" +
	"service_id\x18\n" +
	" \x01(\tR\tserviceId\x12E\n" +
	"\x12child_service_keys\x18\v \x03(\v2\x17.wallet.ChildServiceKeyR\x10childServiceKeys\x12\x1d\n" +
	"\x03cap\x18\f \x03(\v2\v.wallet.CapR\x03cap\"U\n" +
	"\x0fChildServiceKey\x12\x1f\n" +
	"\vservice_key\x18\x01 \x01(\tR\n" +
	"serviceKey\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\"J\n" +
	"\bServices\x12\x12\n" +
	"\x04self\x18\x01 \x01(\bR\x04self\x12\x14\n" +
	"\x05other\x18\x02 \x01(\bR\x05other\x12\x14\n" +
	"\x05agent\x18\x03 \x01(\bR\x05agent\"r\n" +
	"\x03Cap\x12\x1d\n" +
	"\n" +
	"single_cap\x18\x01 \x01(\tR\tsingleCap\x120\n" +
	"\x14minimum_transfer_cap\x18\x02 \x01(\tR\x12minimumTransferCap\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"0\n" +
	"\x04docs\x12(\n" +
	"\awallets\x18\x01 \x03(\v2\x0e.wallet.WalletR\awallets\"\"\n" +
	"\x10GetWalletRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\\\n" +
	"\x13GetAllWalletRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\";\n" +
	"\x11GetWalletResponse\x12&\n" +
	"\x06wallet\x18\x01 \x01(\v2\x0e.wallet.WalletR\x06wallet\"\xd5\x01\n" +
	"\x04Meta\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12\x1d\n" +
	"\n" +
	"total_docs\x18\x03 \x01(\x05R\ttotalDocs\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\"\n" +
	"\rhas_next_page\x18\x05 \x01(\bR\vhasNextPage\x12\"\n" +
	"\rhas_prev_page\x18\x06 \x01(\bR\vhasPrevPage\x12\x1b\n" +
	"\tnext_page\x18\a \x01(\x05R\bnextPage\"j\n" +
	"\x14GetAllWalletResponse\x12(\n" +
	"\awallets\x18\x01 \x03(\v2\x0e.wallet.WalletR\awallets\x12(\n" +
	"\bmetadata\x18\x02 \x01(\v2\f.wallet.MetaR\bmetadata2\x9c\x01\n" +
	"\rWalletService\x12@\n" +
	"\tGetWallet\x12\x18.wallet.GetWalletRequest\x1a\x19.wallet.GetWalletResponse\x12I\n" +
	"\fGetAllWallet\x12\x1b.wallet.GetAllWalletRequest\x1a\x1c.wallet.GetAllWalletResponseBHZFgithub.com/cbesuperapp/cbe-super-app-cps-action/grpc/wallet;grpcwalletb\x06proto3"

var (
	file_wallet_proto_rawDescOnce sync.Once
	file_wallet_proto_rawDescData []byte
)

func file_wallet_proto_rawDescGZIP() []byte {
	file_wallet_proto_rawDescOnce.Do(func() {
		file_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)))
	})
	return file_wallet_proto_rawDescData
}

var file_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_wallet_proto_goTypes = []any{
	(*Wallet)(nil),               // 0: wallet.Wallet
	(*ChildServiceKey)(nil),      // 1: wallet.ChildServiceKey
	(*Services)(nil),             // 2: wallet.Services
	(*Cap)(nil),                  // 3: wallet.Cap
	(*Docs)(nil),                 // 4: wallet.docs
	(*GetWalletRequest)(nil),     // 5: wallet.GetWalletRequest
	(*GetAllWalletRequest)(nil),  // 6: wallet.GetAllWalletRequest
	(*GetWalletResponse)(nil),    // 7: wallet.GetWalletResponse
	(*Meta)(nil),                 // 8: wallet.Meta
	(*GetAllWalletResponse)(nil), // 9: wallet.GetAllWalletResponse
}
var file_wallet_proto_depIdxs = []int32{
	2, // 0: wallet.Wallet.services:type_name -> wallet.Services
	1, // 1: wallet.Wallet.child_service_keys:type_name -> wallet.ChildServiceKey
	3, // 2: wallet.Wallet.cap:type_name -> wallet.Cap
	0, // 3: wallet.docs.wallets:type_name -> wallet.Wallet
	0, // 4: wallet.GetWalletResponse.wallet:type_name -> wallet.Wallet
	0, // 5: wallet.GetAllWalletResponse.wallets:type_name -> wallet.Wallet
	8, // 6: wallet.GetAllWalletResponse.metadata:type_name -> wallet.Meta
	5, // 7: wallet.WalletService.GetWallet:input_type -> wallet.GetWalletRequest
	6, // 8: wallet.WalletService.GetAllWallet:input_type -> wallet.GetAllWalletRequest
	7, // 9: wallet.WalletService.GetWallet:output_type -> wallet.GetWalletResponse
	9, // 10: wallet.WalletService.GetAllWallet:output_type -> wallet.GetAllWalletResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_wallet_proto_init() }
func file_wallet_proto_init() {
	if File_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_proto_goTypes,
		DependencyIndexes: file_wallet_proto_depIdxs,
		MessageInfos:      file_wallet_proto_msgTypes,
	}.Build()
	File_wallet_proto = out.File
	file_wallet_proto_goTypes = nil
	file_wallet_proto_depIdxs = nil
}
