// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/customer/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/customer/repository/repository.go -destination=internal/domain/customer/mocks/repository_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "gitlab.com/bersufekadgetachew/cbe-super-app-cps-ms/internal/domain/customer/entity"
	utils "gitlab.com/bersufekadgetachew/cbe-super-app-cps-ms/utils"
	member "gitlab.com/bersufekadgetachew/cbe-super-app-shared/shared/entities/member"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomerRepository is a mock of CustomerRepository interface.
type MockCustomerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomerRepositoryMockRecorder is the mock recorder for MockCustomerRepository.
type MockCustomerRepositoryMockRecorder struct {
	mock *MockCustomerRepository
}

// NewMockCustomerRepository creates a new mock instance.
func NewMockCustomerRepository(ctrl *gomock.Controller) *MockCustomerRepository {
	mock := &MockCustomerRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerRepository) EXPECT() *MockCustomerRepositoryMockRecorder {
	return m.recorder
}

// GetCustomerByID mocks base method.
func (m *MockCustomerRepository) GetCustomerByID(ctx context.Context, id string) (*member.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerByID", ctx, id)
	ret0, _ := ret[0].(*member.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerByID indicates an expected call of GetCustomerByID.
func (mr *MockCustomerRepositoryMockRecorder) GetCustomerByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByID", reflect.TypeOf((*MockCustomerRepository)(nil).GetCustomerByID), ctx, id)
}

// GetCustomersDetail mocks base method.
func (m *MockCustomerRepository) GetCustomersDetail(ctx context.Context, filterParams *utils.Filter) (*entity.CustomerRespose, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomersDetail", ctx, filterParams)
	ret0, _ := ret[0].(*entity.CustomerRespose)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomersDetail indicates an expected call of GetCustomersDetail.
func (mr *MockCustomerRepositoryMockRecorder) GetCustomersDetail(ctx, filterParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomersDetail", reflect.TypeOf((*MockCustomerRepository)(nil).GetCustomersDetail), ctx, filterParams)
}
