// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/unlink/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/unlink/repository.go -destination=internal/domain/unlink/mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ApproveOrDecline mocks base method.
func (m *MockRepository) ApproveOrDecline(userCode, decision, reason, checkerUser string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveOrDecline", userCode, decision, reason, checkerUser)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveOrDecline indicates an expected call of ApproveOrDecline.
func (mr *MockRepositoryMockRecorder) ApproveOrDecline(userCode, decision, reason, checkerUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveOrDecline", reflect.TypeOf((*MockRepository)(nil).ApproveOrDecline), userCode, decision, reason, checkerUser)
}

// UnlinkDevice mocks base method.
func (m *MockRepository) UnlinkDevice(userCode, makerUser string, branchCode []string, homeBranch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkDevice", userCode, makerUser, branchCode, homeBranch)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkDevice indicates an expected call of UnlinkDevice.
func (mr *MockRepositoryMockRecorder) UnlinkDevice(userCode, makerUser, branchCode, homeBranch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkDevice", reflect.TypeOf((*MockRepository)(nil).UnlinkDevice), userCode, makerUser, branchCode, homeBranch)
}
