// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/account/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	account "cbe-super-app-member-users/internal/port/outbound/account"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAccountRepositoryPort is a mock of AccountRepositoryPort interface.
type MockAccountRepositoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryPortMockRecorder
}

// MockAccountRepositoryPortMockRecorder is the mock recorder for MockAccountRepositoryPort.
type MockAccountRepositoryPortMockRecorder struct {
	mock *MockAccountRepositoryPort
}

// NewMockAccountRepositoryPort creates a new mock instance.
func NewMockAccountRepositoryPort(ctrl *gomock.Controller) *MockAccountRepositoryPort {
	mock := &MockAccountRepositoryPort{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepositoryPort) EXPECT() *MockAccountRepositoryPortMockRecorder {
	return m.recorder
}

// CreateLinkedAccount mocks base method.
func (m *MockAccountRepositoryPort) CreateLinkedAccount(ctx context.Context, account *account.LinkedAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLinkedAccount", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLinkedAccount indicates an expected call of CreateLinkedAccount.
func (mr *MockAccountRepositoryPortMockRecorder) CreateLinkedAccount(ctx, account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLinkedAccount", reflect.TypeOf((*MockAccountRepositoryPort)(nil).CreateLinkedAccount), ctx, account)
}

// FindAccountUserByID mocks base method.
func (m *MockAccountRepositoryPort) FindAccountUserByID(ctx context.Context, id string) (*account.AccountUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAccountUserByID", ctx, id)
	ret0, _ := ret[0].(*account.AccountUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAccountUserByID indicates an expected call of FindAccountUserByID.
func (mr *MockAccountRepositoryPortMockRecorder) FindAccountUserByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAccountUserByID", reflect.TypeOf((*MockAccountRepositoryPort)(nil).FindAccountUserByID), ctx, id)
}

// UpdateUserCustomerNumber mocks base method.
func (m *MockAccountRepositoryPort) UpdateUserCustomerNumber(ctx context.Context, userID, customerNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserCustomerNumber", ctx, userID, customerNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserCustomerNumber indicates an expected call of UpdateUserCustomerNumber.
func (mr *MockAccountRepositoryPortMockRecorder) UpdateUserCustomerNumber(ctx, userID, customerNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserCustomerNumber", reflect.TypeOf((*MockAccountRepositoryPort)(nil).UpdateUserCustomerNumber), ctx, userID, customerNumber)
}
