// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/account/api.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAccountAPIPort is a mock of AccountAPIPort interface.
type MockAccountAPIPort struct {
	ctrl     *gomock.Controller
	recorder *MockAccountAPIPortMockRecorder
}

// MockAccountAPIPortMockRecorder is the mock recorder for MockAccountAPIPort.
type MockAccountAPIPortMockRecorder struct {
	mock *MockAccountAPIPort
}

// NewMockAccountAPIPort creates a new mock instance.
func NewMockAccountAPIPort(ctrl *gomock.Controller) *MockAccountAPIPort {
	mock := &MockAccountAPIPort{ctrl: ctrl}
	mock.recorder = &MockAccountAPIPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountAPIPort) EXPECT() *MockAccountAPIPortMockRecorder {
	return m.recorder
}

// LookupAccountByPhone mocks base method.
func (m *MockAccountAPIPort) LookupAccountByPhone(ctx context.Context, phoneNumber string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupAccountByPhone", ctx, phoneNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupAccountByPhone indicates an expected call of LookupAccountByPhone.
func (mr *MockAccountAPIPortMockRecorder) LookupAccountByPhone(ctx, phoneNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupAccountByPhone", reflect.TypeOf((*MockAccountAPIPort)(nil).LookupAccountByPhone), ctx, phoneNumber)
}
