syntax = "proto3";

package bank;

option go_package = "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/grpc/pb";

import "google/protobuf/timestamp.proto";

// Bank message definition
message Bank {
  string id = 1;
  string name = 2;
  string logo = 3;
  string code = 4;
  string bic = 5;
  bool enabled = 6;
}

// Request messages
message GetBankRequest {
  string id = 1;
}

message GetAllBanksRequest {
  int32 page = 1;
  int32 per_page = 2;
  string search = 3;
  string sort_by = 4;
  string sort_order = 5;
}

// Response messages
message GetBankResponse {
  Bank bank = 1;
  string message = 2;
}

message GetAllBanksResponse {
  repeated Bank banks = 1;
  int32 total = 2;
  int32 page = 3;
  int32 per_page = 4;
  int32 total_pages = 5;
  string message = 6;
}



// Bank service definition
service BankService {
  // Get a single bank by ID
  rpc GetBank(GetBankRequest) returns (GetBankResponse);
  
  // Get all banks with pagination and filtering
  rpc GetAllBanks(GetAllBanksRequest) returns (GetAllBanksResponse);
  
}
