// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/users/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	users "cbe-super-app-member-users/internal/port/outbound/users"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepositoryPort is a mock of UserRepositoryPort interface.
type MockUserRepositoryPort struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryPortMockRecorder
}

// MockUserRepositoryPortMockRecorder is the mock recorder for MockUserRepositoryPort.
type MockUserRepositoryPortMockRecorder struct {
	mock *MockUserRepositoryPort
}

// NewMockUserRepositoryPort creates a new mock instance.
func NewMockUserRepositoryPort(ctrl *gomock.Controller) *MockUserRepositoryPort {
	mock := &MockUserRepositoryPort{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryPort) EXPECT() *MockUserRepositoryPortMockRecorder {
	return m.recorder
}

// FindActiveLinkedAccounts mocks base method.
func (m *MockUserRepositoryPort) FindActiveLinkedAccounts(ctx context.Context, userID string) ([]users.LinkedAccountDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveLinkedAccounts", ctx, userID)
	ret0, _ := ret[0].([]users.LinkedAccountDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveLinkedAccounts indicates an expected call of FindActiveLinkedAccounts.
func (mr *MockUserRepositoryPortMockRecorder) FindActiveLinkedAccounts(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveLinkedAccounts", reflect.TypeOf((*MockUserRepositoryPort)(nil).FindActiveLinkedAccounts), ctx, userID)
}

// FindByEmail mocks base method.
func (m *MockUserRepositoryPort) FindByEmail(ctx context.Context, email string) (*users.UserEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*users.UserEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserRepositoryPortMockRecorder) FindByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserRepositoryPort)(nil).FindByEmail), ctx, email)
}

// FindByID mocks base method.
func (m *MockUserRepositoryPort) FindByID(ctx context.Context, id string) (*users.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*users.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryPortMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepositoryPort)(nil).FindByID), ctx, id)
}

// FindOTP mocks base method.
func (m *MockUserRepositoryPort) FindOTP(ctx context.Context, userID, email string) (*users.OTPRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOTP", ctx, userID, email)
	ret0, _ := ret[0].(*users.OTPRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOTP indicates an expected call of FindOTP.
func (mr *MockUserRepositoryPortMockRecorder) FindOTP(ctx, userID, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOTP", reflect.TypeOf((*MockUserRepositoryPort)(nil).FindOTP), ctx, userID, email)
}

// StoreOTP mocks base method.
func (m *MockUserRepositoryPort) StoreOTP(ctx context.Context, otp *users.OTPRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreOTP", ctx, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreOTP indicates an expected call of StoreOTP.
func (mr *MockUserRepositoryPortMockRecorder) StoreOTP(ctx, otp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreOTP", reflect.TypeOf((*MockUserRepositoryPort)(nil).StoreOTP), ctx, otp)
}

// UpdateUserEmail mocks base method.
func (m *MockUserRepositoryPort) UpdateUserEmail(ctx context.Context, userID, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserEmail", ctx, userID, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserEmail indicates an expected call of UpdateUserEmail.
func (mr *MockUserRepositoryPortMockRecorder) UpdateUserEmail(ctx, userID, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserEmail", reflect.TypeOf((*MockUserRepositoryPort)(nil).UpdateUserEmail), ctx, userID, email)
}
