// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: proto/session.proto

package session

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateSessionRequest represents a request to create a new session
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionData   []byte                 `protobuf:"bytes,2,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"` // JSON encoded session data
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	ServiceFeeIds string                 `protobuf:"bytes,5,opt,name=service_fee_ids,json=serviceFeeIds,proto3" json:"service_fee_ids,omitempty"`
	AuthTierId    string                 `protobuf:"bytes,6,opt,name=auth_tier_id,json=authTierId,proto3" json:"auth_tier_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateSessionRequest) GetSessionData() []byte {
	if x != nil {
		return x.SessionData
	}
	return nil
}

func (x *CreateSessionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateSessionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateSessionRequest) GetServiceFeeIds() string {
	if x != nil {
		return x.ServiceFeeIds
	}
	return ""
}

func (x *CreateSessionRequest) GetAuthTierId() string {
	if x != nil {
		return x.AuthTierId
	}
	return ""
}

func (x *CreateSessionRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateSessionRequest) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CreateSessionRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// CreateSessionResponse represents the response for session creation
type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionData   []byte                 `protobuf:"bytes,2,opt,name=session_data,json=sessionData,proto3" json:"session_data,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Services      []*ServiceConfig       `protobuf:"bytes,6,rep,name=services,proto3" json:"services,omitempty"`
	AuthTier      *AuthTier              `protobuf:"bytes,7,opt,name=auth_tier,json=authTier,proto3" json:"auth_tier,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SignedData    bool                   `protobuf:"varint,11,opt,name=signed_data,json=signedData,proto3" json:"signed_data,omitempty"`
	Token         string                 `protobuf:"bytes,12,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_proto_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateSessionResponse) GetSessionData() []byte {
	if x != nil {
		return x.SessionData
	}
	return nil
}

func (x *CreateSessionResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateSessionResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CreateSessionResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateSessionResponse) GetServices() []*ServiceConfig {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *CreateSessionResponse) GetAuthTier() *AuthTier {
	if x != nil {
		return x.AuthTier
	}
	return nil
}

func (x *CreateSessionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateSessionResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CreateSessionResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *CreateSessionResponse) GetSignedData() bool {
	if x != nil {
		return x.SignedData
	}
	return false
}

func (x *CreateSessionResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// UpdateSessionRequest represents a request to update a session
type UpdateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionRequest) Reset() {
	*x = UpdateSessionRequest{}
	mi := &file_proto_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// func (*UpdateSessionRequest) ProtoMessage() {}

func (x *UpdateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateSessionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// UpdateSessionResponse represents the response for session update
type UpdateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionResponse) Reset() {
	*x = UpdateSessionResponse{}
	mi := &file_proto_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// func (*UpdateSessionResponse) ProtoMessage() {}

func (x *UpdateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetSessionRequest represents a request to get session information
type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_proto_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// GetSessionResponse represents the response for getting session information
type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AuthTier      *AuthTier              `protobuf:"bytes,2,opt,name=auth_tier,json=authTier,proto3" json:"auth_tier,omitempty"`
	Services      []*ServiceConfig       `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	TotalFees     float64                `protobuf:"fixed64,6,opt,name=total_fees,json=totalFees,proto3" json:"total_fees,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SignedData    bool                   `protobuf:"varint,10,opt,name=signed_data,json=signedData,proto3" json:"signed_data,omitempty"`
	Checksum      string                 `protobuf:"bytes,11,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_proto_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetSessionResponse) GetAuthTier() *AuthTier {
	if x != nil {
		return x.AuthTier
	}
	return nil
}

func (x *GetSessionResponse) GetServices() []*ServiceConfig {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *GetSessionResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetSessionResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetSessionResponse) GetTotalFees() float64 {
	if x != nil {
		return x.TotalFees
	}
	return 0
}

func (x *GetSessionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetSessionResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetSessionResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *GetSessionResponse) GetSignedData() bool {
	if x != nil {
		return x.SignedData
	}
	return false
}

func (x *GetSessionResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// HealthCheckRequest represents a health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{6}
}

// HealthCheckResponse represents a health check response
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ServiceConfig represents service configuration
type ServiceConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceCode        string                 `protobuf:"bytes,2,opt,name=service_code,json=serviceCode,proto3" json:"service_code,omitempty"`
	ServiceName        string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceType        string                 `protobuf:"bytes,4,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	Key                string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Cap                *Cap                   `protobuf:"bytes,6,opt,name=cap,proto3" json:"cap,omitempty"`
	CbeProductCodes    *ProductCodes          `protobuf:"bytes,7,opt,name=cbe_product_codes,json=cbeProductCodes,proto3" json:"cbe_product_codes,omitempty"`
	CbeIfbProductCodes *ProductCodes          `protobuf:"bytes,8,opt,name=cbe_ifb_product_codes,json=cbeIfbProductCodes,proto3" json:"cbe_ifb_product_codes,omitempty"`
	AboveAmount        int32                  `protobuf:"varint,9,opt,name=above_amount,json=aboveAmount,proto3" json:"above_amount,omitempty"`
	AboveServiceFee    int32                  `protobuf:"varint,10,opt,name=above_service_fee,json=aboveServiceFee,proto3" json:"above_service_fee,omitempty"`
	PaymentType        string                 `protobuf:"bytes,11,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	Tiers              []*Tier                `protobuf:"bytes,12,rep,name=tiers,proto3" json:"tiers,omitempty"`
	CbeGlEntry         *GLEntry               `protobuf:"bytes,13,opt,name=cbe_gl_entry,json=cbeGlEntry,proto3" json:"cbe_gl_entry,omitempty"`
	CbeIfbGlEntry      *GLEntry               `protobuf:"bytes,14,opt,name=cbe_ifb_gl_entry,json=cbeIfbGlEntry,proto3" json:"cbe_ifb_gl_entry,omitempty"`
	Enabled            bool                   `protobuf:"varint,15,opt,name=enabled,proto3" json:"enabled,omitempty"`
	IsDeleted          bool                   `protobuf:"varint,16,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastModifiedAt     string                 `protobuf:"bytes,18,opt,name=last_modified_at,json=lastModifiedAt,proto3" json:"last_modified_at,omitempty"`
	DeletedAt          string                 `protobuf:"bytes,19,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_proto_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceConfig) GetServiceCode() string {
	if x != nil {
		return x.ServiceCode
	}
	return ""
}

func (x *ServiceConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceConfig) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *ServiceConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ServiceConfig) GetCap() *Cap {
	if x != nil {
		return x.Cap
	}
	return nil
}

func (x *ServiceConfig) GetCbeProductCodes() *ProductCodes {
	if x != nil {
		return x.CbeProductCodes
	}
	return nil
}

func (x *ServiceConfig) GetCbeIfbProductCodes() *ProductCodes {
	if x != nil {
		return x.CbeIfbProductCodes
	}
	return nil
}

func (x *ServiceConfig) GetAboveAmount() int32 {
	if x != nil {
		return x.AboveAmount
	}
	return 0
}

func (x *ServiceConfig) GetAboveServiceFee() int32 {
	if x != nil {
		return x.AboveServiceFee
	}
	return 0
}

func (x *ServiceConfig) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *ServiceConfig) GetTiers() []*Tier {
	if x != nil {
		return x.Tiers
	}
	return nil
}

func (x *ServiceConfig) GetCbeGlEntry() *GLEntry {
	if x != nil {
		return x.CbeGlEntry
	}
	return nil
}

func (x *ServiceConfig) GetCbeIfbGlEntry() *GLEntry {
	if x != nil {
		return x.CbeIfbGlEntry
	}
	return nil
}

func (x *ServiceConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ServiceConfig) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *ServiceConfig) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ServiceConfig) GetLastModifiedAt() string {
	if x != nil {
		return x.LastModifiedAt
	}
	return ""
}

func (x *ServiceConfig) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

// AuthTier represents authentication tier configuration
type AuthTier struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MinAmount      int64                  `protobuf:"varint,2,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount      int64                  `protobuf:"varint,3,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	Enabled        bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	IsDeleted      bool                   `protobuf:"varint,5,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	Method         string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	LastModifiedAt string                 `protobuf:"bytes,7,opt,name=last_modified_at,json=lastModifiedAt,proto3" json:"last_modified_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthTier) Reset() {
	*x = AuthTier{}
	mi := &file_proto_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// func (*AuthTier) ProtoMessage() {}

func (x *AuthTier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTier.ProtoReflect.Descriptor instead.
func (*AuthTier) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{9}
}

func (x *AuthTier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthTier) GetMinAmount() int64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *AuthTier) GetMaxAmount() int64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *AuthTier) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AuthTier) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *AuthTier) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuthTier) GetLastModifiedAt() string {
	if x != nil {
		return x.LastModifiedAt
	}
	return ""
}

// Cap represents capacity limits
type Cap struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IndividualDailyCap  int32                  `protobuf:"varint,1,opt,name=individual_daily_cap,json=individualDailyCap,proto3" json:"individual_daily_cap,omitempty"`
	IndividualSingleCap int32                  `protobuf:"varint,2,opt,name=individual_single_cap,json=individualSingleCap,proto3" json:"individual_single_cap,omitempty"`
	KycLevel            string                 `protobuf:"bytes,3,opt,name=kyc_level,json=kycLevel,proto3" json:"kyc_level,omitempty"`
	MinAmount           int32                  `protobuf:"varint,4,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	CorporateDailyCap   int32                  `protobuf:"varint,5,opt,name=corporate_daily_cap,json=corporateDailyCap,proto3" json:"corporate_daily_cap,omitempty"`
	CorporateSingleCap  int32                  `protobuf:"varint,6,opt,name=corporate_single_cap,json=corporateSingleCap,proto3" json:"corporate_single_cap,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Cap) Reset() {
	*x = Cap{}
	mi := &file_proto_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// func (*Cap) ProtoMessage() {}

func (x *Cap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cap.ProtoReflect.Descriptor instead.
func (*Cap) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{10}
}

func (x *Cap) GetIndividualDailyCap() int32 {
	if x != nil {
		return x.IndividualDailyCap
	}
	return 0
}

func (x *Cap) GetIndividualSingleCap() int32 {
	if x != nil {
		return x.IndividualSingleCap
	}
	return 0
}

func (x *Cap) GetKycLevel() string {
	if x != nil {
		return x.KycLevel
	}
	return ""
}

func (x *Cap) GetMinAmount() int32 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *Cap) GetCorporateDailyCap() int32 {
	if x != nil {
		return x.CorporateDailyCap
	}
	return 0
}

func (x *Cap) GetCorporateSingleCap() int32 {
	if x != nil {
		return x.CorporateSingleCap
	}
	return 0
}

// ProductCodes represents product codes
type ProductCodes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prd           string                 `protobuf:"bytes,1,opt,name=prd,proto3" json:"prd,omitempty"`
	VatPrd        string                 `protobuf:"bytes,2,opt,name=vat_prd,json=vatPrd,proto3" json:"vat_prd,omitempty"`
	SfPrd         string                 `protobuf:"bytes,3,opt,name=sf_prd,json=sfPrd,proto3" json:"sf_prd,omitempty"`
	Trxn          string                 `protobuf:"bytes,4,opt,name=trxn,proto3" json:"trxn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCodes) Reset() {
	*x = ProductCodes{}
	mi := &file_proto_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// func (*ProductCodes) ProtoMessage() {}

func (x *ProductCodes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCodes.ProtoReflect.Descriptor instead.
func (*ProductCodes) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{11}
}

func (x *ProductCodes) GetPrd() string {
	if x != nil {
		return x.Prd
	}
	return ""
}

func (x *ProductCodes) GetVatPrd() string {
	if x != nil {
		return x.VatPrd
	}
	return ""
}

func (x *ProductCodes) GetSfPrd() string {
	if x != nil {
		return x.SfPrd
	}
	return ""
}

func (x *ProductCodes) GetTrxn() string {
	if x != nil {
		return x.Trxn
	}
	return ""
}

// Tier represents fee tier configuration
type Tier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeeAmount     int32                  `protobuf:"varint,1,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Min           int32                  `protobuf:"varint,3,opt,name=min,proto3" json:"min,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tier) Reset() {
	*x = Tier{}
	mi := &file_proto_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// func (*Tier) ProtoMessage() {}

func (x *Tier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tier.ProtoReflect.Descriptor instead.
func (*Tier) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{12}
}

func (x *Tier) GetFeeAmount() int32 {
	if x != nil {
		return x.FeeAmount
	}
	return 0
}

func (x *Tier) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Tier) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

// GLEntry represents general ledger entry
type GLEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductAccount    string                 `protobuf:"bytes,1,opt,name=product_account,json=productAccount,proto3" json:"product_account,omitempty"`
	ProductBranchCode string                 `protobuf:"bytes,2,opt,name=product_branch_code,json=productBranchCode,proto3" json:"product_branch_code,omitempty"`
	ServiceAccount    string                 `protobuf:"bytes,3,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	ServiceBranchCode string                 `protobuf:"bytes,4,opt,name=service_branch_code,json=serviceBranchCode,proto3" json:"service_branch_code,omitempty"`
	VatAccount        string                 `protobuf:"bytes,5,opt,name=vat_account,json=vatAccount,proto3" json:"vat_account,omitempty"`
	VatBranchCode     string                 `protobuf:"bytes,6,opt,name=vat_branch_code,json=vatBranchCode,proto3" json:"vat_branch_code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GLEntry) Reset() {
	*x = GLEntry{}
	mi := &file_proto_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GLEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// func (*GLEntry) ProtoMessage() {}

func (x *GLEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GLEntry.ProtoReflect.Descriptor instead.
func (*GLEntry) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{13}
}

func (x *GLEntry) GetProductAccount() string {
	if x != nil {
		return x.ProductAccount
	}
	return ""
}

func (x *GLEntry) GetProductBranchCode() string {
	if x != nil {
		return x.ProductBranchCode
	}
	return ""
}

func (x *GLEntry) GetServiceAccount() string {
	if x != nil {
		return x.ServiceAccount
	}
	return ""
}

func (x *GLEntry) GetServiceBranchCode() string {
	if x != nil {
		return x.ServiceBranchCode
	}
	return ""
}

func (x *GLEntry) GetVatAccount() string {
	if x != nil {
		return x.VatAccount
	}
	return ""
}

func (x *GLEntry) GetVatBranchCode() string {
	if x != nil {
		return x.VatBranchCode
	}
	return ""
}

var File_proto_session_proto protoreflect.FileDescriptor

const file_proto_session_proto_rawDesc = "" +
	"\n" +
	"\x13proto/session.proto\x12\asession\"\xa4\x02\n" +
	"\x14CreateSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fsession_data\x18\x02 \x01(\fR\vsessionData\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12&\n" +
	"\x0fservice_fee_ids\x18\x05 \x01(\tR\rserviceFeeIds\x12 \n" +
	"\fauth_tier_id\x18\x06 \x01(\tR\n" +
	"authTierId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\t \x01(\tR\texpiresAt\"\x99\x03\n" +
	"\x15CreateSessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fsession_data\x18\x02 \x01(\fR\vsessionData\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x122\n" +
	"\bservices\x18\x06 \x03(\v2\x16.session.ServiceConfigR\bservices\x12.\n" +
	"\tauth_tier\x18\a \x01(\v2\x11.session.AuthTierR\bauthTier\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\tR\texpiresAt\x12\x1f\n" +
	"\vsigned_data\x18\v \x01(\bR\n" +
	"signedData\x12\x14\n" +
	"\x05token\x18\f \x01(\tR\x05token\"M\n" +
	"\x14UpdateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"j\n" +
	"\x15UpdateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xfb\x02\n" +
	"\x12GetSessionResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12.\n" +
	"\tauth_tier\x18\x02 \x01(\v2\x11.session.AuthTierR\bauthTier\x122\n" +
	"\bservices\x18\x03 \x03(\v2\x16.session.ServiceConfigR\bservices\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"total_fees\x18\x06 \x01(\x01R\ttotalFees\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\t \x01(\tR\texpiresAt\x12\x1f\n" +
	"\vsigned_data\x18\n" +
	" \x01(\bR\n" +
	"signedData\x12\x1a\n" +
	"\bchecksum\x18\v \x01(\tR\bchecksum\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xee\x05\n" +
	"\rServiceConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fservice_code\x18\x02 \x01(\tR\vserviceCode\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12!\n" +
	"\fservice_type\x18\x04 \x01(\tR\vserviceType\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\x12\x1e\n" +
	"\x03cap\x18\x06 \x01(\v2\f.session.CapR\x03cap\x12A\n" +
	"\x11cbe_product_codes\x18\a \x01(\v2\x15.session.ProductCodesR\x0fcbeProductCodes\x12H\n" +
	"\x15cbe_ifb_product_codes\x18\b \x01(\v2\x15.session.ProductCodesR\x12cbeIfbProductCodes\x12!\n" +
	"\fabove_amount\x18\t \x01(\x05R\vaboveAmount\x12*\n" +
	"\x11above_service_fee\x18\n" +
	" \x01(\x05R\x0faboveServiceFee\x12!\n" +
	"\fpayment_type\x18\v \x01(\tR\vpaymentType\x12#\n" +
	"\x05tiers\x18\f \x03(\v2\r.session.TierR\x05tiers\x122\n" +
	"\fcbe_gl_entry\x18\r \x01(\v2\x10.session.GLEntryR\n" +
	"cbeGlEntry\x129\n" +
	"\x10cbe_ifb_gl_entry\x18\x0e \x01(\v2\x10.session.GLEntryR\rcbeIfbGlEntry\x12\x18\n" +
	"\aenabled\x18\x0f \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x10 \x01(\bR\tisDeleted\x12\x1d\n" +
	"\n" +
	"created_at\x18\x11 \x01(\tR\tcreatedAt\x12(\n" +
	"\x10last_modified_at\x18\x12 \x01(\tR\x0elastModifiedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x13 \x01(\tR\tdeletedAt\"\xd3\x01\n" +
	"\bAuthTier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x02 \x01(\x03R\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x03 \x01(\x03R\tmaxAmount\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x05 \x01(\bR\tisDeleted\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12(\n" +
	"\x10last_modified_at\x18\a \x01(\tR\x0elastModifiedAt\"\x89\x02\n" +
	"\x03Cap\x120\n" +
	"\x14individual_daily_cap\x18\x01 \x01(\x05R\x12individualDailyCap\x122\n" +
	"\x15individual_single_cap\x18\x02 \x01(\x05R\x13individualSingleCap\x12\x1b\n" +
	"\tkyc_level\x18\x03 \x01(\tR\bkycLevel\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x04 \x01(\x05R\tminAmount\x12.\n" +
	"\x13corporate_daily_cap\x18\x05 \x01(\x05R\x11corporateDailyCap\x120\n" +
	"\x14corporate_single_cap\x18\x06 \x01(\x05R\x12corporateSingleCap\"d\n" +
	"\fProductCodes\x12\x10\n" +
	"\x03prd\x18\x01 \x01(\tR\x03prd\x12\x17\n" +
	"\avat_prd\x18\x02 \x01(\tR\x06vatPrd\x12\x15\n" +
	"\x06sf_prd\x18\x03 \x01(\tR\x05sfPrd\x12\x12\n" +
	"\x04trxn\x18\x04 \x01(\tR\x04trxn\"I\n" +
	"\x04Tier\x12\x1d\n" +
	"\n" +
	"fee_amount\x18\x01 \x01(\x05R\tfeeAmount\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\x12\x10\n" +
	"\x03min\x18\x03 \x01(\x05R\x03min\"\x84\x02\n" +
	"\aGLEntry\x12'\n" +
	"\x0fproduct_account\x18\x01 \x01(\tR\x0eproductAccount\x12.\n" +
	"\x13product_branch_code\x18\x02 \x01(\tR\x11productBranchCode\x12'\n" +
	"\x0fservice_account\x18\x03 \x01(\tR\x0eserviceAccount\x12.\n" +
	"\x13service_branch_code\x18\x04 \x01(\tR\x11serviceBranchCode\x12\x1f\n" +
	"\vvat_account\x18\x05 \x01(\tR\n" +
	"vatAccount\x12&\n" +
	"\x0fvat_branch_code\x18\x06 \x01(\tR\rvatBranchCode2\xc1\x02\n" +
	"\x0eSessionService\x12N\n" +
	"\rCreateSession\x12\x1d.session.CreateSessionRequest\x1a\x1e.session.CreateSessionResponse\x12N\n" +
	"\rUpdateSession\x12\x1d.session.UpdateSessionRequest\x1a\x1e.session.UpdateSessionResponse\x12E\n" +
	"\n" +
	"GetSession\x12\x1a.session.GetSessionRequest\x1a\x1b.session.GetSessionResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.session.HealthCheckRequest\x1a\x1c.session.HealthCheckResponseB'Z%cbe-super-app-tokenizer/proto/sessionb\x06proto3"

var (
	file_proto_session_proto_rawDescOnce sync.Once
	file_proto_session_proto_rawDescData []byte
)

func file_proto_session_proto_rawDescGZIP() []byte {
	file_proto_session_proto_rawDescOnce.Do(func() {
		file_proto_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_session_proto_rawDesc), len(file_proto_session_proto_rawDesc)))
	})
	return file_proto_session_proto_rawDescData
}

var file_proto_session_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_session_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),  // 0: session.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 1: session.CreateSessionResponse
	(*UpdateSessionRequest)(nil),  // 2: session.UpdateSessionRequest
	(*UpdateSessionResponse)(nil), // 3: session.UpdateSessionResponse
	(*GetSessionRequest)(nil),     // 4: session.GetSessionRequest
	(*GetSessionResponse)(nil),    // 5: session.GetSessionResponse
	(*HealthCheckRequest)(nil),    // 6: session.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 7: session.HealthCheckResponse
	(*ServiceConfig)(nil),         // 8: session.ServiceConfig
	(*AuthTier)(nil),              // 9: session.AuthTier
	(*Cap)(nil),                   // 10: session.Cap
	(*ProductCodes)(nil),          // 11: session.ProductCodes
	(*Tier)(nil),                  // 12: session.Tier
	(*GLEntry)(nil),               // 13: session.GLEntry
}
var file_proto_session_proto_depIdxs = []int32{
	8,  // 0: session.CreateSessionResponse.services:type_name -> session.ServiceConfig
	9,  // 1: session.CreateSessionResponse.auth_tier:type_name -> session.AuthTier
	9,  // 2: session.GetSessionResponse.auth_tier:type_name -> session.AuthTier
	8,  // 3: session.GetSessionResponse.services:type_name -> session.ServiceConfig
	10, // 4: session.ServiceConfig.cap:type_name -> session.Cap
	11, // 5: session.ServiceConfig.cbe_product_codes:type_name -> session.ProductCodes
	11, // 6: session.ServiceConfig.cbe_ifb_product_codes:type_name -> session.ProductCodes
	12, // 7: session.ServiceConfig.tiers:type_name -> session.Tier
	13, // 8: session.ServiceConfig.cbe_gl_entry:type_name -> session.GLEntry
	13, // 9: session.ServiceConfig.cbe_ifb_gl_entry:type_name -> session.GLEntry
	0,  // 10: session.SessionService.CreateSession:input_type -> session.CreateSessionRequest
	2,  // 11: session.SessionService.UpdateSession:input_type -> session.UpdateSessionRequest
	4,  // 12: session.SessionService.GetSession:input_type -> session.GetSessionRequest
	6,  // 13: session.SessionService.HealthCheck:input_type -> session.HealthCheckRequest
	1,  // 14: session.SessionService.CreateSession:output_type -> session.CreateSessionResponse
	3,  // 15: session.SessionService.UpdateSession:output_type -> session.UpdateSessionResponse
	5,  // 16: session.SessionService.GetSession:output_type -> session.GetSessionResponse
	7,  // 17: session.SessionService.HealthCheck:output_type -> session.HealthCheckResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_session_proto_init() }
func file_proto_session_proto_init() {
	if File_proto_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_session_proto_rawDesc), len(file_proto_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_session_proto_goTypes,
		DependencyIndexes: file_proto_session_proto_depIdxs,
		MessageInfos:      file_proto_session_proto_msgTypes,
	}.Build()
	File_proto_session_proto = out.File
	file_proto_session_proto_goTypes = nil
	file_proto_session_proto_depIdxs = nil
}
