// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/wallet/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/wallet/repository/repository.go -destination=internal/domain/wallet/mocks/repository_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "cbe-super-app-cps-action/internal/adapter/outbound/model"
	entity "cbe-super-app-cps-action/internal/domain/wallet/entity"
	utils "cbe-super-app-cps-action/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockRepository) Authorize(ctx context.Context, req model.AuthorizeCPSAction) (*model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx, req)
	ret0, _ := ret[0].(*model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockRepositoryMockRecorder) Authorize(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockRepository)(nil).Authorize), ctx, req)
}

// CPSActionExists mocks base method.
func (m *MockRepository) CPSActionExists(ctx context.Context, cpsReq model.CreateCPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CPSActionExists", ctx, cpsReq)
	ret0, _ := ret[0].(error)
	return ret0
}

// CPSActionExists indicates an expected call of CPSActionExists.
func (mr *MockRepositoryMockRecorder) CPSActionExists(ctx, cpsReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CPSActionExists", reflect.TypeOf((*MockRepository)(nil).CPSActionExists), ctx, cpsReq)
}

// CreateWallet mocks base method.
func (m *MockRepository) CreateWallet(ctx context.Context, cpsReq model.CreateCPSAction) (*model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx, cpsReq)
	ret0, _ := ret[0].(*model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockRepositoryMockRecorder) CreateWallet(ctx, cpsReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockRepository)(nil).CreateWallet), ctx, cpsReq)
}

// DeleteWallet mocks base method.
func (m *MockRepository) DeleteWallet(ctx context.Context, id string, cpsReq model.CreateCPSAction) (*model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWallet", ctx, id, cpsReq)
	ret0, _ := ret[0].(*model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWallet indicates an expected call of DeleteWallet.
func (mr *MockRepositoryMockRecorder) DeleteWallet(ctx, id, cpsReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWallet", reflect.TypeOf((*MockRepository)(nil).DeleteWallet), ctx, id, cpsReq)
}

// EnableOrDisableWallet mocks base method.
func (m *MockRepository) EnableOrDisableWallet(ctx context.Context, id string, requestAction model.RequestAction, cpsReq model.CreateCPSAction) (*model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableOrDisableWallet", ctx, id, requestAction, cpsReq)
	ret0, _ := ret[0].(*model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnableOrDisableWallet indicates an expected call of EnableOrDisableWallet.
func (mr *MockRepositoryMockRecorder) EnableOrDisableWallet(ctx, id, requestAction, cpsReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableOrDisableWallet", reflect.TypeOf((*MockRepository)(nil).EnableOrDisableWallet), ctx, id, requestAction, cpsReq)
}

// GetAllWallet mocks base method.
func (m *MockRepository) GetAllWallet(ctx context.Context, filterParams *utils.Filter) (*entity.WalletResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWallet", ctx, filterParams)
	ret0, _ := ret[0].(*entity.WalletResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWallet indicates an expected call of GetAllWallet.
func (mr *MockRepositoryMockRecorder) GetAllWallet(ctx, filterParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWallet", reflect.TypeOf((*MockRepository)(nil).GetAllWallet), ctx, filterParams)
}

// GetWallet mocks base method.
func (m *MockRepository) GetWallet(ctx context.Context, id string) (*entity.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWallet", ctx, id)
	ret0, _ := ret[0].(*entity.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWallet indicates an expected call of GetWallet.
func (mr *MockRepositoryMockRecorder) GetWallet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWallet", reflect.TypeOf((*MockRepository)(nil).GetWallet), ctx, id)
}

// Reject mocks base method.
func (m *MockRepository) Reject(ctx context.Context, req model.RejectCPSAction) (*model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject", ctx, req)
	ret0, _ := ret[0].(*model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reject indicates an expected call of Reject.
func (mr *MockRepositoryMockRecorder) Reject(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*MockRepository)(nil).Reject), ctx, req)
}

// UpdateWallet mocks base method.
func (m *MockRepository) UpdateWallet(ctx context.Context, id string, cpsReq model.CreateCPSAction) (*model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWallet", ctx, id, cpsReq)
	ret0, _ := ret[0].(*model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWallet indicates an expected call of UpdateWallet.
func (mr *MockRepositoryMockRecorder) UpdateWallet(ctx, id, cpsReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWallet", reflect.TypeOf((*MockRepository)(nil).UpdateWallet), ctx, id, cpsReq)
}
