// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: bank.proto

package bank

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BankService_GetOneBank_FullMethodName   = "/BankService.BankService/GetOneBank"
	BankService_GetAllBank_FullMethodName   = "/BankService.BankService/GetAllBank"
	BankService_GetBankByBIC_FullMethodName = "/BankService.BankService/GetBankByBIC"
)

// BankServiceClient is the client API for BankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BankServiceClient interface {
	GetOneBank(ctx context.Context, in *GetOneBankRequest, opts ...grpc.CallOption) (*GetOneBankResponse, error)
	GetAllBank(ctx context.Context, in *GetAllBankRequest, opts ...grpc.CallOption) (*GetAllBankResponse, error)
	GetBankByBIC(ctx context.Context, in *GetOneBankByBICRequest, opts ...grpc.CallOption) (*GetOneBankResponse, error)
}

type bankServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankServiceClient(cc grpc.ClientConnInterface) BankServiceClient {
	return &bankServiceClient{cc}
}

func (c *bankServiceClient) GetOneBank(ctx context.Context, in *GetOneBankRequest, opts ...grpc.CallOption) (*GetOneBankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOneBankResponse)
	err := c.cc.Invoke(ctx, BankService_GetOneBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) GetAllBank(ctx context.Context, in *GetAllBankRequest, opts ...grpc.CallOption) (*GetAllBankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllBankResponse)
	err := c.cc.Invoke(ctx, BankService_GetAllBank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) GetBankByBIC(ctx context.Context, in *GetOneBankByBICRequest, opts ...grpc.CallOption) (*GetOneBankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOneBankResponse)
	err := c.cc.Invoke(ctx, BankService_GetBankByBIC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankServiceServer is the server API for BankService service.
// All implementations must embed UnimplementedBankServiceServer
// for forward compatibility.
type BankServiceServer interface {
	GetOneBank(context.Context, *GetOneBankRequest) (*GetOneBankResponse, error)
	GetAllBank(context.Context, *GetAllBankRequest) (*GetAllBankResponse, error)
	GetBankByBIC(context.Context, *GetOneBankByBICRequest) (*GetOneBankResponse, error)
	mustEmbedUnimplementedBankServiceServer()
}

// UnimplementedBankServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBankServiceServer struct{}

func (UnimplementedBankServiceServer) GetOneBank(context.Context, *GetOneBankRequest) (*GetOneBankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOneBank not implemented")
}
func (UnimplementedBankServiceServer) GetAllBank(context.Context, *GetAllBankRequest) (*GetAllBankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBank not implemented")
}
func (UnimplementedBankServiceServer) GetBankByBIC(context.Context, *GetOneBankByBICRequest) (*GetOneBankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankByBIC not implemented")
}
func (UnimplementedBankServiceServer) mustEmbedUnimplementedBankServiceServer() {}
func (UnimplementedBankServiceServer) testEmbeddedByValue()                     {}

// UnsafeBankServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankServiceServer will
// result in compilation errors.
type UnsafeBankServiceServer interface {
	mustEmbedUnimplementedBankServiceServer()
}

func RegisterBankServiceServer(s grpc.ServiceRegistrar, srv BankServiceServer) {
	// If the following call pancis, it indicates UnimplementedBankServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BankService_ServiceDesc, srv)
}

func _BankService_GetOneBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneBankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).GetOneBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankService_GetOneBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).GetOneBank(ctx, req.(*GetOneBankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_GetAllBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).GetAllBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankService_GetAllBank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).GetAllBank(ctx, req.(*GetAllBankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_GetBankByBIC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneBankByBICRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).GetBankByBIC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankService_GetBankByBIC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).GetBankByBIC(ctx, req.(*GetOneBankByBICRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BankService_ServiceDesc is the grpc.ServiceDesc for BankService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BankService.BankService",
	HandlerType: (*BankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOneBank",
			Handler:    _BankService_GetOneBank_Handler,
		},
		{
			MethodName: "GetAllBank",
			Handler:    _BankService_GetAllBank_Handler,
		},
		{
			MethodName: "GetBankByBIC",
			Handler:    _BankService_GetBankByBIC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bank.proto",
}
