// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/bank/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/bank/repository/repository.go -destination=internal/domain/bank/mocks/repository_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/adapter/outbound/model"
	entity "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/domain/bank/entity"
	utils "github.com/CBE-Super-App/cbe-super-app-cps-action/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockRepository) Authorize(ctx context.Context, req model.AuthorizeCPSAction) (*model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx, req)
	ret0, _ := ret[0].(*model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockRepositoryMockRecorder) Authorize(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockRepository)(nil).Authorize), ctx, req)
}

// CPSActionExists mocks base method.
func (m *MockRepository) CPSActionExists(ctx context.Context, cpsReq model.CreateCPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CPSActionExists", ctx, cpsReq)
	ret0, _ := ret[0].(error)
	return ret0
}

// CPSActionExists indicates an expected call of CPSActionExists.
func (mr *MockRepositoryMockRecorder) CPSActionExists(ctx, cpsReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CPSActionExists", reflect.TypeOf((*MockRepository)(nil).CPSActionExists), ctx, cpsReq)
}

// CreateBank mocks base method.
func (m *MockRepository) CreateBank(ctx context.Context, cpsReq model.CreateCPSAction) (*model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBank", ctx, cpsReq)
	ret0, _ := ret[0].(*model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBank indicates an expected call of CreateBank.
func (mr *MockRepositoryMockRecorder) CreateBank(ctx, cpsReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBank", reflect.TypeOf((*MockRepository)(nil).CreateBank), ctx, cpsReq)
}

// DeleteBank mocks base method.
func (m *MockRepository) DeleteBank(ctx context.Context, id string, cpsReq model.CreateCPSAction) (*model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBank", ctx, id, cpsReq)
	ret0, _ := ret[0].(*model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBank indicates an expected call of DeleteBank.
func (mr *MockRepositoryMockRecorder) DeleteBank(ctx, id, cpsReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBank", reflect.TypeOf((*MockRepository)(nil).DeleteBank), ctx, id, cpsReq)
}

// EnableOrDisableBank mocks base method.
func (m *MockRepository) EnableOrDisableBank(ctx context.Context, id string, requestAction model.RequestAction, cpsReq model.CreateCPSAction) (*model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableOrDisableBank", ctx, id, requestAction, cpsReq)
	ret0, _ := ret[0].(*model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnableOrDisableBank indicates an expected call of EnableOrDisableBank.
func (mr *MockRepositoryMockRecorder) EnableOrDisableBank(ctx, id, requestAction, cpsReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableOrDisableBank", reflect.TypeOf((*MockRepository)(nil).EnableOrDisableBank), ctx, id, requestAction, cpsReq)
}

// GetAllBanks mocks base method.
func (m *MockRepository) GetAllBanks(ctx context.Context, filterParams *utils.Filter) (*entity.BankResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBanks", ctx, filterParams)
	ret0, _ := ret[0].(*entity.BankResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBanks indicates an expected call of GetAllBanks.
func (mr *MockRepositoryMockRecorder) GetAllBanks(ctx, filterParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBanks", reflect.TypeOf((*MockRepository)(nil).GetAllBanks), ctx, filterParams)
}

// GetBank mocks base method.
func (m *MockRepository) GetBank(ctx context.Context, id string) (*entity.Bank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBank", ctx, id)
	ret0, _ := ret[0].(*entity.Bank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBank indicates an expected call of GetBank.
func (mr *MockRepositoryMockRecorder) GetBank(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBank", reflect.TypeOf((*MockRepository)(nil).GetBank), ctx, id)
}

// Reject mocks base method.
func (m *MockRepository) Reject(ctx context.Context, req model.RejectCPSAction) (*model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject", ctx, req)
	ret0, _ := ret[0].(*model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reject indicates an expected call of Reject.
func (mr *MockRepositoryMockRecorder) Reject(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*MockRepository)(nil).Reject), ctx, req)
}

// UpdateBank mocks base method.
func (m *MockRepository) UpdateBank(ctx context.Context, id string, cpsReq model.CreateCPSAction) (*model.CpsAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBank", ctx, id, cpsReq)
	ret0, _ := ret[0].(*model.CpsAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBank indicates an expected call of UpdateBank.
func (mr *MockRepositoryMockRecorder) UpdateBank(ctx, id, cpsReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBank", reflect.TypeOf((*MockRepository)(nil).UpdateBank), ctx, id, cpsReq)
}
