package mini_app_query

const (
	// Category queries
	MiniAppCategorySelectCols    = `SELECT RAWTOHEX(ID) AS ID, NAME, ICON, IS_ENABLED, IS_DELETED, CREATED_AT, LAST_MODIFIED_AT, DELETED_AT FROM MINI_APP_CATEGORIES`
	MiniAppCategoryCountBase     = `SELECT COUNT(1) FROM MINI_APP_CATEGORIES`
	MiniAppCategoryCountByName   = `SELECT COUNT(1) FROM MINI_APP_CATEGORIES WHERE IS_DELETED = 0 AND LOWER(NAME) = LOWER(:1)`
	MiniAppCategoryByIDBase      = MiniAppCategorySelectCols + ` WHERE ID = HEXTORAW(:1) AND IS_DELETED = 0`
	MiniAppCategoryInsert        = `INSERT INTO MINI_APP_CATEGORIES (NAME, ICON, IS_ENABLED, IS_DELETED, CREATED_AT, LAST_MODIFIED_AT) VALUES (:1, :2, :3, :4, :5, :6)`
	MiniAppCategoryUpdate        = `UPDATE MINI_APP_CATEGORIES SET NAME = :1, ICON = :2, LAST_MODIFIED_AT = :3 WHERE ID = HEXTORAW(:4) AND IS_DELETED = 0`
	MiniAppCategoryToggleEnabled = `UPDATE MINI_APP_CATEGORIES SET IS_ENABLED = :1, LAST_MODIFIED_AT = :2 WHERE ID = HEXTORAW(:3) AND IS_DELETED = 0`
	MiniAppCategorySoftDelete    = `UPDATE MINI_APP_CATEGORIES SET IS_DELETED = 1, DELETED_AT = :1, LAST_MODIFIED_AT = :2 WHERE ID = HEXTORAW(:3) AND IS_DELETED = 0`

	// Mini-app queries
	MiniAppsCountByCategoryID = `SELECT COUNT(1) FROM MINI_APPS WHERE CATEGORY_ID = HEXTORAW(:1) AND IS_DELETED = 0`
	MiniAppsCountByDynamic    = `SELECT COUNT(1) FROM MINI_APPS WHERE IS_DELETED = 0 AND (`
	
	// MiniAppsInsert            = `INSERT INTO MINI_APPS ( CATEGORY_ID, MERCHANT_ID, APP_NAME, APP_ICON, APP_TYPE, BANNER_IMAGE, URL, APP_VIEW_TYPE, IS_FEATURED, IS_ENABLED, IS_DELETED, CREATED_AT, LAST_MODIFIED_AT, CRED_MERCHANT_APP_ID, CRED_FABRIC_APP_ID, CRED_SHORT_CODE, CRED_APP_SECRET, CRED_PRIVATE_KEY, CRED_PUBLIC_KEY, SERVICE_ID) VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10, :11, :12, :13, :14, :15, :16, :17, :18, :19)`
	MiniAppsInsert = `
INSERT INTO MINI_APPS (
    CATEGORY_ID,
    MERCHANT_ID,
    APP_NAME,
    APP_ICON,
    APP_TYPE,
    BANNER_IMAGE,
    URL,
    APP_VIEW_TYPE,
    IS_FEATURED,
    IS_ENABLED,
    IS_DELETED,
    CREATED_AT,
    LAST_MODIFIED_AT,
    CREDENTIAL_MERCHANT_APP_ID,
    CREDENTIAL_FABRIC_APP_ID,
    CREDENTIAL_SHORT_CODE,
    CREDENTIAL_APP_SECRET,
    CREDENTIAL_PRIVATE_KEY,
    CREDENTIAL_PUBLIC_KEY,
    SERVICE_ID
) VALUES (
    :1, :2, :3, :4, :5, :6, :7, :8, :9, :10,
    :11, :12, :13, :14, :15, :16, :17, :18, :19, :20
)`

	MiniAppsUpdate            = `UPDATE MINI_APPS SET CATEGORY_ID = :1, MERCHANT_ID = :2, APP_NAME = :3, APP_ICON = :4, APP_TYPE = :5, BANNER_IMAGE = :6, URL = :7, APP_VIEW_TYPE = :8, IS_FEATURED = :9, IS_ENABLED = :10, LAST_MODIFIED_AT = :11, CREDENTIAL_MERCHANT_APP_ID = :12, CREDENTIAL_FABRIC_APP_ID = :13, CREDENTIAL_SHORT_CODE = :14, CREDENTIAL_APP_SECRET = :15, CREDENTIAL_PRIVATE_KEY = :16, CREDENTIAL_PUBLIC_KEY = :17, SERVICE_ID =:18  WHERE ID = HEXTORAW(:19) AND IS_DELETED = 0`


	MiniAppsSoftDelete        = `UPDATE MINI_APPS SET IS_DELETED = 1, DELETED_AT = :1, LAST_MODIFIED_AT = :2 WHERE ID = HEXTORAW(:3) AND IS_DELETED = 0`
	MiniAppsToggleEnable      = `UPDATE MINI_APPS SET IS_ENABLED = :1, LAST_MODIFIED_AT = :2 WHERE ID = HEXTORAW(:3) AND IS_DELETED = 0`

	MiniAppsBaseSelect        = `SELECT RAWTOHEX(a.ID), RAWTOHEX(a.CATEGORY_ID), RAWTOHEX(a.MERCHANT_ID), RAWTOHEX(a.SERVICE_ID), a.APP_NAME, a.APP_ICON, a.APP_TYPE, a.BANNER_IMAGE, a.URL, a.APP_VIEW_TYPE, a.IS_FEATURED, a.IS_ENABLED, a.IS_DELETED, a.CREATED_AT, a.LAST_MODIFIED_AT, a.DELETED_AT, a.CREDENTIAL_MERCHANT_APP_ID, a.CREDENTIAL_FABRIC_APP_ID, a.CREDENTIAL_SHORT_CODE, a.CREDENTIAL_APP_SECRET, a.CREDENTIAL_PRIVATE_KEY, a.CREDENTIAL_PUBLIC_KEY, RAWTOHEX(c.ID), c.NAME, c.ICON, RAWTOHEX(m.ID), m.MERCHANT_NAME, m.MERCHANT_CODE FROM MINI_APPS a LEFT JOIN MINI_APP_CATEGORIES c ON c.ID = a.CATEGORY_ID LEFT JOIN MERCHANTS m ON m.ID = a.MERCHANT_ID`

	MiniAppsGroupedByCategory = `SELECT CATEGORY_ID_HEX, CATEGORY_NAME, APP_ID_HEX, APP_NAME, APP_ICON, APP_TYPE, BANNER_IMAGE, URL, APP_VIEW_TYPE, IS_FEATURED, SERVICE_CODE, CNT FROM ( SELECT RAWTOHEX(a.CATEGORY_ID) AS CATEGORY_ID_HEX, c.NAME AS CATEGORY_NAME, RAWTOHEX(a.ID) AS APP_ID_HEX, a.APP_NAME, a.APP_ICON, a.APP_TYPE, a.BANNER_IMAGE, a.URL, a.APP_VIEW_TYPE, a.IS_FEATURED, a.SERVICE_CODE, COUNT(*) OVER (PARTITION BY a.CATEGORY_ID) AS CNT, ROW_NUMBER() OVER (PARTITION BY a.CATEGORY_ID ORDER BY a.CREATED_AT DESC, a.ID DESC) AS RN FROM MINI_APPS a JOIN MINI_APP_CATEGORIES c ON c.ID = a.CATEGORY_ID WHERE a.IS_DELETED = 0 AND a.IS_ENABLED = 1 `

	// Merchant queries
	MiniAppMerchantsSelectCols     = `SELECT RAWTOHEX(ID), MERCHANT_NAME, MERCHANT_CODE, SETTLEMENT_METHOD, MERCHANT_ACCOUNT_NUMBER, IS_ENABLED, IS_DELETED, CREATED_AT, LAST_MODIFIED_AT, DELETED_AT,CONTACT_PHONE,CONTACT_EMAIL FROM MERCHANTS`
	MiniAppMerchantsCountBase      = `SELECT COUNT(1) FROM MERCHANTS`
	MiniAppMerchantsCountByDynamic = `SELECT COUNT(1) FROM MERCHANTS WHERE MERCHANT_TYPE = 'MINI_APP' AND IS_DELETED = 0 AND  (`
	MiniAppMerchantByID           = MiniAppMerchantsSelectCols + ` WHERE ID = HEXTORAW(:1) AND IS_DELETED = 0`
	MiniAppMerchantInsert = `
INSERT INTO MERCHANTS (
    MERCHANT_NAME,
    MERCHANT_CODE,
    MERCHANT_TYPE,
    SETTLEMENT_METHOD,
    MERCHANT_ACCOUNT_NUMBER,
    IS_ENABLED,
    IS_DELETED,
    CREATED_AT,
    LAST_MODIFIED_AT,
    CONTACT_PHONE,
    CONTACT_EMAIL
) VALUES (
    :1,
    :2,
	'MINI_APP',
    :3,
    :4,
    :5,
    :6,
    :7,
    :8,
    :9,
    :10
    
)`
	MiniAppMerchantUpdate          = `UPDATE MERCHANTS SET MERCHANT_NAME = :1, MERCHANT_CODE = :2, SETTLEMENT_METHOD = :3, MERCHANT_ACCOUNT_NUMBER = :4, LAST_MODIFIED_AT = :5,CONTACT_PHONE =:6,
    CONTACT_EMAIL = :7  WHERE ID = HEXTORAW(:8) AND IS_DELETED = 0 AND MERCHANT_TYPE = 'MINI_APP'`
	MiniAppMerchantSoftDelete      = `UPDATE MERCHANTS SET IS_DELETED = 1, DELETED_AT = :1, LAST_MODIFIED_AT = :2 WHERE ID = HEXTORAW(:3) AND IS_DELETED = 0 AND MERCHANT_TYPE = 'MINI_APP'`
	MiniAppMerchantToggleEnabled   = `UPDATE MERCHANTS SET IS_ENABLED = :1, LAST_MODIFIED_AT = :2 WHERE ID = HEXTORAW(:3) AND IS_DELETED = 0 AND MERCHANT_TYPE = 'MINI_APP'`


)