syntax = "proto3";

package wallet;



option go_package = "github.com/cbesuperapp/cbe-super-app-cps-action/grpc/wallet;grpcwallet";

message Wallet {
  string id = 1;
  string name = 2;
  string unique_code = 3;
  string avatar = 4;
  bool enabled = 5;
  bool is_deleted = 6;
  Services services = 7;
  string service_code = 8;
  string service_key = 9;
  string service_id = 10;
}

message Services {
  bool self = 1;
  bool other = 2;
  bool agent = 3;
}
message docs {
    repeated Wallet wallets = 1;
}


message GetWalletRequest {
  string id = 1;
}

message GetAllWalletRequest {
  int32 page = 1;
  int32 per_page = 2;
  string search = 3;
}

message GetWalletResponse {
  Wallet wallet = 1;
}

message Meta {
  int32 limit = 1;
  int32 total_pages = 2;
  int32 total_docs = 3;
  int32 page = 4;
  bool has_next_page = 5;
  bool has_prev_page = 6;
  int32 next_page = 7;
}

message GetAllWalletResponse {
  repeated Wallet wallets = 1;
  Meta metadata = 2;
}

service WalletService {
  rpc GetWallet (GetWalletRequest) returns (GetWalletResponse);
  rpc GetAllWallet (GetAllWalletRequest) returns (GetAllWalletResponse);
}
