// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/amount_based_auth/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/adapter/outbound/model"
	amount_based_auth_domain "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/domain/amount_based_auth"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ApproveAmountBasedAuth mocks base method.
func (m *MockRepository) ApproveAmountBasedAuth(ctx context.Context, id string, cpsAction model.AuthorizeCPSAction) (*model.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveAmountBasedAuth", ctx, id, cpsAction)
	ret0, _ := ret[0].(*model.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApproveAmountBasedAuth indicates an expected call of ApproveAmountBasedAuth.
func (mr *MockRepositoryMockRecorder) ApproveAmountBasedAuth(ctx, id, cpsAction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveAmountBasedAuth", reflect.TypeOf((*MockRepository)(nil).ApproveAmountBasedAuth), ctx, id, cpsAction)
}

// RejectAmountBasedAuth mocks base method.
func (m *MockRepository) RejectAmountBasedAuth(ctx context.Context, id string, cpsAction model.RejectCPSAction) (*model.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectAmountBasedAuth", ctx, id, cpsAction)
	ret0, _ := ret[0].(*model.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RejectAmountBasedAuth indicates an expected call of RejectAmountBasedAuth.
func (mr *MockRepositoryMockRecorder) RejectAmountBasedAuth(ctx, id, cpsAction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectAmountBasedAuth", reflect.TypeOf((*MockRepository)(nil).RejectAmountBasedAuth), ctx, id, cpsAction)
}

// UpdateAuthTier mocks base method.
func (m *MockRepository) UpdateAuthTier(ctx context.Context, request amount_based_auth_domain.UpdateAmountBasedAuth, cpsAction model.CreateCPSAction) (*model.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAuthTier", ctx, request, cpsAction)
	ret0, _ := ret[0].(*model.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAuthTier indicates an expected call of UpdateAuthTier.
func (mr *MockRepositoryMockRecorder) UpdateAuthTier(ctx, request, cpsAction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAuthTier", reflect.TypeOf((*MockRepository)(nil).UpdateAuthTier), ctx, request, cpsAction)
}
