// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/port/outbound/minIO/minio_uploader.go

// Package mocks_minio_uploader is a generated GoMock package.
package outbound

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMinIOUploader is a mock of MinIOUploader interface.
type MockMinIOUploader struct {
	ctrl     *gomock.Controller
	recorder *MockMinIOUploaderMockRecorder
}

// MockMinIOUploaderMockRecorder is the mock recorder for MockMinIOUploader.
type MockMinIOUploaderMockRecorder struct {
	mock *MockMinIOUploader
}

// NewMockMinIOUploader creates a new mock instance.
func NewMockMinIOUploader(ctrl *gomock.Controller) *MockMinIOUploader {
	mock := &MockMinIOUploader{ctrl: ctrl}
	mock.recorder = &MockMinIOUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinIOUploader) EXPECT() *MockMinIOUploaderMockRecorder {
	return m.recorder
}

// UploadProfileImage mocks base method.
func (m *MockMinIOUploader) UploadProfileImage(ctx context.Context, objectName string, file multipart.File, contentType, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadProfileImage", ctx, objectName, file, contentType, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadProfileImage indicates an expected call of UploadProfileImage.
func (mr *MockMinIOUploaderMockRecorder) UploadProfileImage(ctx, objectName, file, contentType, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadProfileImage", reflect.TypeOf((*MockMinIOUploader)(nil).UploadProfileImage), ctx, objectName, file, contentType, userID)
}
