// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/inbound/account/port.go

// Package mocks is a generated GoMock package.
package mocks

import (
	account "cbe-super-app-member-users/internal/port/inbound/account"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAccountPort is a mock of AccountPort interface.
type MockAccountPort struct {
	ctrl     *gomock.Controller
	recorder *MockAccountPortMockRecorder
}

// MockAccountPortMockRecorder is the mock recorder for MockAccountPort.
type MockAccountPortMockRecorder struct {
	mock *MockAccountPort
}

// NewMockAccountPort creates a new mock instance.
func NewMockAccountPort(ctrl *gomock.Controller) *MockAccountPort {
	mock := &MockAccountPort{ctrl: ctrl}
	mock.recorder = &MockAccountPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountPort) EXPECT() *MockAccountPortMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockAccountPort) CreateAccount(ctx context.Context, userID string) (*account.AccountCreationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, userID)
	ret0, _ := ret[0].(*account.AccountCreationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockAccountPortMockRecorder) CreateAccount(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockAccountPort)(nil).CreateAccount), ctx, userID)
}
