// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/action/repository.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	action "gitlab.com/bersufekadgetachew/cbe-super-app-cps-action/internal/domain/action"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateCpsAction mocks base method.
func (m *MockRepository) CreateCpsAction(ctx context.Context, Action action.CPSAction) (action.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCpsAction", ctx, Action)
	ret0, _ := ret[0].(action.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCpsAction indicates an expected call of CreateCpsAction.
func (mr *MockRepositoryMockRecorder) CreateCpsAction(ctx, Action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCpsAction", reflect.TypeOf((*MockRepository)(nil).CreateCpsAction), ctx, Action)
}

// FetchAccountsByAccountNumber mocks base method.
func (m *MockRepository) FetchAccountsByAccountNumber(ctx context.Context, accountNumber string) ([]action.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAccountsByAccountNumber", ctx, accountNumber)
	ret0, _ := ret[0].([]action.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAccountsByAccountNumber indicates an expected call of FetchAccountsByAccountNumber.
func (mr *MockRepositoryMockRecorder) FetchAccountsByAccountNumber(ctx, accountNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAccountsByAccountNumber", reflect.TypeOf((*MockRepository)(nil).FetchAccountsByAccountNumber), ctx, accountNumber)
}

// FetchCpsActionById mocks base method.
func (m *MockRepository) FetchCpsActionById(ctx context.Context, Action_Id string) (action.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchCpsActionById", ctx, Action_Id)
	ret0, _ := ret[0].(action.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchCpsActionById indicates an expected call of FetchCpsActionById.
func (mr *MockRepositoryMockRecorder) FetchCpsActionById(ctx, Action_Id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchCpsActionById", reflect.TypeOf((*MockRepository)(nil).FetchCpsActionById), ctx, Action_Id)
}

// FetchLastCpsActionByMakerID mocks base method.
func (m *MockRepository) FetchLastCpsActionByMakerID(ctx context.Context, makerId string) (action.CPSAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchLastCpsActionByMakerID", ctx, makerId)
	ret0, _ := ret[0].(action.CPSAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchLastCpsActionByMakerID indicates an expected call of FetchLastCpsActionByMakerID.
func (mr *MockRepositoryMockRecorder) FetchLastCpsActionByMakerID(ctx, makerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchLastCpsActionByMakerID", reflect.TypeOf((*MockRepository)(nil).FetchLastCpsActionByMakerID), ctx, makerId)
}

// FetchLinkedAccountById mocks base method.
func (m *MockRepository) FetchLinkedAccountById(ctx context.Context, id []string) ([]action.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchLinkedAccountById", ctx, id)
	ret0, _ := ret[0].([]action.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchLinkedAccountById indicates an expected call of FetchLinkedAccountById.
func (mr *MockRepositoryMockRecorder) FetchLinkedAccountById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchLinkedAccountById", reflect.TypeOf((*MockRepository)(nil).FetchLinkedAccountById), ctx, id)
}

// GetAllHqServices mocks base method.
func (m *MockRepository) GetAllHqServices(ctx context.Context) ([]action.ServiceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHqServices", ctx)
	ret0, _ := ret[0].([]action.ServiceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllHqServices indicates an expected call of GetAllHqServices.
func (mr *MockRepositoryMockRecorder) GetAllHqServices(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHqServices", reflect.TypeOf((*MockRepository)(nil).GetAllHqServices), ctx)
}

// GetAllHqServicesPaginated mocks base method.
func (m *MockRepository) GetAllHqServicesPaginated(ctx context.Context, offset, limit int) ([]action.ServiceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHqServicesPaginated", ctx, offset, limit)
	ret0, _ := ret[0].([]action.ServiceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllHqServicesPaginated indicates an expected call of GetAllHqServicesPaginated.
func (mr *MockRepositoryMockRecorder) GetAllHqServicesPaginated(ctx, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHqServicesPaginated", reflect.TypeOf((*MockRepository)(nil).GetAllHqServicesPaginated), ctx, offset, limit)
}

// GetHqServiceById mocks base method.
func (m *MockRepository) GetHqServiceById(ctx context.Context, id string) (action.ServiceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHqServiceById", ctx, id)
	ret0, _ := ret[0].(action.ServiceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHqServiceById indicates an expected call of GetHqServiceById.
func (mr *MockRepositoryMockRecorder) GetHqServiceById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHqServiceById", reflect.TypeOf((*MockRepository)(nil).GetHqServiceById), ctx, id)
}

// UpdateAccount mocks base method.
func (m *MockRepository) UpdateAccount(ctx context.Context, linkedAccount action.LinkedAccount) (action.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, linkedAccount)
	ret0, _ := ret[0].(action.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockRepositoryMockRecorder) UpdateAccount(ctx, linkedAccount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockRepository)(nil).UpdateAccount), ctx, linkedAccount)
}

// UpdateAccounts mocks base method.
func (m *MockRepository) UpdateAccounts(ctx context.Context, linkedAccounts []action.LinkedAccount) ([]action.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccounts", ctx, linkedAccounts)
	ret0, _ := ret[0].([]action.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccounts indicates an expected call of UpdateAccounts.
func (mr *MockRepositoryMockRecorder) UpdateAccounts(ctx, linkedAccounts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccounts", reflect.TypeOf((*MockRepository)(nil).UpdateAccounts), ctx, linkedAccounts)
}

// UpdateCpsAction mocks base method.
func (m *MockRepository) UpdateCpsAction(ctx context.Context, Action action.CPSAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCpsAction", ctx, Action)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCpsAction indicates an expected call of UpdateCpsAction.
func (mr *MockRepositoryMockRecorder) UpdateCpsAction(ctx, Action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCpsAction", reflect.TypeOf((*MockRepository)(nil).UpdateCpsAction), ctx, Action)
}

// UpdateHqService mocks base method.
func (m *MockRepository) UpdateHqService(ctx context.Context, service action.ServiceDetails) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHqService", ctx, service)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHqService indicates an expected call of UpdateHqService.
func (mr *MockRepositoryMockRecorder) UpdateHqService(ctx, service interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHqService", reflect.TypeOf((*MockRepository)(nil).UpdateHqService), ctx, service)
}
