// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/action/service_impl.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	action "gitlab.com/bersufekadgetachew/cbe-super-app-cps-action/internal/domain/action"
)

// MockServiceImpl is a mock of ServiceImpl interface.
type MockServiceImpl struct {
	ctrl     *gomock.Controller
	recorder *MockServiceImplMockRecorder
}

// MockServiceImplMockRecorder is the mock recorder for MockServiceImpl.
type MockServiceImplMockRecorder struct {
	mock *MockServiceImpl
}

// NewMockServiceImpl creates a new mock instance.
func NewMockServiceImpl(ctrl *gomock.Controller) *MockServiceImpl {
	mock := &MockServiceImpl{ctrl: ctrl}
	mock.recorder = &MockServiceImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceImpl) EXPECT() *MockServiceImplMockRecorder {
	return m.recorder
}

// GetAccountByAccount mocks base method.
func (m *MockServiceImpl) GetAccountByAccount(ctx context.Context, Account string) ([]action.LinkedAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByAccount", ctx, Account)
	ret0, _ := ret[0].([]action.LinkedAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByAccount indicates an expected call of GetAccountByAccount.
func (mr *MockServiceImplMockRecorder) GetAccountByAccount(ctx, Account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByAccount", reflect.TypeOf((*MockServiceImpl)(nil).GetAccountByAccount), ctx, Account)
}

// GetServicePaginated mocks base method.
func (m *MockServiceImpl) GetServicePaginated(ctx context.Context, limit, offset int) ([]action.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServicePaginated", ctx, limit, offset)
	ret0, _ := ret[0].([]action.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServicePaginated indicates an expected call of GetServicePaginated.
func (mr *MockServiceImplMockRecorder) GetServicePaginated(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServicePaginated", reflect.TypeOf((*MockServiceImpl)(nil).GetServicePaginated), ctx, limit, offset)
}

// RemoveCif mocks base method.
func (m *MockServiceImpl) RemoveCif(ctx context.Context, action_id string, action bool, checker_id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCif", ctx, action_id, action, checker_id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCif indicates an expected call of RemoveCif.
func (mr *MockServiceImplMockRecorder) RemoveCif(ctx, action_id, action, checker_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCif", reflect.TypeOf((*MockServiceImpl)(nil).RemoveCif), ctx, action_id, action, checker_id)
}

// RemoveCifRequest mocks base method.
func (m *MockServiceImpl) RemoveCifRequest(ctx context.Context, id []string, action bool, maker_id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCifRequest", ctx, id, action, maker_id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveCifRequest indicates an expected call of RemoveCifRequest.
func (mr *MockServiceImplMockRecorder) RemoveCifRequest(ctx, id, action, maker_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCifRequest", reflect.TypeOf((*MockServiceImpl)(nil).RemoveCifRequest), ctx, id, action, maker_id)
}

// UpdateServiceFlag mocks base method.
func (m *MockServiceImpl) UpdateServiceFlag(ctx context.Context, action_id string, action bool, checker_id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceFlag", ctx, action_id, action, checker_id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServiceFlag indicates an expected call of UpdateServiceFlag.
func (mr *MockServiceImplMockRecorder) UpdateServiceFlag(ctx, action_id, action, checker_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceFlag", reflect.TypeOf((*MockServiceImpl)(nil).UpdateServiceFlag), ctx, action_id, action, checker_id)
}

// UpdateServiceFlagRequest mocks base method.
func (m *MockServiceImpl) UpdateServiceFlagRequest(ctx context.Context, id string, action bool, maker_id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceFlagRequest", ctx, id, action, maker_id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServiceFlagRequest indicates an expected call of UpdateServiceFlagRequest.
func (mr *MockServiceImplMockRecorder) UpdateServiceFlagRequest(ctx, id, action, maker_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceFlagRequest", reflect.TypeOf((*MockServiceImpl)(nil).UpdateServiceFlagRequest), ctx, id, action, maker_id)
}
