// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/miniapp/service_impl.go

// Package mock_services is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	miniapp "gitlab.com/bersufekadgetachew/cbe-super-app-cps-action/internal/domain/miniapp"
)

// MockMiniAppService is a mock of MiniAppService interface.
type MockMiniAppService struct {
	ctrl     *gomock.Controller
	recorder *MockMiniAppServiceMockRecorder
}

// MockMiniAppServiceMockRecorder is the mock recorder for MockMiniAppService.
type MockMiniAppServiceMockRecorder struct {
	mock *MockMiniAppService
}

// NewMockMiniAppService creates a new mock instance.
func NewMockMiniAppService(ctrl *gomock.Controller) *MockMiniAppService {
	mock := &MockMiniAppService{ctrl: ctrl}
	mock.recorder = &MockMiniAppServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiniAppService) EXPECT() *MockMiniAppServiceMockRecorder {
	return m.recorder
}

// CheckMiniApp mocks base method.
func (m *MockMiniAppService) CheckMiniApp(ctx context.Context, actionId string, action bool, checkerId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckMiniApp", ctx, actionId, action, checkerId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckMiniApp indicates an expected call of CheckMiniApp.
func (mr *MockMiniAppServiceMockRecorder) CheckMiniApp(ctx, actionId, action, checkerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMiniApp", reflect.TypeOf((*MockMiniAppService)(nil).CheckMiniApp), ctx, actionId, action, checkerId)
}

// CreateMiniAppAction mocks base method.
func (m *MockMiniAppService) CreateMiniAppAction(ctx context.Context, miniApp miniapp.MiniApp, makerId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMiniAppAction", ctx, miniApp, makerId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMiniAppAction indicates an expected call of CreateMiniAppAction.
func (mr *MockMiniAppServiceMockRecorder) CreateMiniAppAction(ctx, miniApp, makerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMiniAppAction", reflect.TypeOf((*MockMiniAppService)(nil).CreateMiniAppAction), ctx, miniApp, makerId)
}
