// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/users/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	users "cbe-super-app-member-users/internal/domain/users"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// FindActiveLinkedAccounts mocks base method.
func (m *MockUserRepository) FindActiveLinkedAccounts(ctx context.Context, userID string) ([]users.LinkedAccountDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveLinkedAccounts", ctx, userID)
	ret0, _ := ret[0].([]users.LinkedAccountDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveLinkedAccounts indicates an expected call of FindActiveLinkedAccounts.
func (mr *MockUserRepositoryMockRecorder) FindActiveLinkedAccounts(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveLinkedAccounts", reflect.TypeOf((*MockUserRepository)(nil).FindActiveLinkedAccounts), ctx, userID)
}

// FindByEmail mocks base method.
func (m *MockUserRepository) FindByEmail(ctx context.Context, email string) (*users.UserEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*users.UserEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserRepositoryMockRecorder) FindByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserRepository)(nil).FindByEmail), ctx, email)
}

// FindByID mocks base method.
func (m *MockUserRepository) FindByID(ctx context.Context, id string) (*users.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*users.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepository)(nil).FindByID), ctx, id)
}

// FindOTP mocks base method.
func (m *MockUserRepository) FindOTP(ctx context.Context, userID, email string) (*users.OTPRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOTP", ctx, userID, email)
	ret0, _ := ret[0].(*users.OTPRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOTP indicates an expected call of FindOTP.
func (mr *MockUserRepositoryMockRecorder) FindOTP(ctx, userID, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOTP", reflect.TypeOf((*MockUserRepository)(nil).FindOTP), ctx, userID, email)
}

// StoreOTP mocks base method.
func (m *MockUserRepository) StoreOTP(ctx context.Context, otp *users.OTPRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreOTP", ctx, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreOTP indicates an expected call of StoreOTP.
func (mr *MockUserRepositoryMockRecorder) StoreOTP(ctx, otp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreOTP", reflect.TypeOf((*MockUserRepository)(nil).StoreOTP), ctx, otp)
}

// UpdateUserEmail mocks base method.
func (m *MockUserRepository) UpdateUserEmail(ctx context.Context, userID, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserEmail", ctx, userID, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserEmail indicates an expected call of UpdateUserEmail.
func (mr *MockUserRepositoryMockRecorder) UpdateUserEmail(ctx, userID, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserEmail", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserEmail), ctx, userID, email)
}
