// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/service/repository.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	service "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/domain/service"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ApproveServiceDetails mocks base method.
func (m *MockRepository) ApproveServiceDetails(ctx context.Context, actionID string, approve bool, checkerID, rejectionReason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveServiceDetails", ctx, actionID, approve, checkerID, rejectionReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveServiceDetails indicates an expected call of ApproveServiceDetails.
func (mr *MockRepositoryMockRecorder) ApproveServiceDetails(ctx, actionID, approve, checkerID, rejectionReason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveServiceDetails", reflect.TypeOf((*MockRepository)(nil).ApproveServiceDetails), ctx, actionID, approve, checkerID, rejectionReason)
}

// ApproveServiceFeeUpdate mocks base method.
func (m *MockRepository) ApproveServiceFeeUpdate(ctx context.Context, cpsAction string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveServiceFeeUpdate", ctx, cpsAction)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveServiceFeeUpdate indicates an expected call of ApproveServiceFeeUpdate.
func (mr *MockRepositoryMockRecorder) ApproveServiceFeeUpdate(ctx, cpsAction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveServiceFeeUpdate", reflect.TypeOf((*MockRepository)(nil).ApproveServiceFeeUpdate), ctx, cpsAction)
}

// GetAllServiceDetails mocks base method.
func (m *MockRepository) GetAllServiceDetails(ctx context.Context) ([]*service.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllServiceDetails", ctx)
	ret0, _ := ret[0].([]*service.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllServiceDetails indicates an expected call of GetAllServiceDetails.
func (mr *MockRepositoryMockRecorder) GetAllServiceDetails(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllServiceDetails", reflect.TypeOf((*MockRepository)(nil).GetAllServiceDetails), ctx)
}

// GetOneServiceDetail mocks base method.
func (m *MockRepository) GetOneServiceDetail(ctx context.Context, id string) (service.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneServiceDetail", ctx, id)
	ret0, _ := ret[0].(service.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneServiceDetail indicates an expected call of GetOneServiceDetail.
func (mr *MockRepositoryMockRecorder) GetOneServiceDetail(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneServiceDetail", reflect.TypeOf((*MockRepository)(nil).GetOneServiceDetail), ctx, id)
}

// InitiateServiceFeeUpdate mocks base method.
func (m *MockRepository) InitiateServiceFeeUpdate(ctx context.Context, cpsAction service.CPSAction) (service.UpdateServiceDetailsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateServiceFeeUpdate", ctx, cpsAction)
	ret0, _ := ret[0].(service.UpdateServiceDetailsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateServiceFeeUpdate indicates an expected call of InitiateServiceFeeUpdate.
func (mr *MockRepositoryMockRecorder) InitiateServiceFeeUpdate(ctx, cpsAction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateServiceFeeUpdate", reflect.TypeOf((*MockRepository)(nil).InitiateServiceFeeUpdate), ctx, cpsAction)
}

// RejectServiceFeeUpdate mocks base method.
func (m *MockRepository) RejectServiceFeeUpdate(ctx context.Context, cpsAction string, action_code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectServiceFeeUpdate", ctx, cpsAction, action_code)
	// ret0, _ := ret[0].(service.UpdateServiceDetailsResponse)
	ret1, _ := ret[1].(error)
	return ret1
}

// RejectServiceFeeUpdate indicates an expected call of RejectServiceFeeUpdate.
func (mr *MockRepositoryMockRecorder) RejectServiceFeeUpdate(ctx, cpsAction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectServiceFeeUpdate", reflect.TypeOf((*MockRepository)(nil).RejectServiceFeeUpdate), ctx, cpsAction)
}

// UpdateCapMinAmount mocks base method.
func (m *MockRepository) UpdateCapMinAmount(ctx context.Context, id string, minAmount uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCapMinAmount", ctx, id, minAmount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCapMinAmount indicates an expected call of UpdateCapMinAmount.
func (mr *MockRepositoryMockRecorder) UpdateCapMinAmount(ctx, id, minAmount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCapMinAmount", reflect.TypeOf((*MockRepository)(nil).UpdateCapMinAmount), ctx, id, minAmount)
}

// UpdateOneServiceDetailRequest mocks base method.
func (m *MockRepository) UpdateOneServiceDetailRequest(ctx context.Context, id string, update service.Service) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOneServiceDetailRequest", ctx, id, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOneServiceDetailRequest indicates an expected call of UpdateOneServiceDetailRequest.
func (mr *MockRepositoryMockRecorder) UpdateOneServiceDetailRequest(ctx, id, update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOneServiceDetailRequest", reflect.TypeOf((*MockRepository)(nil).UpdateOneServiceDetailRequest), ctx, id, update)
}
