// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/event/service.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	event "github.com/CBE-Super-App/cbe-super-app-cps-action/internal/domain/event"
	gomock "github.com/golang/mock/gomock"
)

// MockEventService is a mock of EventService interface.
type MockEventService struct {
	ctrl     *gomock.Controller
	recorder *MockEventServiceMockRecorder
}

// MockEventServiceMockRecorder is the mock recorder for MockEventService.
type MockEventServiceMockRecorder struct {
	mock *MockEventService
}

// NewMockEventService creates a new mock instance.
func NewMockEventService(ctrl *gomock.Controller) *MockEventService {
	mock := &MockEventService{ctrl: ctrl}
	mock.recorder = &MockEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventService) EXPECT() *MockEventServiceMockRecorder {
	return m.recorder
}

// ApproveEventRequest mocks base method.
func (m *MockEventService) ApproveEventRequest(ctx context.Context, action_id string, action_taken bool, checkerID, checkerName, checkerPhone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveEventRequest", ctx, action_id, action_taken, checkerID, checkerName, checkerPhone)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveEventRequest indicates an expected call of ApproveEventRequest.
func (mr *MockEventServiceMockRecorder) ApproveEventRequest(ctx, action_id, action_taken, checkerID, checkerName, checkerPhone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveEventRequest", reflect.TypeOf((*MockEventService)(nil).ApproveEventRequest), ctx, action_id, action_taken, checkerID, checkerName, checkerPhone)
}

// CreateEventRequest mocks base method.
func (m *MockEventService) CreateEventRequest(ctx context.Context, event event.Event, ticket event.Ticket, makerID, makerName, makerPhone string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEventRequest", ctx, event, ticket, makerID, makerName, makerPhone)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEventRequest indicates an expected call of CreateEventRequest.
func (mr *MockEventServiceMockRecorder) CreateEventRequest(ctx, event, ticket, makerID, makerName, makerPhone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEventRequest", reflect.TypeOf((*MockEventService)(nil).CreateEventRequest), ctx, event, ticket, makerID, makerName, makerPhone)
}

// FetchEvent mocks base method.
func (m *MockEventService) FetchEvent(ctx context.Context, limit, offset int) ([]event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchEvent", ctx, limit, offset)
	ret0, _ := ret[0].([]event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchEvent indicates an expected call of FetchEvent.
func (mr *MockEventServiceMockRecorder) FetchEvent(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchEvent", reflect.TypeOf((*MockEventService)(nil).FetchEvent), ctx, limit, offset)
}

// FetchEventById mocks base method.
func (m *MockEventService) FetchEventById(ctx context.Context, event_id string) (event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchEventById", ctx, event_id)
	ret0, _ := ret[0].(event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchEventById indicates an expected call of FetchEventById.
func (mr *MockEventServiceMockRecorder) FetchEventById(ctx, event_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchEventById", reflect.TypeOf((*MockEventService)(nil).FetchEventById), ctx, event_id)
}
