package initiator

// MongoDB Collection Names
var (
	DeviceVersionControllCollection  = "device_version_control"
	MembersCollection                = "members"
	HQCollection                     = "hq"
	OTPsCollection                   = "otps"
	MemberDevicesHistoryCollection   = "member_device_histories"
	PINResetsCollection              = "pin_reset_sessions"
	CPSActionsCollection             = "cps_actions"
	AuthTierCollection               = "auth_tier"
	AccountBlockCollection           = "account_block"
	CardsCollection                  = "portal_cards"
	MiniAppsCollection               = "mini_app"
	MiniAppMerchantCollection        = "mini_app_merchant"
	EcommerceMerchantCollection      = "ecommerce_merchants"
	AccessListCollection             = "access_list"
	AvatarsCollection                = "avatars"
	BranchUserCollection             = "branch_user"
	AdvertsCollection                = "adverts"
	ArchievedLinkedAccountCollection = "archived_linked_account"
	BanksCollection                  = "banks"
	BudgetCategoryCollection         = "budget_category"
	LinkedAccountsCollection         = "linked_account"
	CPSUsersCollection               = "cps_users"
	DonationsCollection              = "donations"
	DonationCategoriesCollection     = "donation_categories"
	ArchievedUsersCollection         = "archived_users"
	DonationCompaniesCollection      = "donation_companies"
	EventsCollection                 = "events"
	PasswordRulesCollection          = "password_rules"
	FeedbackCollection               = "feedback"
	IconsCollection                  = "icons"
	NotificationsCollection          = "notifications"
	ServicesCollection               = "services"
	ValidationRulesCollection        = "validation_rule"
	WalletsCollection                = "wallets"
	TopUpsCollection                 = "topups"
	DepartmentsCollection            = "department"
	JobRolesCollection               = "job_roles"
	PermissionGroupsCollection       = "permission_groups"
	PermissionCategoryCollection     = "permission_category"
	PermissionCollection             = "permission"
	NewsArticlesCollection           = "news_articles"
	NewsCategoriesCollection         = "news_categories"
	NewsShortVideosCollection        = "news_short_videos"
	NewsTagsCollection               = "news_tags"
	NewsCategoryCollection           = "news_category"
	CustomersKYCCollection           = "customer_kyc"
	BPSActionRolesCollection         = "action_roles"
	BPSActionListCollection          = "bps_action_list"
	CPSActionListCollection          = "cps_action_list"
	RolesCollection                  = "roles"

	BPSActionApproveIndexCollection = "bps_action_approver_index"

	MiniAppCategoryCollection = "mini_app_categories"

	CPSActionRolesCollection         = "cps_action_roles"
	CPSActionApproveIndexCollection  = "cps_action_approver_index"
	EventMerchantsCollection         = "event_merchants"
	MiniAppProductCodes              = "mini_app_product_codes"
	AccessListSegmentationCollection = "access_list_segmentation"
	CustomerSegmentationCollection   = "customer_segmentations"
	CPSRolesCollection               = "cps_roles"
)

// Minio Bucket Names
var (
	AvatarsBucketName              = "avatar"
	EventsBucketName               = "events"
	BanksBucketName                = "banks"
	WalletsBucketName              = "wallets"
	TopUpsBucketName               = "topups"
	MiniAppsBucketName             = "miniapps"
	DonationsBucketName            = "donation"
	DonationIconsBucketName        = "donation-icon"
	DonationCompanysLogoBucketName = "donation-company-logo"
	BudgetCategoryBucketName       = "budget-category"
	AmountBasedAuthBucketName      = "amount-based-auth"
	AdvertBucketName               = "advert-bucket"
	VaultCategoryBucketName        = "vault-category"
)
