package initiator

// MongoDB Collection Names
var (
	DeviceVersionControllCollection  = "device_version_control"
	MembersCollection                = "members"
	HQCollection                     = "hq"
	OTPsCollection                   = "otps"
	MemberDevicesHistoryCollection   = "member_device_histories"
	PINResetsCollection              = "pin_reset_sessions"
	CPSActionsCollection             = "cps_actions"
	AuthTierCollection               = "auth_tier"
	AccountBlockCollection           = "account_block"
	CardsCollection                  = "portal_cards"
	MiniAppsCollection               = "mini_app"
	MiniAppMerchantCollection        = "mini_app_merchant"
	AccessListCollection             = "access_list"
	AvatarsCollection                = "avatars"
	BranchUserCollection             = "branch_user"
	AdvertsCollection                = "adverts"
	ArchievedLinkedAccountCollection = "archived_linked_account"
	BanksCollection                  = "banks"
	BudgetCategoryCollection         = "budget_category"
	LinkedAccountsCollection         = "linked_account"
	CPSUsersCollection               = "cps_users"
	DonationsCollection              = "donations"
	DonationCategoriesCollection     = "donation_categories"
	ArchievedUsersCollection         = "archived_users"
	DonationCompaniesCollection      = "donation_companies"
	EventsCollection                 = "events"
	PasswordRulesCollection          = "password_rules"
	FeedbackCollection               = "feedback"
	IconsCollection                  = "icons"
	NotificationsCollection          = "notifications"
	ServicesCollection               = "services"
	ValidationRulesCollection        = "validation_rule"
	WalletsCollection                = "wallets"
	TopUpsCollection                 = "topups"
	DepartmentsCollection            = "department"
	PermissionGroupsCollection       = "permission_groups"
	PermissionCategoryCollection     = "permission_category"
	PermissionCollection             = "permission"
	NewsArticlesCollection           = "news_articles"
	NewsCategoriesCollection         = "news_categories"
	NewsShortVideosCollection        = "news_short_videos"
	NewsTagsCollection               = "news_tags"
	NewsCategoryCollection           = "news_category"
	CustomersKYCCollection           = "customer_kyc"
	BPSActionRolesCollection         = "action_roles"
)

// Minio Bucket Names
var (
	AvatarsBucketName              = "avatar"
	EventsBucketName               = "events"
	BanksBucketName                = "banks"
	WalletsBucketName              = "wallets"
	TopUpsBucketName               = "topups"
	MiniAppsBucketName             = "miniapps"
	DonationsBucketName            = "donation"
	DonationIconsBucketName        = "donation-icon"
	DonationCompanysLogoBucketName = "donation-company-logo"
	BudgetCategoryBucketName       = "budget-category"
	AmountBasedAuthBucketName      = "amount-based-auth"
	AdvertBucketName               = "advert-bucket"
	VaultCategoryBucketName        = "vault-category"
)
